package ihh.slabsstairswalls.minecraft;

import ihh.slabsstairswalls.ItemModels;
import net.minecraft.data.DataGenerator;
import net.minecraftforge.client.model.generators.ExistingFileHelper;

public final class MinecraftItemModels extends ItemModels {
    public MinecraftItemModels(DataGenerator g, ExistingFileHelper e) {
        super(g, e);
    }

    @Override
    protected void registerModels() {
        parentFenceGate(MinecraftBlocks.NETHER_BRICK_FENCE_GATE, "nether_brick");
        parentStairs(MinecraftBlocks.CUT_RED_SANDSTONE_STAIRS, "cut_red_sandstone");
        parentStairs(MinecraftBlocks.CUT_SANDSTONE_STAIRS, "cut_sandstone");
        parentStairs(MinecraftBlocks.SMOOTH_STONE_STAIRS, "smooth_stone");
        parentWall(MinecraftBlocks.CUT_RED_SANDSTONE_WALL, "cut_red_sandstone");
        parentWall(MinecraftBlocks.CUT_SANDSTONE_WALL, "cut_sandstone");
        parentWall(MinecraftBlocks.DARK_PRISMARINE_WALL, "dark_prismarine");
        parentWall(MinecraftBlocks.PRISMARINE_BRICK_WALL, "prismarine_bricks");
        parentWall(MinecraftBlocks.POLISHED_ANDESITE_WALL, "polished_andesite");
        parentWall(MinecraftBlocks.POLISHED_DIORITE_WALL, "polished_diorite");
        parentWall(MinecraftBlocks.POLISHED_GRANITE_WALL, "polished_granite");
        parentWall(MinecraftBlocks.PURPUR_WALL, "purpur");
        parentWall(MinecraftBlocks.QUARTZ_WALL, "quartz");
        parentWall(MinecraftBlocks.SMOOTH_QUARTZ_WALL, "smooth_quartz");
        parentWall(MinecraftBlocks.SMOOTH_RED_SANDSTONE_WALL, "smooth_red_sandstone");
        parentWall(MinecraftBlocks.SMOOTH_SANDSTONE_WALL, "smooth_sandstone");
        parentWall(MinecraftBlocks.SMOOTH_STONE_WALL, "smooth_stone");
        parentWall(MinecraftBlocks.STONE_WALL, "stone");
        parentSlab(MinecraftBlocks.OAK_SLAB, "oak");
        parentSlab(MinecraftBlocks.SPRUCE_SLAB, "spruce");
        parentSlab(MinecraftBlocks.BIRCH_SLAB, "birch");
        parentSlab(MinecraftBlocks.JUNGLE_SLAB, "jungle");
        parentSlab(MinecraftBlocks.ACACIA_SLAB, "acacia");
        parentSlab(MinecraftBlocks.DARK_OAK_SLAB, "dark_oak");
        parentSlab(MinecraftBlocks.STRIPPED_OAK_SLAB, "stripped_oak");
        parentSlab(MinecraftBlocks.STRIPPED_SPRUCE_SLAB, "stripped_spruce");
        parentSlab(MinecraftBlocks.STRIPPED_BIRCH_SLAB, "stripped_birch");
        parentSlab(MinecraftBlocks.STRIPPED_JUNGLE_SLAB, "stripped_jungle");
        parentSlab(MinecraftBlocks.STRIPPED_ACACIA_SLAB, "stripped_acacia");
        parentSlab(MinecraftBlocks.STRIPPED_DARK_OAK_SLAB, "stripped_dark_oak");
        parentSlab(MinecraftBlocks.WHITE_CONCRETE_SLAB, "white_concrete");
        parentSlab(MinecraftBlocks.ORANGE_CONCRETE_SLAB, "orange_concrete");
        parentSlab(MinecraftBlocks.MAGENTA_CONCRETE_SLAB, "magenta_concrete");
        parentSlab(MinecraftBlocks.LIGHT_BLUE_CONCRETE_SLAB, "light_blue_concrete");
        parentSlab(MinecraftBlocks.YELLOW_CONCRETE_SLAB, "yellow_concrete");
        parentSlab(MinecraftBlocks.LIME_CONCRETE_SLAB, "lime_concrete");
        parentSlab(MinecraftBlocks.PINK_CONCRETE_SLAB, "pink_concrete");
        parentSlab(MinecraftBlocks.GRAY_CONCRETE_SLAB, "gray_concrete");
        parentSlab(MinecraftBlocks.LIGHT_GRAY_CONCRETE_SLAB, "light_gray_concrete");
        parentSlab(MinecraftBlocks.CYAN_CONCRETE_SLAB, "cyan_concrete");
        parentSlab(MinecraftBlocks.PURPLE_CONCRETE_SLAB, "purple_concrete");
        parentSlab(MinecraftBlocks.BLUE_CONCRETE_SLAB, "blue_concrete");
        parentSlab(MinecraftBlocks.BROWN_CONCRETE_SLAB, "brown_concrete");
        parentSlab(MinecraftBlocks.GREEN_CONCRETE_SLAB, "green_concrete");
        parentSlab(MinecraftBlocks.RED_CONCRETE_SLAB, "red_concrete");
        parentSlab(MinecraftBlocks.BLACK_CONCRETE_SLAB, "black_concrete");
        parentSlab(MinecraftBlocks.WHITE_CONCRETE_POWDER_SLAB, "white_concrete_powder");
        parentSlab(MinecraftBlocks.ORANGE_CONCRETE_POWDER_SLAB, "orange_concrete_powder");
        parentSlab(MinecraftBlocks.MAGENTA_CONCRETE_POWDER_SLAB, "magenta_concrete_powder");
        parentSlab(MinecraftBlocks.LIGHT_BLUE_CONCRETE_POWDER_SLAB, "light_blue_concrete_powder");
        parentSlab(MinecraftBlocks.YELLOW_CONCRETE_POWDER_SLAB, "yellow_concrete_powder");
        parentSlab(MinecraftBlocks.LIME_CONCRETE_POWDER_SLAB, "lime_concrete_powder");
        parentSlab(MinecraftBlocks.PINK_CONCRETE_POWDER_SLAB, "pink_concrete_powder");
        parentSlab(MinecraftBlocks.GRAY_CONCRETE_POWDER_SLAB, "gray_concrete_powder");
        parentSlab(MinecraftBlocks.LIGHT_GRAY_CONCRETE_POWDER_SLAB, "light_gray_concrete_powder");
        parentSlab(MinecraftBlocks.CYAN_CONCRETE_POWDER_SLAB, "cyan_concrete_powder");
        parentSlab(MinecraftBlocks.PURPLE_CONCRETE_POWDER_SLAB, "purple_concrete_powder");
        parentSlab(MinecraftBlocks.BLUE_CONCRETE_POWDER_SLAB, "blue_concrete_powder");
        parentSlab(MinecraftBlocks.BROWN_CONCRETE_POWDER_SLAB, "brown_concrete_powder");
        parentSlab(MinecraftBlocks.GREEN_CONCRETE_POWDER_SLAB, "green_concrete_powder");
        parentSlab(MinecraftBlocks.RED_CONCRETE_POWDER_SLAB, "red_concrete_powder");
        parentSlab(MinecraftBlocks.BLACK_CONCRETE_POWDER_SLAB, "black_concrete_powder");
        parentSlab(MinecraftBlocks.WHITE_GLAZED_TERRACOTTA_SLAB, "white_glazed_terracotta");
        parentSlab(MinecraftBlocks.ORANGE_GLAZED_TERRACOTTA_SLAB, "orange_glazed_terracotta");
        parentSlab(MinecraftBlocks.MAGENTA_GLAZED_TERRACOTTA_SLAB, "magenta_glazed_terracotta");
        parentSlab(MinecraftBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_SLAB, "light_blue_glazed_terracotta");
        parentSlab(MinecraftBlocks.YELLOW_GLAZED_TERRACOTTA_SLAB, "yellow_glazed_terracotta");
        parentSlab(MinecraftBlocks.LIME_GLAZED_TERRACOTTA_SLAB, "lime_glazed_terracotta");
        parentSlab(MinecraftBlocks.PINK_GLAZED_TERRACOTTA_SLAB, "pink_glazed_terracotta");
        parentSlab(MinecraftBlocks.GRAY_GLAZED_TERRACOTTA_SLAB, "gray_glazed_terracotta");
        parentSlab(MinecraftBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_SLAB, "light_gray_glazed_terracotta");
        parentSlab(MinecraftBlocks.CYAN_GLAZED_TERRACOTTA_SLAB, "cyan_glazed_terracotta");
        parentSlab(MinecraftBlocks.PURPLE_GLAZED_TERRACOTTA_SLAB, "purple_glazed_terracotta");
        parentSlab(MinecraftBlocks.BLUE_GLAZED_TERRACOTTA_SLAB, "blue_glazed_terracotta");
        parentSlab(MinecraftBlocks.BROWN_GLAZED_TERRACOTTA_SLAB, "brown_glazed_terracotta");
        parentSlab(MinecraftBlocks.GREEN_GLAZED_TERRACOTTA_SLAB, "green_glazed_terracotta");
        parentSlab(MinecraftBlocks.RED_GLAZED_TERRACOTTA_SLAB, "red_glazed_terracotta");
        parentSlab(MinecraftBlocks.BLACK_GLAZED_TERRACOTTA_SLAB, "black_glazed_terracotta");
        parentSlab(MinecraftBlocks.WHITE_STAINED_GLASS_SLAB, "white_stained_glass");
        parentSlab(MinecraftBlocks.ORANGE_STAINED_GLASS_SLAB, "orange_stained_glass");
        parentSlab(MinecraftBlocks.MAGENTA_STAINED_GLASS_SLAB, "magenta_stained_glass");
        parentSlab(MinecraftBlocks.LIGHT_BLUE_STAINED_GLASS_SLAB, "light_blue_stained_glass");
        parentSlab(MinecraftBlocks.YELLOW_STAINED_GLASS_SLAB, "yellow_stained_glass");
        parentSlab(MinecraftBlocks.LIME_STAINED_GLASS_SLAB, "lime_stained_glass");
        parentSlab(MinecraftBlocks.PINK_STAINED_GLASS_SLAB, "pink_stained_glass");
        parentSlab(MinecraftBlocks.GRAY_STAINED_GLASS_SLAB, "gray_stained_glass");
        parentSlab(MinecraftBlocks.LIGHT_GRAY_STAINED_GLASS_SLAB, "light_gray_stained_glass");
        parentSlab(MinecraftBlocks.CYAN_STAINED_GLASS_SLAB, "cyan_stained_glass");
        parentSlab(MinecraftBlocks.PURPLE_STAINED_GLASS_SLAB, "purple_stained_glass");
        parentSlab(MinecraftBlocks.BLUE_STAINED_GLASS_SLAB, "blue_stained_glass");
        parentSlab(MinecraftBlocks.BROWN_STAINED_GLASS_SLAB, "brown_stained_glass");
        parentSlab(MinecraftBlocks.GREEN_STAINED_GLASS_SLAB, "green_stained_glass");
        parentSlab(MinecraftBlocks.RED_STAINED_GLASS_SLAB, "red_stained_glass");
        parentSlab(MinecraftBlocks.BLACK_STAINED_GLASS_SLAB, "black_stained_glass");
        parentSlab(MinecraftBlocks.WHITE_TERRACOTTA_SLAB, "white_terracotta");
        parentSlab(MinecraftBlocks.ORANGE_TERRACOTTA_SLAB, "orange_terracotta");
        parentSlab(MinecraftBlocks.MAGENTA_TERRACOTTA_SLAB, "magenta_terracotta");
        parentSlab(MinecraftBlocks.LIGHT_BLUE_TERRACOTTA_SLAB, "light_blue_terracotta");
        parentSlab(MinecraftBlocks.YELLOW_TERRACOTTA_SLAB, "yellow_terracotta");
        parentSlab(MinecraftBlocks.LIME_TERRACOTTA_SLAB, "lime_terracotta");
        parentSlab(MinecraftBlocks.PINK_TERRACOTTA_SLAB, "pink_terracotta");
        parentSlab(MinecraftBlocks.GRAY_TERRACOTTA_SLAB, "gray_terracotta");
        parentSlab(MinecraftBlocks.LIGHT_GRAY_TERRACOTTA_SLAB, "light_gray_terracotta");
        parentSlab(MinecraftBlocks.CYAN_TERRACOTTA_SLAB, "cyan_terracotta");
        parentSlab(MinecraftBlocks.PURPLE_TERRACOTTA_SLAB, "purple_terracotta");
        parentSlab(MinecraftBlocks.BLUE_TERRACOTTA_SLAB, "blue_terracotta");
        parentSlab(MinecraftBlocks.BROWN_TERRACOTTA_SLAB, "brown_terracotta");
        parentSlab(MinecraftBlocks.GREEN_TERRACOTTA_SLAB, "green_terracotta");
        parentSlab(MinecraftBlocks.RED_TERRACOTTA_SLAB, "red_terracotta");
        parentSlab(MinecraftBlocks.BLACK_TERRACOTTA_SLAB, "black_terracotta");
        parentSlab(MinecraftBlocks.WHITE_WOOL_SLAB, "white_wool");
        parentSlab(MinecraftBlocks.ORANGE_WOOL_SLAB, "orange_wool");
        parentSlab(MinecraftBlocks.MAGENTA_WOOL_SLAB, "magenta_wool");
        parentSlab(MinecraftBlocks.LIGHT_BLUE_WOOL_SLAB, "light_blue_wool");
        parentSlab(MinecraftBlocks.YELLOW_WOOL_SLAB, "yellow_wool");
        parentSlab(MinecraftBlocks.LIME_WOOL_SLAB, "lime_wool");
        parentSlab(MinecraftBlocks.PINK_WOOL_SLAB, "pink_wool");
        parentSlab(MinecraftBlocks.GRAY_WOOL_SLAB, "gray_wool");
        parentSlab(MinecraftBlocks.LIGHT_GRAY_WOOL_SLAB, "light_gray_wool");
        parentSlab(MinecraftBlocks.CYAN_WOOL_SLAB, "cyan_wool");
        parentSlab(MinecraftBlocks.PURPLE_WOOL_SLAB, "purple_wool");
        parentSlab(MinecraftBlocks.BLUE_WOOL_SLAB, "blue_wool");
        parentSlab(MinecraftBlocks.BROWN_WOOL_SLAB, "brown_wool");
        parentSlab(MinecraftBlocks.GREEN_WOOL_SLAB, "green_wool");
        parentSlab(MinecraftBlocks.RED_WOOL_SLAB, "red_wool");
        parentSlab(MinecraftBlocks.BLACK_WOOL_SLAB, "black_wool");
        parentSlab(MinecraftBlocks.DIRT_SLAB, "dirt");
        parentSlab(MinecraftBlocks.COARSE_DIRT_SLAB, "coarse_dirt");
        parentSlab(MinecraftBlocks.PODZOL_SLAB, "podzol");
        parentSlab(MinecraftBlocks.BEDROCK_SLAB, "bedrock");
        parentSlab(MinecraftBlocks.SAND_SLAB, "sand");
        parentSlab(MinecraftBlocks.RED_SAND_SLAB, "red_sand");
        parentSlab(MinecraftBlocks.GRAVEL_SLAB, "gravel");
        parentSlab(MinecraftBlocks.GOLD_ORE_SLAB, "gold_ore");
        parentSlab(MinecraftBlocks.IRON_ORE_SLAB, "iron_ore");
        parentSlab(MinecraftBlocks.COAL_ORE_SLAB, "coal_ore");
        parentSlab(MinecraftBlocks.SPONGE_SLAB, "sponge");
        parentSlab(MinecraftBlocks.WET_SPONGE_SLAB, "wet_sponge");
        parentSlab(MinecraftBlocks.GLASS_SLAB, "glass");
        parentSlab(MinecraftBlocks.LAPIS_ORE_SLAB, "lapis_ore");
        parentSlab(MinecraftBlocks.LAPIS_BLOCK_SLAB, "lapis_block");
        parentSlab(MinecraftBlocks.CHISELED_SANDSTONE_SLAB, "chiseled_sandstone");
        parentSlab(MinecraftBlocks.GOLD_BLOCK_SLAB, "gold_block");
        parentSlab(MinecraftBlocks.IRON_BLOCK_SLAB, "iron_block");
        parentSlab(MinecraftBlocks.BOOKSHELF_SLAB, "bookshelf");
        parentSlab(MinecraftBlocks.OBSIDIAN_SLAB, "obsidian");
        parentSlab(MinecraftBlocks.PURPUR_PILLAR_SLAB, "purpur_pillar");
        parentSlab(MinecraftBlocks.DIAMOND_ORE_SLAB, "diamond_ore");
        parentSlab(MinecraftBlocks.DIAMOND_BLOCK_SLAB, "diamond_block");
        parentSlab(MinecraftBlocks.REDSTONE_ORE_SLAB, "redstone_ore");
        parentSlab(MinecraftBlocks.ICE_SLAB, "ice");
        parentSlab(MinecraftBlocks.SNOW_SLAB, "snow");
        parentSlab(MinecraftBlocks.CLAY_SLAB, "clay");
        parentSlab(MinecraftBlocks.PUMPKIN_SLAB, "pumpkin");
        parentSlab(MinecraftBlocks.NETHERRACK_SLAB, "netherrack");
        parentSlab(MinecraftBlocks.SOUL_SAND_SLAB, "soul_sand");
        parentSlab(MinecraftBlocks.GLOWSTONE_SLAB, "glowstone");
        parentSlab(MinecraftBlocks.CRACKED_STONE_BRICK_SLAB, "cracked_stone_brick");
        parentSlab(MinecraftBlocks.CHISELED_STONE_BRICK_SLAB, "chiseled_stone_brick");
        parentSlab(MinecraftBlocks.BROWN_MUSHROOM_SLAB, "brown_mushroom");
        parentSlab(MinecraftBlocks.RED_MUSHROOM_SLAB, "red_mushroom");
        parentSlab(MinecraftBlocks.MUSHROOM_STEM_SLAB, "mushroom_stem");
        parentSlab(MinecraftBlocks.MELON_SLAB, "melon");
        parentSlab(MinecraftBlocks.MYCELIUM_SLAB, "mycelium");
        parentSlab(MinecraftBlocks.END_STONE_SLAB, "end_stone");
        parentSlab(MinecraftBlocks.EMERALD_ORE_SLAB, "emerald_ore");
        parentSlab(MinecraftBlocks.EMERALD_BLOCK_SLAB, "emerald_block");
        parentSlab(MinecraftBlocks.REDSTONE_BLOCK_SLAB, "redstone_block");
        parentSlab(MinecraftBlocks.NETHER_QUARTZ_ORE_SLAB, "nether_quartz_ore");
        parentSlab(MinecraftBlocks.CHISELED_QUARTZ_SLAB, "chiseled_quartz");
        parentSlab(MinecraftBlocks.QUARTZ_PILLAR_SLAB, "quartz_pillar");
        parentSlab(MinecraftBlocks.HAY_SLAB, "hay");
        parentSlab(MinecraftBlocks.TERRACOTTA_SLAB, "terracotta");
        parentSlab(MinecraftBlocks.COAL_SLAB, "coal");
        parentSlab(MinecraftBlocks.PACKED_ICE_SLAB, "packed_ice");
        parentSlab(MinecraftBlocks.SLIME_SLAB, "slime");
        parentSlab(MinecraftBlocks.SEA_LANTERN_SLAB, "sea_lantern");
        parentSlab(MinecraftBlocks.CHISELED_RED_SANDSTONE_SLAB, "chiseled_red_sandstone");
        parentSlab(MinecraftBlocks.MAGMA_SLAB, "magma");
        parentSlab(MinecraftBlocks.NETHER_WART_SLAB, "nether_wart");
        parentSlab(MinecraftBlocks.BONE_SLAB, "bone");
        parentSlab(MinecraftBlocks.DEAD_TUBE_CORAL_SLAB, "dead_tube_coral");
        parentSlab(MinecraftBlocks.DEAD_BRAIN_CORAL_SLAB, "dead_brain_coral");
        parentSlab(MinecraftBlocks.DEAD_BUBBLE_CORAL_SLAB, "dead_bubble_coral");
        parentSlab(MinecraftBlocks.DEAD_FIRE_CORAL_SLAB, "dead_fire_coral");
        parentSlab(MinecraftBlocks.DEAD_HORN_CORAL_SLAB, "dead_horn_coral");
        parentSlab(MinecraftBlocks.TUBE_CORAL_SLAB, "tube_coral");
        parentSlab(MinecraftBlocks.BRAIN_CORAL_SLAB, "brain_coral");
        parentSlab(MinecraftBlocks.BUBBLE_CORAL_SLAB, "bubble_coral");
        parentSlab(MinecraftBlocks.FIRE_CORAL_SLAB, "fire_coral");
        parentSlab(MinecraftBlocks.HORN_CORAL_SLAB, "horn_coral");
        parentSlab(MinecraftBlocks.DRIED_KELP_SLAB, "dried_kelp");
        parentSlab(MinecraftBlocks.HONEY_SLAB, "honey");
        parentSlab(MinecraftBlocks.HONEYCOMB_SLAB, "honeycomb");
        parentStairs(MinecraftBlocks.OAK_STAIRS, "oak");
        parentStairs(MinecraftBlocks.SPRUCE_STAIRS, "spruce");
        parentStairs(MinecraftBlocks.BIRCH_STAIRS, "birch");
        parentStairs(MinecraftBlocks.JUNGLE_STAIRS, "jungle");
        parentStairs(MinecraftBlocks.ACACIA_STAIRS, "acacia");
        parentStairs(MinecraftBlocks.DARK_OAK_STAIRS, "dark_oak");
        parentStairs(MinecraftBlocks.STRIPPED_OAK_STAIRS, "stripped_oak");
        parentStairs(MinecraftBlocks.STRIPPED_SPRUCE_STAIRS, "stripped_spruce");
        parentStairs(MinecraftBlocks.STRIPPED_BIRCH_STAIRS, "stripped_birch");
        parentStairs(MinecraftBlocks.STRIPPED_JUNGLE_STAIRS, "stripped_jungle");
        parentStairs(MinecraftBlocks.STRIPPED_ACACIA_STAIRS, "stripped_acacia");
        parentStairs(MinecraftBlocks.STRIPPED_DARK_OAK_STAIRS, "stripped_dark_oak");
        parentStairs(MinecraftBlocks.WHITE_CONCRETE_STAIRS, "white_concrete");
        parentStairs(MinecraftBlocks.ORANGE_CONCRETE_STAIRS, "orange_concrete");
        parentStairs(MinecraftBlocks.MAGENTA_CONCRETE_STAIRS, "magenta_concrete");
        parentStairs(MinecraftBlocks.LIGHT_BLUE_CONCRETE_STAIRS, "light_blue_concrete");
        parentStairs(MinecraftBlocks.YELLOW_CONCRETE_STAIRS, "yellow_concrete");
        parentStairs(MinecraftBlocks.LIME_CONCRETE_STAIRS, "lime_concrete");
        parentStairs(MinecraftBlocks.PINK_CONCRETE_STAIRS, "pink_concrete");
        parentStairs(MinecraftBlocks.GRAY_CONCRETE_STAIRS, "gray_concrete");
        parentStairs(MinecraftBlocks.LIGHT_GRAY_CONCRETE_STAIRS, "light_gray_concrete");
        parentStairs(MinecraftBlocks.CYAN_CONCRETE_STAIRS, "cyan_concrete");
        parentStairs(MinecraftBlocks.PURPLE_CONCRETE_STAIRS, "purple_concrete");
        parentStairs(MinecraftBlocks.BLUE_CONCRETE_STAIRS, "blue_concrete");
        parentStairs(MinecraftBlocks.BROWN_CONCRETE_STAIRS, "brown_concrete");
        parentStairs(MinecraftBlocks.GREEN_CONCRETE_STAIRS, "green_concrete");
        parentStairs(MinecraftBlocks.RED_CONCRETE_STAIRS, "red_concrete");
        parentStairs(MinecraftBlocks.BLACK_CONCRETE_STAIRS, "black_concrete");
        parentStairs(MinecraftBlocks.WHITE_CONCRETE_POWDER_STAIRS, "white_concrete_powder");
        parentStairs(MinecraftBlocks.ORANGE_CONCRETE_POWDER_STAIRS, "orange_concrete_powder");
        parentStairs(MinecraftBlocks.MAGENTA_CONCRETE_POWDER_STAIRS, "magenta_concrete_powder");
        parentStairs(MinecraftBlocks.LIGHT_BLUE_CONCRETE_POWDER_STAIRS, "light_blue_concrete_powder");
        parentStairs(MinecraftBlocks.YELLOW_CONCRETE_POWDER_STAIRS, "yellow_concrete_powder");
        parentStairs(MinecraftBlocks.LIME_CONCRETE_POWDER_STAIRS, "lime_concrete_powder");
        parentStairs(MinecraftBlocks.PINK_CONCRETE_POWDER_STAIRS, "pink_concrete_powder");
        parentStairs(MinecraftBlocks.GRAY_CONCRETE_POWDER_STAIRS, "gray_concrete_powder");
        parentStairs(MinecraftBlocks.LIGHT_GRAY_CONCRETE_POWDER_STAIRS, "light_gray_concrete_powder");
        parentStairs(MinecraftBlocks.CYAN_CONCRETE_POWDER_STAIRS, "cyan_concrete_powder");
        parentStairs(MinecraftBlocks.PURPLE_CONCRETE_POWDER_STAIRS, "purple_concrete_powder");
        parentStairs(MinecraftBlocks.BLUE_CONCRETE_POWDER_STAIRS, "blue_concrete_powder");
        parentStairs(MinecraftBlocks.BROWN_CONCRETE_POWDER_STAIRS, "brown_concrete_powder");
        parentStairs(MinecraftBlocks.GREEN_CONCRETE_POWDER_STAIRS, "green_concrete_powder");
        parentStairs(MinecraftBlocks.RED_CONCRETE_POWDER_STAIRS, "red_concrete_powder");
        parentStairs(MinecraftBlocks.BLACK_CONCRETE_POWDER_STAIRS, "black_concrete_powder");
        parentStairs(MinecraftBlocks.WHITE_GLAZED_TERRACOTTA_STAIRS, "white_glazed_terracotta");
        parentStairs(MinecraftBlocks.ORANGE_GLAZED_TERRACOTTA_STAIRS, "orange_glazed_terracotta");
        parentStairs(MinecraftBlocks.MAGENTA_GLAZED_TERRACOTTA_STAIRS, "magenta_glazed_terracotta");
        parentStairs(MinecraftBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_STAIRS, "light_blue_glazed_terracotta");
        parentStairs(MinecraftBlocks.YELLOW_GLAZED_TERRACOTTA_STAIRS, "yellow_glazed_terracotta");
        parentStairs(MinecraftBlocks.LIME_GLAZED_TERRACOTTA_STAIRS, "lime_glazed_terracotta");
        parentStairs(MinecraftBlocks.PINK_GLAZED_TERRACOTTA_STAIRS, "pink_glazed_terracotta");
        parentStairs(MinecraftBlocks.GRAY_GLAZED_TERRACOTTA_STAIRS, "gray_glazed_terracotta");
        parentStairs(MinecraftBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_STAIRS, "light_gray_glazed_terracotta");
        parentStairs(MinecraftBlocks.CYAN_GLAZED_TERRACOTTA_STAIRS, "cyan_glazed_terracotta");
        parentStairs(MinecraftBlocks.PURPLE_GLAZED_TERRACOTTA_STAIRS, "purple_glazed_terracotta");
        parentStairs(MinecraftBlocks.BLUE_GLAZED_TERRACOTTA_STAIRS, "blue_glazed_terracotta");
        parentStairs(MinecraftBlocks.BROWN_GLAZED_TERRACOTTA_STAIRS, "brown_glazed_terracotta");
        parentStairs(MinecraftBlocks.GREEN_GLAZED_TERRACOTTA_STAIRS, "green_glazed_terracotta");
        parentStairs(MinecraftBlocks.RED_GLAZED_TERRACOTTA_STAIRS, "red_glazed_terracotta");
        parentStairs(MinecraftBlocks.BLACK_GLAZED_TERRACOTTA_STAIRS, "black_glazed_terracotta");
        parentStairs(MinecraftBlocks.WHITE_STAINED_GLASS_STAIRS, "white_stained_glass");
        parentStairs(MinecraftBlocks.ORANGE_STAINED_GLASS_STAIRS, "orange_stained_glass");
        parentStairs(MinecraftBlocks.MAGENTA_STAINED_GLASS_STAIRS, "magenta_stained_glass");
        parentStairs(MinecraftBlocks.LIGHT_BLUE_STAINED_GLASS_STAIRS, "light_blue_stained_glass");
        parentStairs(MinecraftBlocks.YELLOW_STAINED_GLASS_STAIRS, "yellow_stained_glass");
        parentStairs(MinecraftBlocks.LIME_STAINED_GLASS_STAIRS, "lime_stained_glass");
        parentStairs(MinecraftBlocks.PINK_STAINED_GLASS_STAIRS, "pink_stained_glass");
        parentStairs(MinecraftBlocks.GRAY_STAINED_GLASS_STAIRS, "gray_stained_glass");
        parentStairs(MinecraftBlocks.LIGHT_GRAY_STAINED_GLASS_STAIRS, "light_gray_stained_glass");
        parentStairs(MinecraftBlocks.CYAN_STAINED_GLASS_STAIRS, "cyan_stained_glass");
        parentStairs(MinecraftBlocks.PURPLE_STAINED_GLASS_STAIRS, "purple_stained_glass");
        parentStairs(MinecraftBlocks.BLUE_STAINED_GLASS_STAIRS, "blue_stained_glass");
        parentStairs(MinecraftBlocks.BROWN_STAINED_GLASS_STAIRS, "brown_stained_glass");
        parentStairs(MinecraftBlocks.GREEN_STAINED_GLASS_STAIRS, "green_stained_glass");
        parentStairs(MinecraftBlocks.RED_STAINED_GLASS_STAIRS, "red_stained_glass");
        parentStairs(MinecraftBlocks.BLACK_STAINED_GLASS_STAIRS, "black_stained_glass");
        parentStairs(MinecraftBlocks.WHITE_TERRACOTTA_STAIRS, "white_terracotta");
        parentStairs(MinecraftBlocks.ORANGE_TERRACOTTA_STAIRS, "orange_terracotta");
        parentStairs(MinecraftBlocks.MAGENTA_TERRACOTTA_STAIRS, "magenta_terracotta");
        parentStairs(MinecraftBlocks.LIGHT_BLUE_TERRACOTTA_STAIRS, "light_blue_terracotta");
        parentStairs(MinecraftBlocks.YELLOW_TERRACOTTA_STAIRS, "yellow_terracotta");
        parentStairs(MinecraftBlocks.LIME_TERRACOTTA_STAIRS, "lime_terracotta");
        parentStairs(MinecraftBlocks.PINK_TERRACOTTA_STAIRS, "pink_terracotta");
        parentStairs(MinecraftBlocks.GRAY_TERRACOTTA_STAIRS, "gray_terracotta");
        parentStairs(MinecraftBlocks.LIGHT_GRAY_TERRACOTTA_STAIRS, "light_gray_terracotta");
        parentStairs(MinecraftBlocks.CYAN_TERRACOTTA_STAIRS, "cyan_terracotta");
        parentStairs(MinecraftBlocks.PURPLE_TERRACOTTA_STAIRS, "purple_terracotta");
        parentStairs(MinecraftBlocks.BLUE_TERRACOTTA_STAIRS, "blue_terracotta");
        parentStairs(MinecraftBlocks.BROWN_TERRACOTTA_STAIRS, "brown_terracotta");
        parentStairs(MinecraftBlocks.GREEN_TERRACOTTA_STAIRS, "green_terracotta");
        parentStairs(MinecraftBlocks.RED_TERRACOTTA_STAIRS, "red_terracotta");
        parentStairs(MinecraftBlocks.BLACK_TERRACOTTA_STAIRS, "black_terracotta");
        parentStairs(MinecraftBlocks.WHITE_WOOL_STAIRS, "white_wool");
        parentStairs(MinecraftBlocks.ORANGE_WOOL_STAIRS, "orange_wool");
        parentStairs(MinecraftBlocks.MAGENTA_WOOL_STAIRS, "magenta_wool");
        parentStairs(MinecraftBlocks.LIGHT_BLUE_WOOL_STAIRS, "light_blue_wool");
        parentStairs(MinecraftBlocks.YELLOW_WOOL_STAIRS, "yellow_wool");
        parentStairs(MinecraftBlocks.LIME_WOOL_STAIRS, "lime_wool");
        parentStairs(MinecraftBlocks.PINK_WOOL_STAIRS, "pink_wool");
        parentStairs(MinecraftBlocks.GRAY_WOOL_STAIRS, "gray_wool");
        parentStairs(MinecraftBlocks.LIGHT_GRAY_WOOL_STAIRS, "light_gray_wool");
        parentStairs(MinecraftBlocks.CYAN_WOOL_STAIRS, "cyan_wool");
        parentStairs(MinecraftBlocks.PURPLE_WOOL_STAIRS, "purple_wool");
        parentStairs(MinecraftBlocks.BLUE_WOOL_STAIRS, "blue_wool");
        parentStairs(MinecraftBlocks.BROWN_WOOL_STAIRS, "brown_wool");
        parentStairs(MinecraftBlocks.GREEN_WOOL_STAIRS, "green_wool");
        parentStairs(MinecraftBlocks.RED_WOOL_STAIRS, "red_wool");
        parentStairs(MinecraftBlocks.BLACK_WOOL_STAIRS, "black_wool");
        parentStairs(MinecraftBlocks.DIRT_STAIRS, "dirt");
        parentStairs(MinecraftBlocks.COARSE_DIRT_STAIRS, "coarse_dirt");
        parentStairs(MinecraftBlocks.PODZOL_STAIRS, "podzol");
        parentStairs(MinecraftBlocks.BEDROCK_STAIRS, "bedrock");
        parentStairs(MinecraftBlocks.SAND_STAIRS, "sand");
        parentStairs(MinecraftBlocks.RED_SAND_STAIRS, "red_sand");
        parentStairs(MinecraftBlocks.GRAVEL_STAIRS, "gravel");
        parentStairs(MinecraftBlocks.GOLD_ORE_STAIRS, "gold_ore");
        parentStairs(MinecraftBlocks.IRON_ORE_STAIRS, "iron_ore");
        parentStairs(MinecraftBlocks.COAL_ORE_STAIRS, "coal_ore");
        parentStairs(MinecraftBlocks.SPONGE_STAIRS, "sponge");
        parentStairs(MinecraftBlocks.WET_SPONGE_STAIRS, "wet_sponge");
        parentStairs(MinecraftBlocks.GLASS_STAIRS, "glass");
        parentStairs(MinecraftBlocks.LAPIS_ORE_STAIRS, "lapis_ore");
        parentStairs(MinecraftBlocks.LAPIS_BLOCK_STAIRS, "lapis_block");
        parentStairs(MinecraftBlocks.CHISELED_SANDSTONE_STAIRS, "chiseled_sandstone");
        parentStairs(MinecraftBlocks.GOLD_BLOCK_STAIRS, "gold_block");
        parentStairs(MinecraftBlocks.IRON_BLOCK_STAIRS, "iron_block");
        parentStairs(MinecraftBlocks.BOOKSHELF_STAIRS, "bookshelf");
        parentStairs(MinecraftBlocks.OBSIDIAN_STAIRS, "obsidian");
        parentStairs(MinecraftBlocks.PURPUR_PILLAR_STAIRS, "purpur_pillar");
        parentStairs(MinecraftBlocks.DIAMOND_ORE_STAIRS, "diamond_ore");
        parentStairs(MinecraftBlocks.DIAMOND_BLOCK_STAIRS, "diamond_block");
        parentStairs(MinecraftBlocks.REDSTONE_ORE_STAIRS, "redstone_ore");
        parentStairs(MinecraftBlocks.ICE_STAIRS, "ice");
        parentStairs(MinecraftBlocks.SNOW_STAIRS, "snow");
        parentStairs(MinecraftBlocks.CLAY_STAIRS, "clay");
        parentStairs(MinecraftBlocks.PUMPKIN_STAIRS, "pumpkin");
        parentStairs(MinecraftBlocks.NETHERRACK_STAIRS, "netherrack");
        parentStairs(MinecraftBlocks.SOUL_SAND_STAIRS, "soul_sand");
        parentStairs(MinecraftBlocks.GLOWSTONE_STAIRS, "glowstone");
        parentStairs(MinecraftBlocks.CRACKED_STONE_BRICK_STAIRS, "cracked_stone_brick");
        parentStairs(MinecraftBlocks.CHISELED_STONE_BRICK_STAIRS, "chiseled_stone_brick");
        parentStairs(MinecraftBlocks.BROWN_MUSHROOM_STAIRS, "brown_mushroom");
        parentStairs(MinecraftBlocks.RED_MUSHROOM_STAIRS, "red_mushroom");
        parentStairs(MinecraftBlocks.MUSHROOM_STEM_STAIRS, "mushroom_stem");
        parentStairs(MinecraftBlocks.MELON_STAIRS, "melon");
        parentStairs(MinecraftBlocks.MYCELIUM_STAIRS, "mycelium");
        parentStairs(MinecraftBlocks.END_STONE_STAIRS, "end_stone");
        parentStairs(MinecraftBlocks.EMERALD_ORE_STAIRS, "emerald_ore");
        parentStairs(MinecraftBlocks.EMERALD_BLOCK_STAIRS, "emerald_block");
        parentStairs(MinecraftBlocks.REDSTONE_BLOCK_STAIRS, "redstone_block");
        parentStairs(MinecraftBlocks.NETHER_QUARTZ_ORE_STAIRS, "nether_quartz_ore");
        parentStairs(MinecraftBlocks.CHISELED_QUARTZ_STAIRS, "chiseled_quartz");
        parentStairs(MinecraftBlocks.QUARTZ_PILLAR_STAIRS, "quartz_pillar");
        parentStairs(MinecraftBlocks.HAY_STAIRS, "hay");
        parentStairs(MinecraftBlocks.TERRACOTTA_STAIRS, "terracotta");
        parentStairs(MinecraftBlocks.COAL_STAIRS, "coal");
        parentStairs(MinecraftBlocks.PACKED_ICE_STAIRS, "packed_ice");
        parentStairs(MinecraftBlocks.SLIME_STAIRS, "slime");
        parentStairs(MinecraftBlocks.SEA_LANTERN_STAIRS, "sea_lantern");
        parentStairs(MinecraftBlocks.CHISELED_RED_SANDSTONE_STAIRS, "chiseled_red_sandstone");
        parentStairs(MinecraftBlocks.MAGMA_STAIRS, "magma");
        parentStairs(MinecraftBlocks.NETHER_WART_STAIRS, "nether_wart");
        parentStairs(MinecraftBlocks.BONE_STAIRS, "bone");
        parentStairs(MinecraftBlocks.DEAD_TUBE_CORAL_STAIRS, "dead_tube_coral");
        parentStairs(MinecraftBlocks.DEAD_BRAIN_CORAL_STAIRS, "dead_brain_coral");
        parentStairs(MinecraftBlocks.DEAD_BUBBLE_CORAL_STAIRS, "dead_bubble_coral");
        parentStairs(MinecraftBlocks.DEAD_FIRE_CORAL_STAIRS, "dead_fire_coral");
        parentStairs(MinecraftBlocks.DEAD_HORN_CORAL_STAIRS, "dead_horn_coral");
        parentStairs(MinecraftBlocks.TUBE_CORAL_STAIRS, "tube_coral");
        parentStairs(MinecraftBlocks.BRAIN_CORAL_STAIRS, "brain_coral");
        parentStairs(MinecraftBlocks.BUBBLE_CORAL_STAIRS, "bubble_coral");
        parentStairs(MinecraftBlocks.FIRE_CORAL_STAIRS, "fire_coral");
        parentStairs(MinecraftBlocks.HORN_CORAL_STAIRS, "horn_coral");
        parentStairs(MinecraftBlocks.DRIED_KELP_STAIRS, "dried_kelp");
        parentStairs(MinecraftBlocks.HONEY_STAIRS, "honey");
        parentStairs(MinecraftBlocks.HONEYCOMB_STAIRS, "honeycomb");
        parentWall(MinecraftBlocks.OAK_WALL, "oak");
        parentWall(MinecraftBlocks.SPRUCE_WALL, "spruce");
        parentWall(MinecraftBlocks.BIRCH_WALL, "birch");
        parentWall(MinecraftBlocks.JUNGLE_WALL, "jungle");
        parentWall(MinecraftBlocks.ACACIA_WALL, "acacia");
        parentWall(MinecraftBlocks.DARK_OAK_WALL, "dark_oak");
        parentWall(MinecraftBlocks.STRIPPED_OAK_WALL, "stripped_oak");
        parentWall(MinecraftBlocks.STRIPPED_SPRUCE_WALL, "stripped_spruce");
        parentWall(MinecraftBlocks.STRIPPED_BIRCH_WALL, "stripped_birch");
        parentWall(MinecraftBlocks.STRIPPED_JUNGLE_WALL, "stripped_jungle");
        parentWall(MinecraftBlocks.STRIPPED_ACACIA_WALL, "stripped_acacia");
        parentWall(MinecraftBlocks.STRIPPED_DARK_OAK_WALL, "stripped_dark_oak");
        parentWall(MinecraftBlocks.WHITE_CONCRETE_WALL, "white_concrete");
        parentWall(MinecraftBlocks.ORANGE_CONCRETE_WALL, "orange_concrete");
        parentWall(MinecraftBlocks.MAGENTA_CONCRETE_WALL, "magenta_concrete");
        parentWall(MinecraftBlocks.LIGHT_BLUE_CONCRETE_WALL, "light_blue_concrete");
        parentWall(MinecraftBlocks.YELLOW_CONCRETE_WALL, "yellow_concrete");
        parentWall(MinecraftBlocks.LIME_CONCRETE_WALL, "lime_concrete");
        parentWall(MinecraftBlocks.PINK_CONCRETE_WALL, "pink_concrete");
        parentWall(MinecraftBlocks.GRAY_CONCRETE_WALL, "gray_concrete");
        parentWall(MinecraftBlocks.LIGHT_GRAY_CONCRETE_WALL, "light_gray_concrete");
        parentWall(MinecraftBlocks.CYAN_CONCRETE_WALL, "cyan_concrete");
        parentWall(MinecraftBlocks.PURPLE_CONCRETE_WALL, "purple_concrete");
        parentWall(MinecraftBlocks.BLUE_CONCRETE_WALL, "blue_concrete");
        parentWall(MinecraftBlocks.BROWN_CONCRETE_WALL, "brown_concrete");
        parentWall(MinecraftBlocks.GREEN_CONCRETE_WALL, "green_concrete");
        parentWall(MinecraftBlocks.RED_CONCRETE_WALL, "red_concrete");
        parentWall(MinecraftBlocks.BLACK_CONCRETE_WALL, "black_concrete");
        parentWall(MinecraftBlocks.WHITE_CONCRETE_POWDER_WALL, "white_concrete_powder");
        parentWall(MinecraftBlocks.ORANGE_CONCRETE_POWDER_WALL, "orange_concrete_powder");
        parentWall(MinecraftBlocks.MAGENTA_CONCRETE_POWDER_WALL, "magenta_concrete_powder");
        parentWall(MinecraftBlocks.LIGHT_BLUE_CONCRETE_POWDER_WALL, "light_blue_concrete_powder");
        parentWall(MinecraftBlocks.YELLOW_CONCRETE_POWDER_WALL, "yellow_concrete_powder");
        parentWall(MinecraftBlocks.LIME_CONCRETE_POWDER_WALL, "lime_concrete_powder");
        parentWall(MinecraftBlocks.PINK_CONCRETE_POWDER_WALL, "pink_concrete_powder");
        parentWall(MinecraftBlocks.GRAY_CONCRETE_POWDER_WALL, "gray_concrete_powder");
        parentWall(MinecraftBlocks.LIGHT_GRAY_CONCRETE_POWDER_WALL, "light_gray_concrete_powder");
        parentWall(MinecraftBlocks.CYAN_CONCRETE_POWDER_WALL, "cyan_concrete_powder");
        parentWall(MinecraftBlocks.PURPLE_CONCRETE_POWDER_WALL, "purple_concrete_powder");
        parentWall(MinecraftBlocks.BLUE_CONCRETE_POWDER_WALL, "blue_concrete_powder");
        parentWall(MinecraftBlocks.BROWN_CONCRETE_POWDER_WALL, "brown_concrete_powder");
        parentWall(MinecraftBlocks.GREEN_CONCRETE_POWDER_WALL, "green_concrete_powder");
        parentWall(MinecraftBlocks.RED_CONCRETE_POWDER_WALL, "red_concrete_powder");
        parentWall(MinecraftBlocks.BLACK_CONCRETE_POWDER_WALL, "black_concrete_powder");
        parentWall(MinecraftBlocks.WHITE_GLAZED_TERRACOTTA_WALL, "white_glazed_terracotta");
        parentWall(MinecraftBlocks.ORANGE_GLAZED_TERRACOTTA_WALL, "orange_glazed_terracotta");
        parentWall(MinecraftBlocks.MAGENTA_GLAZED_TERRACOTTA_WALL, "magenta_glazed_terracotta");
        parentWall(MinecraftBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_WALL, "light_blue_glazed_terracotta");
        parentWall(MinecraftBlocks.YELLOW_GLAZED_TERRACOTTA_WALL, "yellow_glazed_terracotta");
        parentWall(MinecraftBlocks.LIME_GLAZED_TERRACOTTA_WALL, "lime_glazed_terracotta");
        parentWall(MinecraftBlocks.PINK_GLAZED_TERRACOTTA_WALL, "pink_glazed_terracotta");
        parentWall(MinecraftBlocks.GRAY_GLAZED_TERRACOTTA_WALL, "gray_glazed_terracotta");
        parentWall(MinecraftBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_WALL, "light_gray_glazed_terracotta");
        parentWall(MinecraftBlocks.CYAN_GLAZED_TERRACOTTA_WALL, "cyan_glazed_terracotta");
        parentWall(MinecraftBlocks.PURPLE_GLAZED_TERRACOTTA_WALL, "purple_glazed_terracotta");
        parentWall(MinecraftBlocks.BLUE_GLAZED_TERRACOTTA_WALL, "blue_glazed_terracotta");
        parentWall(MinecraftBlocks.BROWN_GLAZED_TERRACOTTA_WALL, "brown_glazed_terracotta");
        parentWall(MinecraftBlocks.GREEN_GLAZED_TERRACOTTA_WALL, "green_glazed_terracotta");
        parentWall(MinecraftBlocks.RED_GLAZED_TERRACOTTA_WALL, "red_glazed_terracotta");
        parentWall(MinecraftBlocks.BLACK_GLAZED_TERRACOTTA_WALL, "black_glazed_terracotta");
        parentWall(MinecraftBlocks.WHITE_STAINED_GLASS_WALL, "white_stained_glass");
        parentWall(MinecraftBlocks.ORANGE_STAINED_GLASS_WALL, "orange_stained_glass");
        parentWall(MinecraftBlocks.MAGENTA_STAINED_GLASS_WALL, "magenta_stained_glass");
        parentWall(MinecraftBlocks.LIGHT_BLUE_STAINED_GLASS_WALL, "light_blue_stained_glass");
        parentWall(MinecraftBlocks.YELLOW_STAINED_GLASS_WALL, "yellow_stained_glass");
        parentWall(MinecraftBlocks.LIME_STAINED_GLASS_WALL, "lime_stained_glass");
        parentWall(MinecraftBlocks.PINK_STAINED_GLASS_WALL, "pink_stained_glass");
        parentWall(MinecraftBlocks.GRAY_STAINED_GLASS_WALL, "gray_stained_glass");
        parentWall(MinecraftBlocks.LIGHT_GRAY_STAINED_GLASS_WALL, "light_gray_stained_glass");
        parentWall(MinecraftBlocks.CYAN_STAINED_GLASS_WALL, "cyan_stained_glass");
        parentWall(MinecraftBlocks.PURPLE_STAINED_GLASS_WALL, "purple_stained_glass");
        parentWall(MinecraftBlocks.BLUE_STAINED_GLASS_WALL, "blue_stained_glass");
        parentWall(MinecraftBlocks.BROWN_STAINED_GLASS_WALL, "brown_stained_glass");
        parentWall(MinecraftBlocks.GREEN_STAINED_GLASS_WALL, "green_stained_glass");
        parentWall(MinecraftBlocks.RED_STAINED_GLASS_WALL, "red_stained_glass");
        parentWall(MinecraftBlocks.BLACK_STAINED_GLASS_WALL, "black_stained_glass");
        parentWall(MinecraftBlocks.WHITE_TERRACOTTA_WALL, "white_terracotta");
        parentWall(MinecraftBlocks.ORANGE_TERRACOTTA_WALL, "orange_terracotta");
        parentWall(MinecraftBlocks.MAGENTA_TERRACOTTA_WALL, "magenta_terracotta");
        parentWall(MinecraftBlocks.LIGHT_BLUE_TERRACOTTA_WALL, "light_blue_terracotta");
        parentWall(MinecraftBlocks.YELLOW_TERRACOTTA_WALL, "yellow_terracotta");
        parentWall(MinecraftBlocks.LIME_TERRACOTTA_WALL, "lime_terracotta");
        parentWall(MinecraftBlocks.PINK_TERRACOTTA_WALL, "pink_terracotta");
        parentWall(MinecraftBlocks.GRAY_TERRACOTTA_WALL, "gray_terracotta");
        parentWall(MinecraftBlocks.LIGHT_GRAY_TERRACOTTA_WALL, "light_gray_terracotta");
        parentWall(MinecraftBlocks.CYAN_TERRACOTTA_WALL, "cyan_terracotta");
        parentWall(MinecraftBlocks.PURPLE_TERRACOTTA_WALL, "purple_terracotta");
        parentWall(MinecraftBlocks.BLUE_TERRACOTTA_WALL, "blue_terracotta");
        parentWall(MinecraftBlocks.BROWN_TERRACOTTA_WALL, "brown_terracotta");
        parentWall(MinecraftBlocks.GREEN_TERRACOTTA_WALL, "green_terracotta");
        parentWall(MinecraftBlocks.RED_TERRACOTTA_WALL, "red_terracotta");
        parentWall(MinecraftBlocks.BLACK_TERRACOTTA_WALL, "black_terracotta");
        parentWall(MinecraftBlocks.WHITE_WOOL_WALL, "white_wool");
        parentWall(MinecraftBlocks.ORANGE_WOOL_WALL, "orange_wool");
        parentWall(MinecraftBlocks.MAGENTA_WOOL_WALL, "magenta_wool");
        parentWall(MinecraftBlocks.LIGHT_BLUE_WOOL_WALL, "light_blue_wool");
        parentWall(MinecraftBlocks.YELLOW_WOOL_WALL, "yellow_wool");
        parentWall(MinecraftBlocks.LIME_WOOL_WALL, "lime_wool");
        parentWall(MinecraftBlocks.PINK_WOOL_WALL, "pink_wool");
        parentWall(MinecraftBlocks.GRAY_WOOL_WALL, "gray_wool");
        parentWall(MinecraftBlocks.LIGHT_GRAY_WOOL_WALL, "light_gray_wool");
        parentWall(MinecraftBlocks.CYAN_WOOL_WALL, "cyan_wool");
        parentWall(MinecraftBlocks.PURPLE_WOOL_WALL, "purple_wool");
        parentWall(MinecraftBlocks.BLUE_WOOL_WALL, "blue_wool");
        parentWall(MinecraftBlocks.BROWN_WOOL_WALL, "brown_wool");
        parentWall(MinecraftBlocks.GREEN_WOOL_WALL, "green_wool");
        parentWall(MinecraftBlocks.RED_WOOL_WALL, "red_wool");
        parentWall(MinecraftBlocks.BLACK_WOOL_WALL, "black_wool");
        parentWall(MinecraftBlocks.DIRT_WALL, "dirt");
        parentWall(MinecraftBlocks.COARSE_DIRT_WALL, "coarse_dirt");
        parentWall(MinecraftBlocks.PODZOL_WALL, "podzol");
        parentWall(MinecraftBlocks.BEDROCK_WALL, "bedrock");
        parentWall(MinecraftBlocks.SAND_WALL, "sand");
        parentWall(MinecraftBlocks.RED_SAND_WALL, "red_sand");
        parentWall(MinecraftBlocks.GRAVEL_WALL, "gravel");
        parentWall(MinecraftBlocks.GOLD_ORE_WALL, "gold_ore");
        parentWall(MinecraftBlocks.IRON_ORE_WALL, "iron_ore");
        parentWall(MinecraftBlocks.COAL_ORE_WALL, "coal_ore");
        parentWall(MinecraftBlocks.SPONGE_WALL, "sponge");
        parentWall(MinecraftBlocks.WET_SPONGE_WALL, "wet_sponge");
        parentWall(MinecraftBlocks.GLASS_WALL, "glass");
        parentWall(MinecraftBlocks.LAPIS_ORE_WALL, "lapis_ore");
        parentWall(MinecraftBlocks.LAPIS_BLOCK_WALL, "lapis_block");
        parentWall(MinecraftBlocks.CHISELED_SANDSTONE_WALL, "chiseled_sandstone");
        parentWall(MinecraftBlocks.GOLD_BLOCK_WALL, "gold_block");
        parentWall(MinecraftBlocks.IRON_BLOCK_WALL, "iron_block");
        parentWall(MinecraftBlocks.BOOKSHELF_WALL, "bookshelf");
        parentWall(MinecraftBlocks.OBSIDIAN_WALL, "obsidian");
        parentWall(MinecraftBlocks.PURPUR_PILLAR_WALL, "purpur_pillar");
        parentWall(MinecraftBlocks.DIAMOND_ORE_WALL, "diamond_ore");
        parentWall(MinecraftBlocks.DIAMOND_BLOCK_WALL, "diamond_block");
        parentWall(MinecraftBlocks.REDSTONE_ORE_WALL, "redstone_ore");
        parentWall(MinecraftBlocks.ICE_WALL, "ice");
        parentWall(MinecraftBlocks.SNOW_WALL, "snow");
        parentWall(MinecraftBlocks.CLAY_WALL, "clay");
        parentWall(MinecraftBlocks.PUMPKIN_WALL, "pumpkin");
        parentWall(MinecraftBlocks.NETHERRACK_WALL, "netherrack");
        parentWall(MinecraftBlocks.SOUL_SAND_WALL, "soul_sand");
        parentWall(MinecraftBlocks.GLOWSTONE_WALL, "glowstone");
        parentWall(MinecraftBlocks.CRACKED_STONE_BRICK_WALL, "cracked_stone_brick");
        parentWall(MinecraftBlocks.CHISELED_STONE_BRICK_WALL, "chiseled_stone_brick");
        parentWall(MinecraftBlocks.BROWN_MUSHROOM_WALL, "brown_mushroom");
        parentWall(MinecraftBlocks.RED_MUSHROOM_WALL, "red_mushroom");
        parentWall(MinecraftBlocks.MUSHROOM_STEM_WALL, "mushroom_stem");
        parentWall(MinecraftBlocks.MELON_WALL, "melon");
        parentWall(MinecraftBlocks.MYCELIUM_WALL, "mycelium");
        parentWall(MinecraftBlocks.END_STONE_WALL, "end_stone");
        parentWall(MinecraftBlocks.EMERALD_ORE_WALL, "emerald_ore");
        parentWall(MinecraftBlocks.EMERALD_BLOCK_WALL, "emerald_block");
        parentWall(MinecraftBlocks.REDSTONE_BLOCK_WALL, "redstone_block");
        parentWall(MinecraftBlocks.NETHER_QUARTZ_ORE_WALL, "nether_quartz_ore");
        parentWall(MinecraftBlocks.CHISELED_QUARTZ_WALL, "chiseled_quartz");
        parentWall(MinecraftBlocks.QUARTZ_PILLAR_WALL, "quartz_pillar");
        parentWall(MinecraftBlocks.HAY_WALL, "hay");
        parentWall(MinecraftBlocks.TERRACOTTA_WALL, "terracotta");
        parentWall(MinecraftBlocks.COAL_WALL, "coal");
        parentWall(MinecraftBlocks.PACKED_ICE_WALL, "packed_ice");
        parentWall(MinecraftBlocks.SLIME_WALL, "slime");
        parentWall(MinecraftBlocks.SEA_LANTERN_WALL, "sea_lantern");
        parentWall(MinecraftBlocks.CHISELED_RED_SANDSTONE_WALL, "chiseled_red_sandstone");
        parentWall(MinecraftBlocks.MAGMA_WALL, "magma");
        parentWall(MinecraftBlocks.NETHER_WART_WALL, "nether_wart");
        parentWall(MinecraftBlocks.BONE_WALL, "bone");
        parentWall(MinecraftBlocks.DEAD_TUBE_CORAL_WALL, "dead_tube_coral");
        parentWall(MinecraftBlocks.DEAD_BRAIN_CORAL_WALL, "dead_brain_coral");
        parentWall(MinecraftBlocks.DEAD_BUBBLE_CORAL_WALL, "dead_bubble_coral");
        parentWall(MinecraftBlocks.DEAD_FIRE_CORAL_WALL, "dead_fire_coral");
        parentWall(MinecraftBlocks.DEAD_HORN_CORAL_WALL, "dead_horn_coral");
        parentWall(MinecraftBlocks.TUBE_CORAL_WALL, "tube_coral");
        parentWall(MinecraftBlocks.BRAIN_CORAL_WALL, "brain_coral");
        parentWall(MinecraftBlocks.BUBBLE_CORAL_WALL, "bubble_coral");
        parentWall(MinecraftBlocks.FIRE_CORAL_WALL, "fire_coral");
        parentWall(MinecraftBlocks.HORN_CORAL_WALL, "horn_coral");
        parentWall(MinecraftBlocks.DRIED_KELP_WALL, "dried_kelp");
        parentWall(MinecraftBlocks.HONEY_WALL, "honey");
        parentWall(MinecraftBlocks.HONEYCOMB_WALL, "honeycomb");
//        parentVertSlab(MinecraftBlocks.OAK_PLANK_VERTICAL_SLAB, "oak_plank");
//        parentVertSlab(MinecraftBlocks.SPRUCE_PLANK_VERTICAL_SLAB, "spruce_plank");
//        parentVertSlab(MinecraftBlocks.BIRCH_PLANK_VERTICAL_SLAB, "birch_plank");
//        parentVertSlab(MinecraftBlocks.JUNGLE_PLANK_VERTICAL_SLAB, "jungle_plank");
//        parentVertSlab(MinecraftBlocks.ACACIA_PLANK_VERTICAL_SLAB, "acacia_plank");
//        parentVertSlab(MinecraftBlocks.DARK_OAK_PLANK_VERTICAL_SLAB, "dark_oak_plank");
//        parentVertSlab(MinecraftBlocks.OAK_VERTICAL_SLAB, "oak");
//        parentVertSlab(MinecraftBlocks.SPRUCE_VERTICAL_SLAB, "spruce");
//        parentVertSlab(MinecraftBlocks.BIRCH_VERTICAL_SLAB, "birch");
//        parentVertSlab(MinecraftBlocks.JUNGLE_VERTICAL_SLAB, "jungle");
//        parentVertSlab(MinecraftBlocks.ACACIA_VERTICAL_SLAB, "acacia");
//        parentVertSlab(MinecraftBlocks.DARK_OAK_VERTICAL_SLAB, "dark_oak");
//        parentVertSlab(MinecraftBlocks.STRIPPED_OAK_VERTICAL_SLAB, "stripped_oak");
//        parentVertSlab(MinecraftBlocks.STRIPPED_SPRUCE_VERTICAL_SLAB, "stripped_spruce");
//        parentVertSlab(MinecraftBlocks.STRIPPED_BIRCH_VERTICAL_SLAB, "stripped_birch");
//        parentVertSlab(MinecraftBlocks.STRIPPED_JUNGLE_VERTICAL_SLAB, "stripped_jungle");
//        parentVertSlab(MinecraftBlocks.STRIPPED_ACACIA_VERTICAL_SLAB, "stripped_acacia");
//        parentVertSlab(MinecraftBlocks.STRIPPED_DARK_OAK_VERTICAL_SLAB, "stripped_dark_oak");
//        parentVertSlab(MinecraftBlocks.WHITE_CONCRETE_VERTICAL_SLAB, "white_concrete");
//        parentVertSlab(MinecraftBlocks.ORANGE_CONCRETE_VERTICAL_SLAB, "orange_concrete");
//        parentVertSlab(MinecraftBlocks.MAGENTA_CONCRETE_VERTICAL_SLAB, "magenta_concrete");
//        parentVertSlab(MinecraftBlocks.LIGHT_BLUE_CONCRETE_VERTICAL_SLAB, "light_blue_concrete");
//        parentVertSlab(MinecraftBlocks.YELLOW_CONCRETE_VERTICAL_SLAB, "yellow_concrete");
//        parentVertSlab(MinecraftBlocks.LIME_CONCRETE_VERTICAL_SLAB, "lime_concrete");
//        parentVertSlab(MinecraftBlocks.PINK_CONCRETE_VERTICAL_SLAB, "pink_concrete");
//        parentVertSlab(MinecraftBlocks.GRAY_CONCRETE_VERTICAL_SLAB, "gray_concrete");
//        parentVertSlab(MinecraftBlocks.LIGHT_GRAY_CONCRETE_VERTICAL_SLAB, "light_gray_concrete");
//        parentVertSlab(MinecraftBlocks.CYAN_CONCRETE_VERTICAL_SLAB, "cyan_concrete");
//        parentVertSlab(MinecraftBlocks.PURPLE_CONCRETE_VERTICAL_SLAB, "purple_concrete");
//        parentVertSlab(MinecraftBlocks.BLUE_CONCRETE_VERTICAL_SLAB, "blue_concrete");
//        parentVertSlab(MinecraftBlocks.BROWN_CONCRETE_VERTICAL_SLAB, "brown_concrete");
//        parentVertSlab(MinecraftBlocks.GREEN_CONCRETE_VERTICAL_SLAB, "green_concrete");
//        parentVertSlab(MinecraftBlocks.RED_CONCRETE_VERTICAL_SLAB, "red_concrete");
//        parentVertSlab(MinecraftBlocks.BLACK_CONCRETE_VERTICAL_SLAB, "black_concrete");
//        parentVertSlab(MinecraftBlocks.WHITE_CONCRETE_POWDER_VERTICAL_SLAB, "white_concrete_powder");
//        parentVertSlab(MinecraftBlocks.ORANGE_CONCRETE_POWDER_VERTICAL_SLAB, "orange_concrete_powder");
//        parentVertSlab(MinecraftBlocks.MAGENTA_CONCRETE_POWDER_VERTICAL_SLAB, "magenta_concrete_powder");
//        parentVertSlab(MinecraftBlocks.LIGHT_BLUE_CONCRETE_POWDER_VERTICAL_SLAB, "light_blue_concrete_powder");
//        parentVertSlab(MinecraftBlocks.YELLOW_CONCRETE_POWDER_VERTICAL_SLAB, "yellow_concrete_powder");
//        parentVertSlab(MinecraftBlocks.LIME_CONCRETE_POWDER_VERTICAL_SLAB, "lime_concrete_powder");
//        parentVertSlab(MinecraftBlocks.PINK_CONCRETE_POWDER_VERTICAL_SLAB, "pink_concrete_powder");
//        parentVertSlab(MinecraftBlocks.GRAY_CONCRETE_POWDER_VERTICAL_SLAB, "gray_concrete_powder");
//        parentVertSlab(MinecraftBlocks.LIGHT_GRAY_CONCRETE_POWDER_VERTICAL_SLAB, "light_gray_concrete_powder");
//        parentVertSlab(MinecraftBlocks.CYAN_CONCRETE_POWDER_VERTICAL_SLAB, "cyan_concrete_powder");
//        parentVertSlab(MinecraftBlocks.PURPLE_CONCRETE_POWDER_VERTICAL_SLAB, "purple_concrete_powder");
//        parentVertSlab(MinecraftBlocks.BLUE_CONCRETE_POWDER_VERTICAL_SLAB, "blue_concrete_powder");
//        parentVertSlab(MinecraftBlocks.BROWN_CONCRETE_POWDER_VERTICAL_SLAB, "brown_concrete_powder");
//        parentVertSlab(MinecraftBlocks.GREEN_CONCRETE_POWDER_VERTICAL_SLAB, "green_concrete_powder");
//        parentVertSlab(MinecraftBlocks.RED_CONCRETE_POWDER_VERTICAL_SLAB, "red_concrete_powder");
//        parentVertSlab(MinecraftBlocks.BLACK_CONCRETE_POWDER_VERTICAL_SLAB, "black_concrete_powder");
//        parentVertSlab(MinecraftBlocks.WHITE_GLAZED_TERRACOTTA_VERTICAL_SLAB, "white_glazed_terracotta");
//        parentVertSlab(MinecraftBlocks.ORANGE_GLAZED_TERRACOTTA_VERTICAL_SLAB, "orange_glazed_terracotta");
//        parentVertSlab(MinecraftBlocks.MAGENTA_GLAZED_TERRACOTTA_VERTICAL_SLAB, "magenta_glazed_terracotta");
//        parentVertSlab(MinecraftBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_VERTICAL_SLAB, "light_blue_glazed_terracotta");
//        parentVertSlab(MinecraftBlocks.YELLOW_GLAZED_TERRACOTTA_VERTICAL_SLAB, "yellow_glazed_terracotta");
//        parentVertSlab(MinecraftBlocks.LIME_GLAZED_TERRACOTTA_VERTICAL_SLAB, "lime_glazed_terracotta");
//        parentVertSlab(MinecraftBlocks.PINK_GLAZED_TERRACOTTA_VERTICAL_SLAB, "pink_glazed_terracotta");
//        parentVertSlab(MinecraftBlocks.GRAY_GLAZED_TERRACOTTA_VERTICAL_SLAB, "gray_glazed_terracotta");
//        parentVertSlab(MinecraftBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_VERTICAL_SLAB, "light_gray_glazed_terracotta");
//        parentVertSlab(MinecraftBlocks.CYAN_GLAZED_TERRACOTTA_VERTICAL_SLAB, "cyan_glazed_terracotta");
//        parentVertSlab(MinecraftBlocks.PURPLE_GLAZED_TERRACOTTA_VERTICAL_SLAB, "purple_glazed_terracotta");
//        parentVertSlab(MinecraftBlocks.BLUE_GLAZED_TERRACOTTA_VERTICAL_SLAB, "blue_glazed_terracotta");
//        parentVertSlab(MinecraftBlocks.BROWN_GLAZED_TERRACOTTA_VERTICAL_SLAB, "brown_glazed_terracotta");
//        parentVertSlab(MinecraftBlocks.GREEN_GLAZED_TERRACOTTA_VERTICAL_SLAB, "green_glazed_terracotta");
//        parentVertSlab(MinecraftBlocks.RED_GLAZED_TERRACOTTA_VERTICAL_SLAB, "red_glazed_terracotta");
//        parentVertSlab(MinecraftBlocks.BLACK_GLAZED_TERRACOTTA_VERTICAL_SLAB, "black_glazed_terracotta");
//        parentVertSlab(MinecraftBlocks.WHITE_STAINED_GLASS_VERTICAL_SLAB, "white_stained_glass");
//        parentVertSlab(MinecraftBlocks.ORANGE_STAINED_GLASS_VERTICAL_SLAB, "orange_stained_glass");
//        parentVertSlab(MinecraftBlocks.MAGENTA_STAINED_GLASS_VERTICAL_SLAB, "magenta_stained_glass");
//        parentVertSlab(MinecraftBlocks.LIGHT_BLUE_STAINED_GLASS_VERTICAL_SLAB, "light_blue_stained_glass");
//        parentVertSlab(MinecraftBlocks.YELLOW_STAINED_GLASS_VERTICAL_SLAB, "yellow_stained_glass");
//        parentVertSlab(MinecraftBlocks.LIME_STAINED_GLASS_VERTICAL_SLAB, "lime_stained_glass");
//        parentVertSlab(MinecraftBlocks.PINK_STAINED_GLASS_VERTICAL_SLAB, "pink_stained_glass");
//        parentVertSlab(MinecraftBlocks.GRAY_STAINED_GLASS_VERTICAL_SLAB, "gray_stained_glass");
//        parentVertSlab(MinecraftBlocks.LIGHT_GRAY_STAINED_GLASS_VERTICAL_SLAB, "light_gray_stained_glass");
//        parentVertSlab(MinecraftBlocks.CYAN_STAINED_GLASS_VERTICAL_SLAB, "cyan_stained_glass");
//        parentVertSlab(MinecraftBlocks.PURPLE_STAINED_GLASS_VERTICAL_SLAB, "purple_stained_glass");
//        parentVertSlab(MinecraftBlocks.BLUE_STAINED_GLASS_VERTICAL_SLAB, "blue_stained_glass");
//        parentVertSlab(MinecraftBlocks.BROWN_STAINED_GLASS_VERTICAL_SLAB, "brown_stained_glass");
//        parentVertSlab(MinecraftBlocks.GREEN_STAINED_GLASS_VERTICAL_SLAB, "green_stained_glass");
//        parentVertSlab(MinecraftBlocks.RED_STAINED_GLASS_VERTICAL_SLAB, "red_stained_glass");
//        parentVertSlab(MinecraftBlocks.BLACK_STAINED_GLASS_VERTICAL_SLAB, "black_stained_glass");
//        parentVertSlab(MinecraftBlocks.WHITE_TERRACOTTA_VERTICAL_SLAB, "white_terracotta");
//        parentVertSlab(MinecraftBlocks.ORANGE_TERRACOTTA_VERTICAL_SLAB, "orange_terracotta");
//        parentVertSlab(MinecraftBlocks.MAGENTA_TERRACOTTA_VERTICAL_SLAB, "magenta_terracotta");
//        parentVertSlab(MinecraftBlocks.LIGHT_BLUE_TERRACOTTA_VERTICAL_SLAB, "light_blue_terracotta");
//        parentVertSlab(MinecraftBlocks.YELLOW_TERRACOTTA_VERTICAL_SLAB, "yellow_terracotta");
//        parentVertSlab(MinecraftBlocks.LIME_TERRACOTTA_VERTICAL_SLAB, "lime_terracotta");
//        parentVertSlab(MinecraftBlocks.PINK_TERRACOTTA_VERTICAL_SLAB, "pink_terracotta");
//        parentVertSlab(MinecraftBlocks.GRAY_TERRACOTTA_VERTICAL_SLAB, "gray_terracotta");
//        parentVertSlab(MinecraftBlocks.LIGHT_GRAY_TERRACOTTA_VERTICAL_SLAB, "light_gray_terracotta");
//        parentVertSlab(MinecraftBlocks.CYAN_TERRACOTTA_VERTICAL_SLAB, "cyan_terracotta");
//        parentVertSlab(MinecraftBlocks.PURPLE_TERRACOTTA_VERTICAL_SLAB, "purple_terracotta");
//        parentVertSlab(MinecraftBlocks.BLUE_TERRACOTTA_VERTICAL_SLAB, "blue_terracotta");
//        parentVertSlab(MinecraftBlocks.BROWN_TERRACOTTA_VERTICAL_SLAB, "brown_terracotta");
//        parentVertSlab(MinecraftBlocks.GREEN_TERRACOTTA_VERTICAL_SLAB, "green_terracotta");
//        parentVertSlab(MinecraftBlocks.RED_TERRACOTTA_VERTICAL_SLAB, "red_terracotta");
//        parentVertSlab(MinecraftBlocks.BLACK_TERRACOTTA_VERTICAL_SLAB, "black_terracotta");
//        parentVertSlab(MinecraftBlocks.WHITE_WOOL_VERTICAL_SLAB, "white_wool");
//        parentVertSlab(MinecraftBlocks.ORANGE_WOOL_VERTICAL_SLAB, "orange_wool");
//        parentVertSlab(MinecraftBlocks.MAGENTA_WOOL_VERTICAL_SLAB, "magenta_wool");
//        parentVertSlab(MinecraftBlocks.LIGHT_BLUE_WOOL_VERTICAL_SLAB, "light_blue_wool");
//        parentVertSlab(MinecraftBlocks.YELLOW_WOOL_VERTICAL_SLAB, "yellow_wool");
//        parentVertSlab(MinecraftBlocks.LIME_WOOL_VERTICAL_SLAB, "lime_wool");
//        parentVertSlab(MinecraftBlocks.PINK_WOOL_VERTICAL_SLAB, "pink_wool");
//        parentVertSlab(MinecraftBlocks.GRAY_WOOL_VERTICAL_SLAB, "gray_wool");
//        parentVertSlab(MinecraftBlocks.LIGHT_GRAY_WOOL_VERTICAL_SLAB, "light_gray_wool");
//        parentVertSlab(MinecraftBlocks.CYAN_WOOL_VERTICAL_SLAB, "cyan_wool");
//        parentVertSlab(MinecraftBlocks.PURPLE_WOOL_VERTICAL_SLAB, "purple_wool");
//        parentVertSlab(MinecraftBlocks.BLUE_WOOL_VERTICAL_SLAB, "blue_wool");
//        parentVertSlab(MinecraftBlocks.BROWN_WOOL_VERTICAL_SLAB, "brown_wool");
//        parentVertSlab(MinecraftBlocks.GREEN_WOOL_VERTICAL_SLAB, "green_wool");
//        parentVertSlab(MinecraftBlocks.RED_WOOL_VERTICAL_SLAB, "red_wool");
//        parentVertSlab(MinecraftBlocks.BLACK_WOOL_VERTICAL_SLAB, "black_wool");
//        parentVertSlab(MinecraftBlocks.STONE_VERTICAL_SLAB, "stone");
//        parentVertSlab(MinecraftBlocks.GRANITE_VERTICAL_SLAB, "granite");
//        parentVertSlab(MinecraftBlocks.POLISHED_GRANITE_VERTICAL_SLAB, "polished_granite");
//        parentVertSlab(MinecraftBlocks.DIORITE_VERTICAL_SLAB, "diorite");
//        parentVertSlab(MinecraftBlocks.POLISHED_DIORITE_VERTICAL_SLAB, "polished_diorite");
//        parentVertSlab(MinecraftBlocks.ANDESITE_VERTICAL_SLAB, "andesite");
//        parentVertSlab(MinecraftBlocks.POLISHED_ANDESITE_VERTICAL_SLAB, "polished_andesite");
//        parentVertSlab(MinecraftBlocks.DIRT_VERTICAL_SLAB, "dirt");
//        parentVertSlab(MinecraftBlocks.COARSE_DIRT_VERTICAL_SLAB, "coarse_dirt");
//        parentVertSlab(MinecraftBlocks.PODZOL_VERTICAL_SLAB, "podzol");
//        parentVertSlab(MinecraftBlocks.BEDROCK_VERTICAL_SLAB, "cobblestone");
//        parentVertSlab(MinecraftBlocks.BEDROCK_VERTICAL_SLAB, "bedrock");
//        parentVertSlab(MinecraftBlocks.SAND_VERTICAL_SLAB, "sand");
//        parentVertSlab(MinecraftBlocks.RED_SAND_VERTICAL_SLAB, "red_sand");
//        parentVertSlab(MinecraftBlocks.GRAVEL_VERTICAL_SLAB, "gravel");
//        parentVertSlab(MinecraftBlocks.GOLD_ORE_VERTICAL_SLAB, "gold_ore");
//        parentVertSlab(MinecraftBlocks.IRON_ORE_VERTICAL_SLAB, "iron_ore");
//        parentVertSlab(MinecraftBlocks.COAL_ORE_VERTICAL_SLAB, "coal_ore");
//        parentVertSlab(MinecraftBlocks.SPONGE_VERTICAL_SLAB, "sponge");
//        parentVertSlab(MinecraftBlocks.WET_SPONGE_VERTICAL_SLAB, "wet_sponge");
//        parentVertSlab(MinecraftBlocks.GLASS_VERTICAL_SLAB, "glass");
//        parentVertSlab(MinecraftBlocks.LAPIS_ORE_VERTICAL_SLAB, "lapis_ore");
//        parentVertSlab(MinecraftBlocks.LAPIS_BLOCK_VERTICAL_SLAB, "lapis_block");
//        parentVertSlab(MinecraftBlocks.SANDSTONE_VERTICAL_SLAB, "sandstone");
//        parentVertSlab(MinecraftBlocks.CHISELED_SANDSTONE_VERTICAL_SLAB, "chiseled_sandstone");
//        parentVertSlab(MinecraftBlocks.CUT_SANDSTONE_VERTICAL_SLAB, "cut_sandstone");
//        parentVertSlab(MinecraftBlocks.GOLD_BLOCK_VERTICAL_SLAB, "gold_block");
//        parentVertSlab(MinecraftBlocks.IRON_BLOCK_VERTICAL_SLAB, "iron_block");
//        parentVertSlab(MinecraftBlocks.SMOOTH_QUARTZ_VERTICAL_SLAB, "smooth_quartz");
//        parentVertSlab(MinecraftBlocks.RED_SANDSTONE_VERTICAL_SLAB, "smooth_red_sandstone");
//        parentVertSlab(MinecraftBlocks.SANDSTONE_VERTICAL_SLAB, "smooth_sandstone");
//        parentVertSlab(MinecraftBlocks.SMOOTH_STONE_VERTICAL_SLAB, "smooth_stone");
//        parentVertSlab(MinecraftBlocks.BRICK_VERTICAL_SLAB, "brick");
//        parentVertSlab(MinecraftBlocks.BOOKSHELF_VERTICAL_SLAB, "bookshelf");
//        parentVertSlab(MinecraftBlocks.MOSSY_COBBLESTONE_VERTICAL_SLAB, "mossy_cobblestone");
//        parentVertSlab(MinecraftBlocks.OBSIDIAN_VERTICAL_SLAB, "obsidian");
//        parentVertSlab(MinecraftBlocks.PURPUR_VERTICAL_SLAB, "purpur");
//        parentVertSlab(MinecraftBlocks.PURPUR_PILLAR_VERTICAL_SLAB, "purpur_pillar");
//        parentVertSlab(MinecraftBlocks.DIAMOND_ORE_VERTICAL_SLAB, "diamond_ore");
//        parentVertSlab(MinecraftBlocks.DIAMOND_BLOCK_VERTICAL_SLAB, "diamond_block");
//        parentVertSlab(MinecraftBlocks.REDSTONE_ORE_VERTICAL_SLAB, "redstone_ore");
//        parentVertSlab(MinecraftBlocks.ICE_VERTICAL_SLAB, "ice");
//        parentVertSlab(MinecraftBlocks.SNOW_VERTICAL_SLAB, "snow");
//        parentVertSlab(MinecraftBlocks.CLAY_VERTICAL_SLAB, "clay");
//        parentVertSlab(MinecraftBlocks.PUMPKIN_VERTICAL_SLAB, "pumpkin");
//        parentVertSlab(MinecraftBlocks.NETHERRACK_VERTICAL_SLAB, "netherrack");
//        parentVertSlab(MinecraftBlocks.SOUL_SAND_VERTICAL_SLAB, "soul_sand");
//        parentVertSlab(MinecraftBlocks.GLOWSTONE_VERTICAL_SLAB, "glowstone");
//        parentVertSlab(MinecraftBlocks.STONE_BRICK_VERTICAL_SLAB, "stone_brick");
//        parentVertSlab(MinecraftBlocks.MOSSY_STONE_BRICK_VERTICAL_SLAB, "mossy_stone_brick");
//        parentVertSlab(MinecraftBlocks.CRACKED_STONE_BRICK_VERTICAL_SLAB, "cracked_stone_brick");
//        parentVertSlab(MinecraftBlocks.CHISELED_STONE_BRICK_VERTICAL_SLAB, "chiseled_stone_brick");
//        parentVertSlab(MinecraftBlocks.BROWN_MUSHROOM_VERTICAL_SLAB, "brown_mushroom");
//        parentVertSlab(MinecraftBlocks.RED_MUSHROOM_VERTICAL_SLAB, "red_mushroom");
//        parentVertSlab(MinecraftBlocks.MUSHROOM_STEM_VERTICAL_SLAB, "mushroom_stem");
//        parentVertSlab(MinecraftBlocks.MELON_VERTICAL_SLAB, "melon");
//        parentVertSlab(MinecraftBlocks.MYCELIUM_VERTICAL_SLAB, "mycelium");
//        parentVertSlab(MinecraftBlocks.NETHER_BRICK_VERTICAL_SLAB, "nether_brick");
//        parentVertSlab(MinecraftBlocks.END_STONE_VERTICAL_SLAB, "end_stone");
//        parentVertSlab(MinecraftBlocks.END_STONE_BRICK_VERTICAL_SLAB, "end_stone_brick");
//        parentVertSlab(MinecraftBlocks.EMERALD_ORE_VERTICAL_SLAB, "emerald_ore");
//        parentVertSlab(MinecraftBlocks.EMERALD_BLOCK_VERTICAL_SLAB, "emerald_block");
//        parentVertSlab(MinecraftBlocks.REDSTONE_BLOCK_VERTICAL_SLAB, "redstone_block");
//        parentVertSlab(MinecraftBlocks.NETHER_QUARTZ_ORE_VERTICAL_SLAB, "nether_quartz_ore");
//        parentVertSlab(MinecraftBlocks.QUARTZ_VERTICAL_SLAB, "quartz");
//        parentVertSlab(MinecraftBlocks.CHISELED_QUARTZ_VERTICAL_SLAB, "chiseled_quartz");
//        parentVertSlab(MinecraftBlocks.QUARTZ_PILLAR_VERTICAL_SLAB, "quartz_pillar");
//        parentVertSlab(MinecraftBlocks.HAY_VERTICAL_SLAB, "hay");
//        parentVertSlab(MinecraftBlocks.TERRACOTTA_VERTICAL_SLAB, "terracotta");
//        parentVertSlab(MinecraftBlocks.COAL_VERTICAL_SLAB, "coal");
//        parentVertSlab(MinecraftBlocks.PACKED_ICE_VERTICAL_SLAB, "packed_ice");
//        parentVertSlab(MinecraftBlocks.SLIME_VERTICAL_SLAB, "slime");
//        parentVertSlab(MinecraftBlocks.PRISMARINE_VERTICAL_SLAB, "prismarine");
//        parentVertSlab(MinecraftBlocks.PRISMARINE_BRICK_VERTICAL_SLAB, "prismarine_brick");
//        parentVertSlab(MinecraftBlocks.DARK_PRISMARINE_VERTICAL_SLAB, "dark_prismarine");
//        parentVertSlab(MinecraftBlocks.SEA_LANTERN_VERTICAL_SLAB, "sea_lantern");
//        parentVertSlab(MinecraftBlocks.RED_SANDSTONE_VERTICAL_SLAB, "red_sandstone");
//        parentVertSlab(MinecraftBlocks.CHISELED_RED_SANDSTONE_VERTICAL_SLAB, "chiseled_red_sandstone");
//        parentVertSlab(MinecraftBlocks.CUT_RED_SANDSTONE_VERTICAL_SLAB, "cut_red_sandstone");
//        parentVertSlab(MinecraftBlocks.MAGMA_VERTICAL_SLAB, "magma");
//        parentVertSlab(MinecraftBlocks.NETHER_WART_VERTICAL_SLAB, "nether_wart");
//        parentVertSlab(MinecraftBlocks.RED_NETHER_BRICK_VERTICAL_SLAB, "red_nether_brick");
//        parentVertSlab(MinecraftBlocks.BONE_VERTICAL_SLAB, "bone");
//        parentVertSlab(MinecraftBlocks.DEAD_TUBE_CORAL_VERTICAL_SLAB, "dead_tube_coral");
//        parentVertSlab(MinecraftBlocks.DEAD_BRAIN_CORAL_VERTICAL_SLAB, "dead_brain_coral");
//        parentVertSlab(MinecraftBlocks.DEAD_BUBBLE_CORAL_VERTICAL_SLAB, "dead_bubble_coral");
//        parentVertSlab(MinecraftBlocks.DEAD_FIRE_CORAL_VERTICAL_SLAB, "dead_fire_coral");
//        parentVertSlab(MinecraftBlocks.DEAD_HORN_CORAL_VERTICAL_SLAB, "dead_horn_coral");
//        parentVertSlab(MinecraftBlocks.TUBE_CORAL_VERTICAL_SLAB, "tube_coral");
//        parentVertSlab(MinecraftBlocks.BRAIN_CORAL_VERTICAL_SLAB, "brain_coral");
//        parentVertSlab(MinecraftBlocks.BUBBLE_CORAL_VERTICAL_SLAB, "bubble_coral");
//        parentVertSlab(MinecraftBlocks.FIRE_CORAL_VERTICAL_SLAB, "fire_coral");
//        parentVertSlab(MinecraftBlocks.HORN_CORAL_VERTICAL_SLAB, "horn_coral");
//        parentVertSlab(MinecraftBlocks.DRIED_KELP_VERTICAL_SLAB, "dried_kelp");
//        parentVertSlab(MinecraftBlocks.HONEY_VERTICAL_SLAB, "honey");
//        parentVertSlab(MinecraftBlocks.HONEYCOMB_VERTICAL_SLAB, "honeycomb");
//        parentVertStairs(MinecraftBlocks.OAK_PLANK_VERTICAL_STAIRS, "oak_plank");
//        parentVertStairs(MinecraftBlocks.SPRUCE_PLANK_VERTICAL_STAIRS, "spruce_plank");
//        parentVertStairs(MinecraftBlocks.BIRCH_PLANK_VERTICAL_STAIRS, "birch_plank");
//        parentVertStairs(MinecraftBlocks.JUNGLE_PLANK_VERTICAL_STAIRS, "jungle_plank");
//        parentVertStairs(MinecraftBlocks.ACACIA_PLANK_VERTICAL_STAIRS, "acacia_plank");
//        parentVertStairs(MinecraftBlocks.DARK_OAK_PLANK_VERTICAL_STAIRS, "dark_oak_plank");
//        parentVertStairs(MinecraftBlocks.OAK_VERTICAL_STAIRS, "oak");
//        parentVertStairs(MinecraftBlocks.SPRUCE_VERTICAL_STAIRS, "spruce");
//        parentVertStairs(MinecraftBlocks.BIRCH_VERTICAL_STAIRS, "birch");
//        parentVertStairs(MinecraftBlocks.JUNGLE_VERTICAL_STAIRS, "jungle");
//        parentVertStairs(MinecraftBlocks.ACACIA_VERTICAL_STAIRS, "acacia");
//        parentVertStairs(MinecraftBlocks.DARK_OAK_VERTICAL_STAIRS, "dark_oak");
//        parentVertStairs(MinecraftBlocks.STRIPPED_OAK_VERTICAL_STAIRS, "stripped_oak");
//        parentVertStairs(MinecraftBlocks.STRIPPED_SPRUCE_VERTICAL_STAIRS, "stripped_spruce");
//        parentVertStairs(MinecraftBlocks.STRIPPED_BIRCH_VERTICAL_STAIRS, "stripped_birch");
//        parentVertStairs(MinecraftBlocks.STRIPPED_JUNGLE_VERTICAL_STAIRS, "stripped_jungle");
//        parentVertStairs(MinecraftBlocks.STRIPPED_ACACIA_VERTICAL_STAIRS, "stripped_acacia");
//        parentVertStairs(MinecraftBlocks.STRIPPED_DARK_OAK_VERTICAL_STAIRS, "stripped_dark_oak");
//        parentVertStairs(MinecraftBlocks.WHITE_CONCRETE_VERTICAL_STAIRS, "white_concrete");
//        parentVertStairs(MinecraftBlocks.ORANGE_CONCRETE_VERTICAL_STAIRS, "orange_concrete");
//        parentVertStairs(MinecraftBlocks.MAGENTA_CONCRETE_VERTICAL_STAIRS, "magenta_concrete");
//        parentVertStairs(MinecraftBlocks.LIGHT_BLUE_CONCRETE_VERTICAL_STAIRS, "light_blue_concrete");
//        parentVertStairs(MinecraftBlocks.YELLOW_CONCRETE_VERTICAL_STAIRS, "yellow_concrete");
//        parentVertStairs(MinecraftBlocks.LIME_CONCRETE_VERTICAL_STAIRS, "lime_concrete");
//        parentVertStairs(MinecraftBlocks.PINK_CONCRETE_VERTICAL_STAIRS, "pink_concrete");
//        parentVertStairs(MinecraftBlocks.GRAY_CONCRETE_VERTICAL_STAIRS, "gray_concrete");
//        parentVertStairs(MinecraftBlocks.LIGHT_GRAY_CONCRETE_VERTICAL_STAIRS, "light_gray_concrete");
//        parentVertStairs(MinecraftBlocks.CYAN_CONCRETE_VERTICAL_STAIRS, "cyan_concrete");
//        parentVertStairs(MinecraftBlocks.PURPLE_CONCRETE_VERTICAL_STAIRS, "purple_concrete");
//        parentVertStairs(MinecraftBlocks.BLUE_CONCRETE_VERTICAL_STAIRS, "blue_concrete");
//        parentVertStairs(MinecraftBlocks.BROWN_CONCRETE_VERTICAL_STAIRS, "brown_concrete");
//        parentVertStairs(MinecraftBlocks.GREEN_CONCRETE_VERTICAL_STAIRS, "green_concrete");
//        parentVertStairs(MinecraftBlocks.RED_CONCRETE_VERTICAL_STAIRS, "red_concrete");
//        parentVertStairs(MinecraftBlocks.BLACK_CONCRETE_VERTICAL_STAIRS, "black_concrete");
//        parentVertStairs(MinecraftBlocks.WHITE_CONCRETE_POWDER_VERTICAL_STAIRS, "white_concrete_powder");
//        parentVertStairs(MinecraftBlocks.ORANGE_CONCRETE_POWDER_VERTICAL_STAIRS, "orange_concrete_powder");
//        parentVertStairs(MinecraftBlocks.MAGENTA_CONCRETE_POWDER_VERTICAL_STAIRS, "magenta_concrete_powder");
//        parentVertStairs(MinecraftBlocks.LIGHT_BLUE_CONCRETE_POWDER_VERTICAL_STAIRS, "light_blue_concrete_powder");
//        parentVertStairs(MinecraftBlocks.YELLOW_CONCRETE_POWDER_VERTICAL_STAIRS, "yellow_concrete_powder");
//        parentVertStairs(MinecraftBlocks.LIME_CONCRETE_POWDER_VERTICAL_STAIRS, "lime_concrete_powder");
//        parentVertStairs(MinecraftBlocks.PINK_CONCRETE_POWDER_VERTICAL_STAIRS, "pink_concrete_powder");
//        parentVertStairs(MinecraftBlocks.GRAY_CONCRETE_POWDER_VERTICAL_STAIRS, "gray_concrete_powder");
//        parentVertStairs(MinecraftBlocks.LIGHT_GRAY_CONCRETE_POWDER_VERTICAL_STAIRS, "light_gray_concrete_powder");
//        parentVertStairs(MinecraftBlocks.CYAN_CONCRETE_POWDER_VERTICAL_STAIRS, "cyan_concrete_powder");
//        parentVertStairs(MinecraftBlocks.PURPLE_CONCRETE_POWDER_VERTICAL_STAIRS, "purple_concrete_powder");
//        parentVertStairs(MinecraftBlocks.BLUE_CONCRETE_POWDER_VERTICAL_STAIRS, "blue_concrete_powder");
//        parentVertStairs(MinecraftBlocks.BROWN_CONCRETE_POWDER_VERTICAL_STAIRS, "brown_concrete_powder");
//        parentVertStairs(MinecraftBlocks.GREEN_CONCRETE_POWDER_VERTICAL_STAIRS, "green_concrete_powder");
//        parentVertStairs(MinecraftBlocks.RED_CONCRETE_POWDER_VERTICAL_STAIRS, "red_concrete_powder");
//        parentVertStairs(MinecraftBlocks.BLACK_CONCRETE_POWDER_VERTICAL_STAIRS, "black_concrete_powder");
//        parentVertStairs(MinecraftBlocks.WHITE_GLAZED_TERRACOTTA_VERTICAL_STAIRS, "white_glazed_terracotta");
//        parentVertStairs(MinecraftBlocks.ORANGE_GLAZED_TERRACOTTA_VERTICAL_STAIRS, "orange_glazed_terracotta");
//        parentVertStairs(MinecraftBlocks.MAGENTA_GLAZED_TERRACOTTA_VERTICAL_STAIRS, "magenta_glazed_terracotta");
//        parentVertStairs(MinecraftBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_VERTICAL_STAIRS, "light_blue_glazed_terracotta");
//        parentVertStairs(MinecraftBlocks.YELLOW_GLAZED_TERRACOTTA_VERTICAL_STAIRS, "yellow_glazed_terracotta");
//        parentVertStairs(MinecraftBlocks.LIME_GLAZED_TERRACOTTA_VERTICAL_STAIRS, "lime_glazed_terracotta");
//        parentVertStairs(MinecraftBlocks.PINK_GLAZED_TERRACOTTA_VERTICAL_STAIRS, "pink_glazed_terracotta");
//        parentVertStairs(MinecraftBlocks.GRAY_GLAZED_TERRACOTTA_VERTICAL_STAIRS, "gray_glazed_terracotta");
//        parentVertStairs(MinecraftBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_VERTICAL_STAIRS, "light_gray_glazed_terracotta");
//        parentVertStairs(MinecraftBlocks.CYAN_GLAZED_TERRACOTTA_VERTICAL_STAIRS, "cyan_glazed_terracotta");
//        parentVertStairs(MinecraftBlocks.PURPLE_GLAZED_TERRACOTTA_VERTICAL_STAIRS, "purple_glazed_terracotta");
//        parentVertStairs(MinecraftBlocks.BLUE_GLAZED_TERRACOTTA_VERTICAL_STAIRS, "blue_glazed_terracotta");
//        parentVertStairs(MinecraftBlocks.BROWN_GLAZED_TERRACOTTA_VERTICAL_STAIRS, "brown_glazed_terracotta");
//        parentVertStairs(MinecraftBlocks.GREEN_GLAZED_TERRACOTTA_VERTICAL_STAIRS, "green_glazed_terracotta");
//        parentVertStairs(MinecraftBlocks.RED_GLAZED_TERRACOTTA_VERTICAL_STAIRS, "red_glazed_terracotta");
//        parentVertStairs(MinecraftBlocks.BLACK_GLAZED_TERRACOTTA_VERTICAL_STAIRS, "black_glazed_terracotta");
//        parentVertStairs(MinecraftBlocks.WHITE_STAINED_GLASS_VERTICAL_STAIRS, "white_stained_glass");
//        parentVertStairs(MinecraftBlocks.ORANGE_STAINED_GLASS_VERTICAL_STAIRS, "orange_stained_glass");
//        parentVertStairs(MinecraftBlocks.MAGENTA_STAINED_GLASS_VERTICAL_STAIRS, "magenta_stained_glass");
//        parentVertStairs(MinecraftBlocks.LIGHT_BLUE_STAINED_GLASS_VERTICAL_STAIRS, "light_blue_stained_glass");
//        parentVertStairs(MinecraftBlocks.YELLOW_STAINED_GLASS_VERTICAL_STAIRS, "yellow_stained_glass");
//        parentVertStairs(MinecraftBlocks.LIME_STAINED_GLASS_VERTICAL_STAIRS, "lime_stained_glass");
//        parentVertStairs(MinecraftBlocks.PINK_STAINED_GLASS_VERTICAL_STAIRS, "pink_stained_glass");
//        parentVertStairs(MinecraftBlocks.GRAY_STAINED_GLASS_VERTICAL_STAIRS, "gray_stained_glass");
//        parentVertStairs(MinecraftBlocks.LIGHT_GRAY_STAINED_GLASS_VERTICAL_STAIRS, "light_gray_stained_glass");
//        parentVertStairs(MinecraftBlocks.CYAN_STAINED_GLASS_VERTICAL_STAIRS, "cyan_stained_glass");
//        parentVertStairs(MinecraftBlocks.PURPLE_STAINED_GLASS_VERTICAL_STAIRS, "purple_stained_glass");
//        parentVertStairs(MinecraftBlocks.BLUE_STAINED_GLASS_VERTICAL_STAIRS, "blue_stained_glass");
//        parentVertStairs(MinecraftBlocks.BROWN_STAINED_GLASS_VERTICAL_STAIRS, "brown_stained_glass");
//        parentVertStairs(MinecraftBlocks.GREEN_STAINED_GLASS_VERTICAL_STAIRS, "green_stained_glass");
//        parentVertStairs(MinecraftBlocks.RED_STAINED_GLASS_VERTICAL_STAIRS, "red_stained_glass");
//        parentVertStairs(MinecraftBlocks.BLACK_STAINED_GLASS_VERTICAL_STAIRS, "black_stained_glass");
//        parentVertStairs(MinecraftBlocks.WHITE_TERRACOTTA_VERTICAL_STAIRS, "white_terracotta");
//        parentVertStairs(MinecraftBlocks.ORANGE_TERRACOTTA_VERTICAL_STAIRS, "orange_terracotta");
//        parentVertStairs(MinecraftBlocks.MAGENTA_TERRACOTTA_VERTICAL_STAIRS, "magenta_terracotta");
//        parentVertStairs(MinecraftBlocks.LIGHT_BLUE_TERRACOTTA_VERTICAL_STAIRS, "light_blue_terracotta");
//        parentVertStairs(MinecraftBlocks.YELLOW_TERRACOTTA_VERTICAL_STAIRS, "yellow_terracotta");
//        parentVertStairs(MinecraftBlocks.LIME_TERRACOTTA_VERTICAL_STAIRS, "lime_terracotta");
//        parentVertStairs(MinecraftBlocks.PINK_TERRACOTTA_VERTICAL_STAIRS, "pink_terracotta");
//        parentVertStairs(MinecraftBlocks.GRAY_TERRACOTTA_VERTICAL_STAIRS, "gray_terracotta");
//        parentVertStairs(MinecraftBlocks.LIGHT_GRAY_TERRACOTTA_VERTICAL_STAIRS, "light_gray_terracotta");
//        parentVertStairs(MinecraftBlocks.CYAN_TERRACOTTA_VERTICAL_STAIRS, "cyan_terracotta");
//        parentVertStairs(MinecraftBlocks.PURPLE_TERRACOTTA_VERTICAL_STAIRS, "purple_terracotta");
//        parentVertStairs(MinecraftBlocks.BLUE_TERRACOTTA_VERTICAL_STAIRS, "blue_terracotta");
//        parentVertStairs(MinecraftBlocks.BROWN_TERRACOTTA_VERTICAL_STAIRS, "brown_terracotta");
//        parentVertStairs(MinecraftBlocks.GREEN_TERRACOTTA_VERTICAL_STAIRS, "green_terracotta");
//        parentVertStairs(MinecraftBlocks.RED_TERRACOTTA_VERTICAL_STAIRS, "red_terracotta");
//        parentVertStairs(MinecraftBlocks.BLACK_TERRACOTTA_VERTICAL_STAIRS, "black_terracotta");
//        parentVertStairs(MinecraftBlocks.WHITE_WOOL_VERTICAL_STAIRS, "white_wool");
//        parentVertStairs(MinecraftBlocks.ORANGE_WOOL_VERTICAL_STAIRS, "orange_wool");
//        parentVertStairs(MinecraftBlocks.MAGENTA_WOOL_VERTICAL_STAIRS, "magenta_wool");
//        parentVertStairs(MinecraftBlocks.LIGHT_BLUE_WOOL_VERTICAL_STAIRS, "light_blue_wool");
//        parentVertStairs(MinecraftBlocks.YELLOW_WOOL_VERTICAL_STAIRS, "yellow_wool");
//        parentVertStairs(MinecraftBlocks.LIME_WOOL_VERTICAL_STAIRS, "lime_wool");
//        parentVertStairs(MinecraftBlocks.PINK_WOOL_VERTICAL_STAIRS, "pink_wool");
//        parentVertStairs(MinecraftBlocks.GRAY_WOOL_VERTICAL_STAIRS, "gray_wool");
//        parentVertStairs(MinecraftBlocks.LIGHT_GRAY_WOOL_VERTICAL_STAIRS, "light_gray_wool");
//        parentVertStairs(MinecraftBlocks.CYAN_WOOL_VERTICAL_STAIRS, "cyan_wool");
//        parentVertStairs(MinecraftBlocks.PURPLE_WOOL_VERTICAL_STAIRS, "purple_wool");
//        parentVertStairs(MinecraftBlocks.BLUE_WOOL_VERTICAL_STAIRS, "blue_wool");
//        parentVertStairs(MinecraftBlocks.BROWN_WOOL_VERTICAL_STAIRS, "brown_wool");
//        parentVertStairs(MinecraftBlocks.GREEN_WOOL_VERTICAL_STAIRS, "green_wool");
//        parentVertStairs(MinecraftBlocks.RED_WOOL_VERTICAL_STAIRS, "red_wool");
//        parentVertStairs(MinecraftBlocks.BLACK_WOOL_VERTICAL_STAIRS, "black_wool");
//        parentVertStairs(MinecraftBlocks.STONE_VERTICAL_STAIRS, "stone");
//        parentVertStairs(MinecraftBlocks.GRANITE_VERTICAL_STAIRS, "granite");
//        parentVertStairs(MinecraftBlocks.POLISHED_GRANITE_VERTICAL_STAIRS, "polished_granite");
//        parentVertStairs(MinecraftBlocks.DIORITE_VERTICAL_STAIRS, "diorite");
//        parentVertStairs(MinecraftBlocks.POLISHED_DIORITE_VERTICAL_STAIRS, "polished_diorite");
//        parentVertStairs(MinecraftBlocks.ANDESITE_VERTICAL_STAIRS, "andesite");
//        parentVertStairs(MinecraftBlocks.POLISHED_ANDESITE_VERTICAL_STAIRS, "polished_andesite");
//        parentVertStairs(MinecraftBlocks.DIRT_VERTICAL_STAIRS, "dirt");
//        parentVertStairs(MinecraftBlocks.COARSE_DIRT_VERTICAL_STAIRS, "coarse_dirt");
//        parentVertStairs(MinecraftBlocks.PODZOL_VERTICAL_STAIRS, "podzol");
//        parentVertStairs(MinecraftBlocks.BEDROCK_VERTICAL_STAIRS, "cobblestone");
//        parentVertStairs(MinecraftBlocks.BEDROCK_VERTICAL_STAIRS, "bedrock");
//        parentVertStairs(MinecraftBlocks.SAND_VERTICAL_STAIRS, "sand");
//        parentVertStairs(MinecraftBlocks.RED_SAND_VERTICAL_STAIRS, "red_sand");
//        parentVertStairs(MinecraftBlocks.GRAVEL_VERTICAL_STAIRS, "gravel");
//        parentVertStairs(MinecraftBlocks.GOLD_ORE_VERTICAL_STAIRS, "gold_ore");
//        parentVertStairs(MinecraftBlocks.IRON_ORE_VERTICAL_STAIRS, "iron_ore");
//        parentVertStairs(MinecraftBlocks.COAL_ORE_VERTICAL_STAIRS, "coal_ore");
//        parentVertStairs(MinecraftBlocks.SPONGE_VERTICAL_STAIRS, "sponge");
//        parentVertStairs(MinecraftBlocks.WET_SPONGE_VERTICAL_STAIRS, "wet_sponge");
//        parentVertStairs(MinecraftBlocks.GLASS_VERTICAL_STAIRS, "glass");
//        parentVertStairs(MinecraftBlocks.LAPIS_ORE_VERTICAL_STAIRS, "lapis_ore");
//        parentVertStairs(MinecraftBlocks.LAPIS_BLOCK_VERTICAL_STAIRS, "lapis_block");
//        parentVertStairs(MinecraftBlocks.SANDSTONE_VERTICAL_STAIRS, "sandstone");
//        parentVertStairs(MinecraftBlocks.CHISELED_SANDSTONE_VERTICAL_STAIRS, "chiseled_sandstone");
//        parentVertStairs(MinecraftBlocks.CUT_SANDSTONE_VERTICAL_STAIRS, "cut_sandstone");
//        parentVertStairs(MinecraftBlocks.GOLD_BLOCK_VERTICAL_STAIRS, "gold_block");
//        parentVertStairs(MinecraftBlocks.IRON_BLOCK_VERTICAL_STAIRS, "iron_block");
//        parentVertStairs(MinecraftBlocks.SMOOTH_QUARTZ_VERTICAL_STAIRS, "smooth_quartz");
//        parentVertStairs(MinecraftBlocks.RED_SANDSTONE_VERTICAL_STAIRS, "smooth_red_sandstone");
//        parentVertStairs(MinecraftBlocks.SANDSTONE_VERTICAL_STAIRS, "smooth_sandstone");
//        parentVertStairs(MinecraftBlocks.SMOOTH_STONE_VERTICAL_STAIRS, "smooth_stone");
//        parentVertStairs(MinecraftBlocks.BRICK_VERTICAL_STAIRS, "brick");
//        parentVertStairs(MinecraftBlocks.BOOKSHELF_VERTICAL_STAIRS, "bookshelf");
//        parentVertStairs(MinecraftBlocks.MOSSY_COBBLESTONE_VERTICAL_STAIRS, "mossy_cobblestone");
//        parentVertStairs(MinecraftBlocks.OBSIDIAN_VERTICAL_STAIRS, "obsidian");
//        parentVertStairs(MinecraftBlocks.PURPUR_VERTICAL_STAIRS, "purpur");
//        parentVertStairs(MinecraftBlocks.PURPUR_PILLAR_VERTICAL_STAIRS, "purpur_pillar");
//        parentVertStairs(MinecraftBlocks.DIAMOND_ORE_VERTICAL_STAIRS, "diamond_ore");
//        parentVertStairs(MinecraftBlocks.DIAMOND_BLOCK_VERTICAL_STAIRS, "diamond_block");
//        parentVertStairs(MinecraftBlocks.REDSTONE_ORE_VERTICAL_STAIRS, "redstone_ore");
//        parentVertStairs(MinecraftBlocks.ICE_VERTICAL_STAIRS, "ice");
//        parentVertStairs(MinecraftBlocks.SNOW_VERTICAL_STAIRS, "snow");
//        parentVertStairs(MinecraftBlocks.CLAY_VERTICAL_STAIRS, "clay");
//        parentVertStairs(MinecraftBlocks.PUMPKIN_VERTICAL_STAIRS, "pumpkin");
//        parentVertStairs(MinecraftBlocks.NETHERRACK_VERTICAL_STAIRS, "netherrack");
//        parentVertStairs(MinecraftBlocks.SOUL_SAND_VERTICAL_STAIRS, "soul_sand");
//        parentVertStairs(MinecraftBlocks.GLOWSTONE_VERTICAL_STAIRS, "glowstone");
//        parentVertStairs(MinecraftBlocks.STONE_BRICK_VERTICAL_STAIRS, "stone_brick");
//        parentVertStairs(MinecraftBlocks.MOSSY_STONE_BRICK_VERTICAL_STAIRS, "mossy_stone_brick");
//        parentVertStairs(MinecraftBlocks.CRACKED_STONE_BRICK_VERTICAL_STAIRS, "cracked_stone_brick");
//        parentVertStairs(MinecraftBlocks.CHISELED_STONE_BRICK_VERTICAL_STAIRS, "chiseled_stone_brick");
//        parentVertStairs(MinecraftBlocks.BROWN_MUSHROOM_VERTICAL_STAIRS, "brown_mushroom");
//        parentVertStairs(MinecraftBlocks.RED_MUSHROOM_VERTICAL_STAIRS, "red_mushroom");
//        parentVertStairs(MinecraftBlocks.MUSHROOM_STEM_VERTICAL_STAIRS, "mushroom_stem");
//        parentVertStairs(MinecraftBlocks.MELON_VERTICAL_STAIRS, "melon");
//        parentVertStairs(MinecraftBlocks.MYCELIUM_VERTICAL_STAIRS, "mycelium");
//        parentVertStairs(MinecraftBlocks.NETHER_BRICK_VERTICAL_STAIRS, "nether_brick");
//        parentVertStairs(MinecraftBlocks.END_STONE_VERTICAL_STAIRS, "end_stone");
//        parentVertStairs(MinecraftBlocks.END_STONE_BRICK_VERTICAL_STAIRS, "end_stone_brick");
//        parentVertStairs(MinecraftBlocks.EMERALD_ORE_VERTICAL_STAIRS, "emerald_ore");
//        parentVertStairs(MinecraftBlocks.EMERALD_BLOCK_VERTICAL_STAIRS, "emerald_block");
//        parentVertStairs(MinecraftBlocks.REDSTONE_BLOCK_VERTICAL_STAIRS, "redstone_block");
//        parentVertStairs(MinecraftBlocks.NETHER_QUARTZ_ORE_VERTICAL_STAIRS, "nether_quartz_ore");
//        parentVertStairs(MinecraftBlocks.QUARTZ_VERTICAL_STAIRS, "quartz");
//        parentVertStairs(MinecraftBlocks.CHISELED_QUARTZ_VERTICAL_STAIRS, "chiseled_quartz");
//        parentVertStairs(MinecraftBlocks.QUARTZ_PILLAR_VERTICAL_STAIRS, "quartz_pillar");
//        parentVertStairs(MinecraftBlocks.HAY_VERTICAL_STAIRS, "hay");
//        parentVertStairs(MinecraftBlocks.TERRACOTTA_VERTICAL_STAIRS, "terracotta");
//        parentVertStairs(MinecraftBlocks.COAL_VERTICAL_STAIRS, "coal");
//        parentVertStairs(MinecraftBlocks.PACKED_ICE_VERTICAL_STAIRS, "packed_ice");
//        parentVertStairs(MinecraftBlocks.SLIME_VERTICAL_STAIRS, "slime");
//        parentVertStairs(MinecraftBlocks.PRISMARINE_VERTICAL_STAIRS, "prismarine");
//        parentVertStairs(MinecraftBlocks.PRISMARINE_BRICK_VERTICAL_STAIRS, "prismarine_brick");
//        parentVertStairs(MinecraftBlocks.DARK_PRISMARINE_VERTICAL_STAIRS, "dark_prismarine");
//        parentVertStairs(MinecraftBlocks.SEA_LANTERN_VERTICAL_STAIRS, "sea_lantern");
//        parentVertStairs(MinecraftBlocks.RED_SANDSTONE_VERTICAL_STAIRS, "red_sandstone");
//        parentVertStairs(MinecraftBlocks.CHISELED_RED_SANDSTONE_VERTICAL_STAIRS, "chiseled_red_sandstone");
//        parentVertStairs(MinecraftBlocks.CUT_RED_SANDSTONE_VERTICAL_STAIRS, "cut_red_sandstone");
//        parentVertStairs(MinecraftBlocks.MAGMA_VERTICAL_STAIRS, "magma");
//        parentVertStairs(MinecraftBlocks.NETHER_WART_VERTICAL_STAIRS, "nether_wart");
//        parentVertStairs(MinecraftBlocks.RED_NETHER_BRICK_VERTICAL_STAIRS, "red_nether_brick");
//        parentVertStairs(MinecraftBlocks.BONE_VERTICAL_STAIRS, "bone");
//        parentVertStairs(MinecraftBlocks.DEAD_TUBE_CORAL_VERTICAL_STAIRS, "dead_tube_coral");
//        parentVertStairs(MinecraftBlocks.DEAD_BRAIN_CORAL_VERTICAL_STAIRS, "dead_brain_coral");
//        parentVertStairs(MinecraftBlocks.DEAD_BUBBLE_CORAL_VERTICAL_STAIRS, "dead_bubble_coral");
//        parentVertStairs(MinecraftBlocks.DEAD_FIRE_CORAL_VERTICAL_STAIRS, "dead_fire_coral");
//        parentVertStairs(MinecraftBlocks.DEAD_HORN_CORAL_VERTICAL_STAIRS, "dead_horn_coral");
//        parentVertStairs(MinecraftBlocks.TUBE_CORAL_VERTICAL_STAIRS, "tube_coral");
//        parentVertStairs(MinecraftBlocks.BRAIN_CORAL_VERTICAL_STAIRS, "brain_coral");
//        parentVertStairs(MinecraftBlocks.BUBBLE_CORAL_VERTICAL_STAIRS, "bubble_coral");
//        parentVertStairs(MinecraftBlocks.FIRE_CORAL_VERTICAL_STAIRS, "fire_coral");
//        parentVertStairs(MinecraftBlocks.HORN_CORAL_VERTICAL_STAIRS, "horn_coral");
//        parentVertStairs(MinecraftBlocks.DRIED_KELP_VERTICAL_STAIRS, "dried_kelp");
//        parentVertStairs(MinecraftBlocks.HONEY_VERTICAL_STAIRS, "honey");
//        parentVertStairs(MinecraftBlocks.HONEYCOMB_VERTICAL_STAIRS, "honeycomb");
    }
}
