package ihh.slabsstairswalls.minecraft;

import ihh.slabsstairswalls.LangGenENUS;
import ihh.slabsstairswalls.SlabsStairsWalls;
import net.minecraft.data.DataGenerator;

public final class MinecraftLangGenENUS extends LangGenENUS {
    public MinecraftLangGenENUS(DataGenerator g) {
        super(g);
    }

    @Override
    protected void addTranslations() {
        add("itemGroup." + SlabsStairsWalls.MODID, SlabsStairsWalls.MODNAME);
        fenceGate(MinecraftItems.NETHER_BRICK_FENCE_GATE, "Nether Brick");
        stairs(MinecraftItems.CUT_RED_SANDSTONE_STAIRS, "Cut Red Sandstone");
        stairs(MinecraftItems.CUT_SANDSTONE_STAIRS, "Cut Sandstone");
        stairs(MinecraftItems.SMOOTH_STONE_STAIRS, "Smooth Stone");
        wall(MinecraftItems.CUT_RED_SANDSTONE_WALL, "Cut Red Sandstone");
        wall(MinecraftItems.CUT_SANDSTONE_WALL, "Cut Sandstone");
        wall(MinecraftItems.DARK_PRISMARINE_WALL, "Dark Prismarine");
        wall(MinecraftItems.PRISMARINE_BRICK_WALL, "Prismarine Brick");
        wall(MinecraftItems.POLISHED_ANDESITE_WALL, "Polished Andesite");
        wall(MinecraftItems.POLISHED_DIORITE_WALL, "Polished Diorite");
        wall(MinecraftItems.POLISHED_GRANITE_WALL, "Polished Granite");
        wall(MinecraftItems.PURPUR_WALL, "Purpur");
        wall(MinecraftItems.QUARTZ_WALL, "Quartz");
        wall(MinecraftItems.SMOOTH_QUARTZ_WALL, "Smooth Quartz");
        wall(MinecraftItems.SMOOTH_RED_SANDSTONE_WALL, "Smooth Red Sandstone");
        wall(MinecraftItems.SMOOTH_SANDSTONE_WALL, "Smooth Sandstone");
        wall(MinecraftItems.SMOOTH_STONE_WALL, "Smooth Stone");
        wall(MinecraftItems.STONE_WALL, "Stone");
        slab(MinecraftItems.OAK_SLAB, "Oak");
        slab(MinecraftItems.SPRUCE_SLAB, "Spruce");
        slab(MinecraftItems.BIRCH_SLAB, "Birch");
        slab(MinecraftItems.JUNGLE_SLAB, "Jungle");
        slab(MinecraftItems.ACACIA_SLAB, "Acacia");
        slab(MinecraftItems.DARK_OAK_SLAB, "Dark Oak");
        slab(MinecraftItems.STRIPPED_OAK_SLAB, "Stripped Oak");
        slab(MinecraftItems.STRIPPED_SPRUCE_SLAB, "Stripped Spruce");
        slab(MinecraftItems.STRIPPED_BIRCH_SLAB, "Stripped Birch");
        slab(MinecraftItems.STRIPPED_JUNGLE_SLAB, "Stripped Jungle");
        slab(MinecraftItems.STRIPPED_ACACIA_SLAB, "Stripped Acacia");
        slab(MinecraftItems.STRIPPED_DARK_OAK_SLAB, "Stripped Dark Oak");
        rainbowSlab("Concrete", MinecraftItems.WHITE_CONCRETE_SLAB, MinecraftItems.ORANGE_CONCRETE_SLAB, MinecraftItems.MAGENTA_CONCRETE_SLAB, MinecraftItems.LIGHT_BLUE_CONCRETE_SLAB, MinecraftItems.YELLOW_CONCRETE_SLAB, MinecraftItems.LIME_CONCRETE_SLAB, MinecraftItems.PINK_CONCRETE_SLAB, MinecraftItems.GRAY_CONCRETE_SLAB, MinecraftItems.LIGHT_GRAY_CONCRETE_SLAB, MinecraftItems.CYAN_CONCRETE_SLAB, MinecraftItems.PURPLE_CONCRETE_SLAB, MinecraftItems.BLUE_CONCRETE_SLAB, MinecraftItems.BROWN_CONCRETE_SLAB, MinecraftItems.GREEN_CONCRETE_SLAB, MinecraftItems.RED_CONCRETE_SLAB, MinecraftItems.BLACK_CONCRETE_SLAB);
        rainbowSlab("Concrete Powder", MinecraftItems.WHITE_CONCRETE_POWDER_SLAB, MinecraftItems.ORANGE_CONCRETE_POWDER_SLAB, MinecraftItems.MAGENTA_CONCRETE_POWDER_SLAB, MinecraftItems.LIGHT_BLUE_CONCRETE_POWDER_SLAB, MinecraftItems.YELLOW_CONCRETE_POWDER_SLAB, MinecraftItems.LIME_CONCRETE_POWDER_SLAB, MinecraftItems.PINK_CONCRETE_POWDER_SLAB, MinecraftItems.GRAY_CONCRETE_POWDER_SLAB, MinecraftItems.LIGHT_GRAY_CONCRETE_POWDER_SLAB, MinecraftItems.CYAN_CONCRETE_POWDER_SLAB, MinecraftItems.PURPLE_CONCRETE_POWDER_SLAB, MinecraftItems.BLUE_CONCRETE_POWDER_SLAB, MinecraftItems.BROWN_CONCRETE_POWDER_SLAB, MinecraftItems.GREEN_CONCRETE_POWDER_SLAB, MinecraftItems.RED_CONCRETE_POWDER_SLAB, MinecraftItems.BLACK_CONCRETE_POWDER_SLAB);
        rainbowSlab("Glazed Terracotta", MinecraftItems.WHITE_GLAZED_TERRACOTTA_SLAB, MinecraftItems.ORANGE_GLAZED_TERRACOTTA_SLAB, MinecraftItems.MAGENTA_GLAZED_TERRACOTTA_SLAB, MinecraftItems.LIGHT_BLUE_GLAZED_TERRACOTTA_SLAB, MinecraftItems.YELLOW_GLAZED_TERRACOTTA_SLAB, MinecraftItems.LIME_GLAZED_TERRACOTTA_SLAB, MinecraftItems.PINK_GLAZED_TERRACOTTA_SLAB, MinecraftItems.GRAY_GLAZED_TERRACOTTA_SLAB, MinecraftItems.LIGHT_GRAY_GLAZED_TERRACOTTA_SLAB, MinecraftItems.CYAN_GLAZED_TERRACOTTA_SLAB, MinecraftItems.PURPLE_GLAZED_TERRACOTTA_SLAB, MinecraftItems.BLUE_GLAZED_TERRACOTTA_SLAB, MinecraftItems.BROWN_GLAZED_TERRACOTTA_SLAB, MinecraftItems.GREEN_GLAZED_TERRACOTTA_SLAB, MinecraftItems.RED_GLAZED_TERRACOTTA_SLAB, MinecraftItems.BLACK_GLAZED_TERRACOTTA_SLAB);
        rainbowSlab("Stained Glass", MinecraftItems.WHITE_STAINED_GLASS_SLAB, MinecraftItems.ORANGE_STAINED_GLASS_SLAB, MinecraftItems.MAGENTA_STAINED_GLASS_SLAB, MinecraftItems.LIGHT_BLUE_STAINED_GLASS_SLAB, MinecraftItems.YELLOW_STAINED_GLASS_SLAB, MinecraftItems.LIME_STAINED_GLASS_SLAB, MinecraftItems.PINK_STAINED_GLASS_SLAB, MinecraftItems.GRAY_STAINED_GLASS_SLAB, MinecraftItems.LIGHT_GRAY_STAINED_GLASS_SLAB, MinecraftItems.CYAN_STAINED_GLASS_SLAB, MinecraftItems.PURPLE_STAINED_GLASS_SLAB, MinecraftItems.BLUE_STAINED_GLASS_SLAB, MinecraftItems.BROWN_STAINED_GLASS_SLAB, MinecraftItems.GREEN_STAINED_GLASS_SLAB, MinecraftItems.RED_STAINED_GLASS_SLAB, MinecraftItems.BLACK_STAINED_GLASS_SLAB);
        rainbowSlab("Terracotta", MinecraftItems.WHITE_TERRACOTTA_SLAB, MinecraftItems.ORANGE_TERRACOTTA_SLAB, MinecraftItems.MAGENTA_TERRACOTTA_SLAB, MinecraftItems.LIGHT_BLUE_TERRACOTTA_SLAB, MinecraftItems.YELLOW_TERRACOTTA_SLAB, MinecraftItems.LIME_TERRACOTTA_SLAB, MinecraftItems.PINK_TERRACOTTA_SLAB, MinecraftItems.GRAY_TERRACOTTA_SLAB, MinecraftItems.LIGHT_GRAY_TERRACOTTA_SLAB, MinecraftItems.CYAN_TERRACOTTA_SLAB, MinecraftItems.PURPLE_TERRACOTTA_SLAB, MinecraftItems.BLUE_TERRACOTTA_SLAB, MinecraftItems.BROWN_TERRACOTTA_SLAB, MinecraftItems.GREEN_TERRACOTTA_SLAB, MinecraftItems.RED_TERRACOTTA_SLAB, MinecraftItems.BLACK_TERRACOTTA_SLAB);
        rainbowSlab("Wool", MinecraftItems.WHITE_WOOL_SLAB, MinecraftItems.ORANGE_WOOL_SLAB, MinecraftItems.MAGENTA_WOOL_SLAB, MinecraftItems.LIGHT_BLUE_WOOL_SLAB, MinecraftItems.YELLOW_WOOL_SLAB, MinecraftItems.LIME_WOOL_SLAB, MinecraftItems.PINK_WOOL_SLAB, MinecraftItems.GRAY_WOOL_SLAB, MinecraftItems.LIGHT_GRAY_WOOL_SLAB, MinecraftItems.CYAN_WOOL_SLAB, MinecraftItems.PURPLE_WOOL_SLAB, MinecraftItems.BLUE_WOOL_SLAB, MinecraftItems.BROWN_WOOL_SLAB, MinecraftItems.GREEN_WOOL_SLAB, MinecraftItems.RED_WOOL_SLAB, MinecraftItems.BLACK_WOOL_SLAB);
        slab(MinecraftItems.DIRT_SLAB, "Dirt");
        slab(MinecraftItems.COARSE_DIRT_SLAB, "Coarse Dirt");
        slab(MinecraftItems.PODZOL_SLAB, "Podzol");
        slab(MinecraftItems.BEDROCK_SLAB, "Bedrock");
        slab(MinecraftItems.SAND_SLAB, "Sand");
        slab(MinecraftItems.RED_SAND_SLAB, "Red Sand");
        slab(MinecraftItems.GRAVEL_SLAB, "Gravel");
        slab(MinecraftItems.GOLD_ORE_SLAB, "Gold Ore");
        slab(MinecraftItems.IRON_ORE_SLAB, "Iron Ore");
        slab(MinecraftItems.COAL_ORE_SLAB, "Coal Ore");
        slab(MinecraftItems.SPONGE_SLAB, "Sponge");
        slab(MinecraftItems.WET_SPONGE_SLAB, "Wet Sponge");
        slab(MinecraftItems.GLASS_SLAB, "Glass");
        slab(MinecraftItems.LAPIS_ORE_SLAB, "Lapis Ore");
        slab(MinecraftItems.LAPIS_BLOCK_SLAB, "Lapis Block");
        slab(MinecraftItems.CHISELED_SANDSTONE_SLAB, "Chiseled Sandstone");
        slab(MinecraftItems.GOLD_BLOCK_SLAB, "Gold Block");
        slab(MinecraftItems.IRON_BLOCK_SLAB, "Iron Block");
        slab(MinecraftItems.BOOKSHELF_SLAB, "Bookshelf");
        slab(MinecraftItems.OBSIDIAN_SLAB, "Obsidian");
        slab(MinecraftItems.PURPUR_PILLAR_SLAB, "Purpur Pillar");
        slab(MinecraftItems.DIAMOND_ORE_SLAB, "Diamond Ore");
        slab(MinecraftItems.DIAMOND_BLOCK_SLAB, "Diamond Block");
        slab(MinecraftItems.REDSTONE_ORE_SLAB, "Redstone Ore");
        slab(MinecraftItems.ICE_SLAB, "Ice");
        slab(MinecraftItems.SNOW_SLAB, "Snow");
        slab(MinecraftItems.CLAY_SLAB, "Clay");
        slab(MinecraftItems.PUMPKIN_SLAB, "Pumpkin");
        slab(MinecraftItems.NETHERRACK_SLAB, "Netherrack");
        slab(MinecraftItems.SOUL_SAND_SLAB, "Soul Sand");
        slab(MinecraftItems.GLOWSTONE_SLAB, "Glowstone");
        slab(MinecraftItems.CRACKED_STONE_BRICK_SLAB, "Cracked Stone Brick");
        slab(MinecraftItems.CHISELED_STONE_BRICK_SLAB, "Chiseled Stone Brick");
        slab(MinecraftItems.BROWN_MUSHROOM_SLAB, "Brown Mushroom");
        slab(MinecraftItems.RED_MUSHROOM_SLAB, "Red Mushroom");
        slab(MinecraftItems.MUSHROOM_STEM_SLAB, "Mushroom Stem");
        slab(MinecraftItems.MELON_SLAB, "Melon");
        slab(MinecraftItems.MYCELIUM_SLAB, "Mycelium");
        slab(MinecraftItems.END_STONE_SLAB, "End Stone");
        slab(MinecraftItems.EMERALD_ORE_SLAB, "Emerald Ore");
        slab(MinecraftItems.EMERALD_BLOCK_SLAB, "Emerald Block");
        slab(MinecraftItems.REDSTONE_BLOCK_SLAB, "Redstone Block");
        slab(MinecraftItems.NETHER_QUARTZ_ORE_SLAB, "Nether Quartz Ore");
        slab(MinecraftItems.CHISELED_QUARTZ_SLAB, "Chiseled Quartz");
        slab(MinecraftItems.QUARTZ_PILLAR_SLAB, "Quartz Pillar");
        slab(MinecraftItems.HAY_SLAB, "Hay");
        slab(MinecraftItems.TERRACOTTA_SLAB, "Terracotta");
        slab(MinecraftItems.COAL_SLAB, "Coal");
        slab(MinecraftItems.PACKED_ICE_SLAB, "Packed Ice");
        slab(MinecraftItems.SLIME_SLAB, "Slime");
        slab(MinecraftItems.SEA_LANTERN_SLAB, "Sea Lantern");
        slab(MinecraftItems.CHISELED_RED_SANDSTONE_SLAB, "Chiseled Red Sandstone");
        slab(MinecraftItems.MAGMA_SLAB, "Magma");
        slab(MinecraftItems.NETHER_WART_SLAB, "Nether Wart");
        slab(MinecraftItems.BONE_SLAB, "Bone");
        slab(MinecraftItems.DEAD_TUBE_CORAL_SLAB, "Dead Tube Coral");
        slab(MinecraftItems.DEAD_BRAIN_CORAL_SLAB, "Dead Brain Coral");
        slab(MinecraftItems.DEAD_BUBBLE_CORAL_SLAB, "Dead Bubble Coral");
        slab(MinecraftItems.DEAD_FIRE_CORAL_SLAB, "Dead Fire Coral");
        slab(MinecraftItems.DEAD_HORN_CORAL_SLAB, "Dead Horn Coral");
        slab(MinecraftItems.TUBE_CORAL_SLAB, "Tube Coral");
        slab(MinecraftItems.BRAIN_CORAL_SLAB, "Brain Coral");
        slab(MinecraftItems.BUBBLE_CORAL_SLAB, "Bubble Coral");
        slab(MinecraftItems.FIRE_CORAL_SLAB, "Fire Coral");
        slab(MinecraftItems.HORN_CORAL_SLAB, "Horn Coral");
        slab(MinecraftItems.DRIED_KELP_SLAB, "Dried Kelp");
        slab(MinecraftItems.HONEY_SLAB, "Honey");
        slab(MinecraftItems.HONEYCOMB_SLAB, "Honeycomb");
        stairs(MinecraftItems.OAK_STAIRS, "Oak");
        stairs(MinecraftItems.SPRUCE_STAIRS, "Spruce");
        stairs(MinecraftItems.BIRCH_STAIRS, "Birch");
        stairs(MinecraftItems.JUNGLE_STAIRS, "Jungle");
        stairs(MinecraftItems.ACACIA_STAIRS, "Acacia");
        stairs(MinecraftItems.DARK_OAK_STAIRS, "Dark Oak");
        stairs(MinecraftItems.STRIPPED_OAK_STAIRS, "Stripped Oak");
        stairs(MinecraftItems.STRIPPED_SPRUCE_STAIRS, "Stripped Spruce");
        stairs(MinecraftItems.STRIPPED_BIRCH_STAIRS, "Stripped Birch");
        stairs(MinecraftItems.STRIPPED_JUNGLE_STAIRS, "Stripped Jungle");
        stairs(MinecraftItems.STRIPPED_ACACIA_STAIRS, "Stripped Acacia");
        stairs(MinecraftItems.STRIPPED_DARK_OAK_STAIRS, "Stripped Dark Oak");
        rainbowStairs("Concrete", MinecraftItems.WHITE_CONCRETE_STAIRS, MinecraftItems.ORANGE_CONCRETE_STAIRS, MinecraftItems.MAGENTA_CONCRETE_STAIRS, MinecraftItems.LIGHT_BLUE_CONCRETE_STAIRS, MinecraftItems.YELLOW_CONCRETE_STAIRS, MinecraftItems.LIME_CONCRETE_STAIRS, MinecraftItems.PINK_CONCRETE_STAIRS, MinecraftItems.GRAY_CONCRETE_STAIRS, MinecraftItems.LIGHT_GRAY_CONCRETE_STAIRS, MinecraftItems.CYAN_CONCRETE_STAIRS, MinecraftItems.PURPLE_CONCRETE_STAIRS, MinecraftItems.BLUE_CONCRETE_STAIRS, MinecraftItems.BROWN_CONCRETE_STAIRS, MinecraftItems.GREEN_CONCRETE_STAIRS, MinecraftItems.RED_CONCRETE_STAIRS, MinecraftItems.BLACK_CONCRETE_STAIRS);
        rainbowStairs("Concrete Powder", MinecraftItems.WHITE_CONCRETE_POWDER_STAIRS, MinecraftItems.ORANGE_CONCRETE_POWDER_STAIRS, MinecraftItems.MAGENTA_CONCRETE_POWDER_STAIRS, MinecraftItems.LIGHT_BLUE_CONCRETE_POWDER_STAIRS, MinecraftItems.YELLOW_CONCRETE_POWDER_STAIRS, MinecraftItems.LIME_CONCRETE_POWDER_STAIRS, MinecraftItems.PINK_CONCRETE_POWDER_STAIRS, MinecraftItems.GRAY_CONCRETE_POWDER_STAIRS, MinecraftItems.LIGHT_GRAY_CONCRETE_POWDER_STAIRS, MinecraftItems.CYAN_CONCRETE_POWDER_STAIRS, MinecraftItems.PURPLE_CONCRETE_POWDER_STAIRS, MinecraftItems.BLUE_CONCRETE_POWDER_STAIRS, MinecraftItems.BROWN_CONCRETE_POWDER_STAIRS, MinecraftItems.GREEN_CONCRETE_POWDER_STAIRS, MinecraftItems.RED_CONCRETE_POWDER_STAIRS, MinecraftItems.BLACK_CONCRETE_POWDER_STAIRS);
        rainbowStairs("Glazed Terracotta", MinecraftItems.WHITE_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.ORANGE_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.MAGENTA_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.LIGHT_BLUE_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.YELLOW_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.LIME_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.PINK_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.GRAY_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.LIGHT_GRAY_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.CYAN_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.PURPLE_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.BLUE_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.BROWN_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.GREEN_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.RED_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.BLACK_GLAZED_TERRACOTTA_STAIRS);
        rainbowStairs("Glass", MinecraftItems.WHITE_STAINED_GLASS_STAIRS, MinecraftItems.ORANGE_STAINED_GLASS_STAIRS, MinecraftItems.MAGENTA_STAINED_GLASS_STAIRS, MinecraftItems.LIGHT_BLUE_STAINED_GLASS_STAIRS, MinecraftItems.YELLOW_STAINED_GLASS_STAIRS, MinecraftItems.LIME_STAINED_GLASS_STAIRS, MinecraftItems.PINK_STAINED_GLASS_STAIRS, MinecraftItems.GRAY_STAINED_GLASS_STAIRS, MinecraftItems.LIGHT_GRAY_STAINED_GLASS_STAIRS, MinecraftItems.CYAN_STAINED_GLASS_STAIRS, MinecraftItems.PURPLE_STAINED_GLASS_STAIRS, MinecraftItems.BLUE_STAINED_GLASS_STAIRS, MinecraftItems.BROWN_STAINED_GLASS_STAIRS, MinecraftItems.GREEN_STAINED_GLASS_STAIRS, MinecraftItems.RED_STAINED_GLASS_STAIRS, MinecraftItems.BLACK_STAINED_GLASS_STAIRS);
        rainbowStairs("Terracotta", MinecraftItems.WHITE_TERRACOTTA_STAIRS, MinecraftItems.ORANGE_TERRACOTTA_STAIRS, MinecraftItems.MAGENTA_TERRACOTTA_STAIRS, MinecraftItems.LIGHT_BLUE_TERRACOTTA_STAIRS, MinecraftItems.YELLOW_TERRACOTTA_STAIRS, MinecraftItems.LIME_TERRACOTTA_STAIRS, MinecraftItems.PINK_TERRACOTTA_STAIRS, MinecraftItems.GRAY_TERRACOTTA_STAIRS, MinecraftItems.LIGHT_GRAY_TERRACOTTA_STAIRS, MinecraftItems.CYAN_TERRACOTTA_STAIRS, MinecraftItems.PURPLE_TERRACOTTA_STAIRS, MinecraftItems.BLUE_TERRACOTTA_STAIRS, MinecraftItems.BROWN_TERRACOTTA_STAIRS, MinecraftItems.GREEN_TERRACOTTA_STAIRS, MinecraftItems.RED_TERRACOTTA_STAIRS, MinecraftItems.BLACK_TERRACOTTA_STAIRS);
        rainbowStairs("Wool", MinecraftItems.WHITE_WOOL_STAIRS, MinecraftItems.ORANGE_WOOL_STAIRS, MinecraftItems.MAGENTA_WOOL_STAIRS, MinecraftItems.LIGHT_BLUE_WOOL_STAIRS, MinecraftItems.YELLOW_WOOL_STAIRS, MinecraftItems.LIME_WOOL_STAIRS, MinecraftItems.PINK_WOOL_STAIRS, MinecraftItems.GRAY_WOOL_STAIRS, MinecraftItems.LIGHT_GRAY_WOOL_STAIRS, MinecraftItems.CYAN_WOOL_STAIRS, MinecraftItems.PURPLE_WOOL_STAIRS, MinecraftItems.BLUE_WOOL_STAIRS, MinecraftItems.BROWN_WOOL_STAIRS, MinecraftItems.GREEN_WOOL_STAIRS, MinecraftItems.RED_WOOL_STAIRS, MinecraftItems.BLACK_WOOL_STAIRS);
        stairs(MinecraftItems.DIRT_STAIRS, "Dirt");
        stairs(MinecraftItems.COARSE_DIRT_STAIRS, "Coarse Dirt");
        stairs(MinecraftItems.PODZOL_STAIRS, "Podzol");
        stairs(MinecraftItems.BEDROCK_STAIRS, "Bedrock");
        stairs(MinecraftItems.SAND_STAIRS, "Sand");
        stairs(MinecraftItems.RED_SAND_STAIRS, "Red Sand");
        stairs(MinecraftItems.GRAVEL_STAIRS, "Gravel");
        stairs(MinecraftItems.GOLD_ORE_STAIRS, "Gold Ore");
        stairs(MinecraftItems.IRON_ORE_STAIRS, "Iron Ore");
        stairs(MinecraftItems.COAL_ORE_STAIRS, "Coal Ore");
        stairs(MinecraftItems.SPONGE_STAIRS, "Sponge");
        stairs(MinecraftItems.WET_SPONGE_STAIRS, "Wet Sponge");
        stairs(MinecraftItems.GLASS_STAIRS, "Glass");
        stairs(MinecraftItems.LAPIS_ORE_STAIRS, "Lapis Ore");
        stairs(MinecraftItems.LAPIS_BLOCK_STAIRS, "Lapis Block");
        stairs(MinecraftItems.CHISELED_SANDSTONE_STAIRS, "Chiseled Sandstone");
        stairs(MinecraftItems.GOLD_BLOCK_STAIRS, "Gold Block");
        stairs(MinecraftItems.IRON_BLOCK_STAIRS, "Iron Block");
        stairs(MinecraftItems.BOOKSHELF_STAIRS, "Bookshelf");
        stairs(MinecraftItems.OBSIDIAN_STAIRS, "Obsidian");
        stairs(MinecraftItems.PURPUR_PILLAR_STAIRS, "Purpur Pillar");
        stairs(MinecraftItems.DIAMOND_ORE_STAIRS, "Diamond Ore");
        stairs(MinecraftItems.DIAMOND_BLOCK_STAIRS, "Diamond Block");
        stairs(MinecraftItems.REDSTONE_ORE_STAIRS, "Redstone Ore");
        stairs(MinecraftItems.ICE_STAIRS, "Ice");
        stairs(MinecraftItems.SNOW_STAIRS, "Snow");
        stairs(MinecraftItems.CLAY_STAIRS, "Clay");
        stairs(MinecraftItems.PUMPKIN_STAIRS, "Pumpkin");
        stairs(MinecraftItems.NETHERRACK_STAIRS, "Netherrack");
        stairs(MinecraftItems.SOUL_SAND_STAIRS, "Soul Sand");
        stairs(MinecraftItems.GLOWSTONE_STAIRS, "Glowstone");
        stairs(MinecraftItems.CRACKED_STONE_BRICK_STAIRS, "Cracked Stone Brick");
        stairs(MinecraftItems.CHISELED_STONE_BRICK_STAIRS, "Chiseled Stone Brick");
        stairs(MinecraftItems.BROWN_MUSHROOM_STAIRS, "Brown Mushroom");
        stairs(MinecraftItems.RED_MUSHROOM_STAIRS, "Red Mushroom");
        stairs(MinecraftItems.MUSHROOM_STEM_STAIRS, "Mushroom Stem");
        stairs(MinecraftItems.MELON_STAIRS, "Melon");
        stairs(MinecraftItems.MYCELIUM_STAIRS, "Mycelium");
        stairs(MinecraftItems.END_STONE_STAIRS, "End Stone");
        stairs(MinecraftItems.EMERALD_ORE_STAIRS, "Emerald Ore");
        stairs(MinecraftItems.EMERALD_BLOCK_STAIRS, "Emerald Block");
        stairs(MinecraftItems.REDSTONE_BLOCK_STAIRS, "Redstone Block");
        stairs(MinecraftItems.NETHER_QUARTZ_ORE_STAIRS, "Nether Quartz Ore");
        stairs(MinecraftItems.CHISELED_QUARTZ_STAIRS, "Chiseled Quartz");
        stairs(MinecraftItems.QUARTZ_PILLAR_STAIRS, "Quartz Pillar");
        stairs(MinecraftItems.HAY_STAIRS, "Hay");
        stairs(MinecraftItems.TERRACOTTA_STAIRS, "Terracotta");
        stairs(MinecraftItems.COAL_STAIRS, "Coal");
        stairs(MinecraftItems.PACKED_ICE_STAIRS, "Packed Ice");
        stairs(MinecraftItems.SLIME_STAIRS, "Slime");
        stairs(MinecraftItems.SEA_LANTERN_STAIRS, "Sea Lantern");
        stairs(MinecraftItems.CHISELED_RED_SANDSTONE_STAIRS, "Chiseled Red Sandstone");
        stairs(MinecraftItems.MAGMA_STAIRS, "Magma");
        stairs(MinecraftItems.NETHER_WART_STAIRS, "Nether Wart");
        stairs(MinecraftItems.BONE_STAIRS, "Bone");
        stairs(MinecraftItems.DEAD_TUBE_CORAL_STAIRS, "Dead Tube Coral");
        stairs(MinecraftItems.DEAD_BRAIN_CORAL_STAIRS, "Dead Brain Coral");
        stairs(MinecraftItems.DEAD_BUBBLE_CORAL_STAIRS, "Dead Bubble Coral");
        stairs(MinecraftItems.DEAD_FIRE_CORAL_STAIRS, "Dead Fire Coral");
        stairs(MinecraftItems.DEAD_HORN_CORAL_STAIRS, "Dead Horn Coral");
        stairs(MinecraftItems.TUBE_CORAL_STAIRS, "Tube Coral");
        stairs(MinecraftItems.BRAIN_CORAL_STAIRS, "Brain Coral");
        stairs(MinecraftItems.BUBBLE_CORAL_STAIRS, "Bubble Coral");
        stairs(MinecraftItems.FIRE_CORAL_STAIRS, "Fire Coral");
        stairs(MinecraftItems.HORN_CORAL_STAIRS, "Horn Coral");
        stairs(MinecraftItems.DRIED_KELP_STAIRS, "Dried Kelp");
        stairs(MinecraftItems.HONEY_STAIRS, "Honey");
        stairs(MinecraftItems.HONEYCOMB_STAIRS, "Honeycomb");
        wall(MinecraftItems.OAK_WALL, "Oak");
        wall(MinecraftItems.SPRUCE_WALL, "Spruce");
        wall(MinecraftItems.BIRCH_WALL, "Birch");
        wall(MinecraftItems.JUNGLE_WALL, "Jungle");
        wall(MinecraftItems.ACACIA_WALL, "Acacia");
        wall(MinecraftItems.DARK_OAK_WALL, "Dark Oak");
        wall(MinecraftItems.STRIPPED_OAK_WALL, "Stripped Oak");
        wall(MinecraftItems.STRIPPED_SPRUCE_WALL, "Stripped Spruce");
        wall(MinecraftItems.STRIPPED_BIRCH_WALL, "Stripped Birch");
        wall(MinecraftItems.STRIPPED_JUNGLE_WALL, "Stripped Jungle");
        wall(MinecraftItems.STRIPPED_ACACIA_WALL, "Stripped Acacia");
        wall(MinecraftItems.STRIPPED_DARK_OAK_WALL, "Stripped Dark Oak");
        rainbowWall("Concrete", MinecraftItems.WHITE_CONCRETE_WALL, MinecraftItems.ORANGE_CONCRETE_WALL, MinecraftItems.MAGENTA_CONCRETE_WALL, MinecraftItems.LIGHT_BLUE_CONCRETE_WALL, MinecraftItems.YELLOW_CONCRETE_WALL, MinecraftItems.LIME_CONCRETE_WALL, MinecraftItems.PINK_CONCRETE_WALL, MinecraftItems.GRAY_CONCRETE_WALL, MinecraftItems.LIGHT_GRAY_CONCRETE_WALL, MinecraftItems.CYAN_CONCRETE_WALL, MinecraftItems.PURPLE_CONCRETE_WALL, MinecraftItems.BLUE_CONCRETE_WALL, MinecraftItems.BROWN_CONCRETE_WALL, MinecraftItems.GREEN_CONCRETE_WALL, MinecraftItems.RED_CONCRETE_WALL, MinecraftItems.BLACK_CONCRETE_WALL);
        rainbowWall("Concrete Powder", MinecraftItems.WHITE_CONCRETE_POWDER_WALL, MinecraftItems.ORANGE_CONCRETE_POWDER_WALL, MinecraftItems.MAGENTA_CONCRETE_POWDER_WALL, MinecraftItems.LIGHT_BLUE_CONCRETE_POWDER_WALL, MinecraftItems.YELLOW_CONCRETE_POWDER_WALL, MinecraftItems.LIME_CONCRETE_POWDER_WALL, MinecraftItems.PINK_CONCRETE_POWDER_WALL, MinecraftItems.GRAY_CONCRETE_POWDER_WALL, MinecraftItems.LIGHT_GRAY_CONCRETE_POWDER_WALL, MinecraftItems.CYAN_CONCRETE_POWDER_WALL, MinecraftItems.PURPLE_CONCRETE_POWDER_WALL, MinecraftItems.BLUE_CONCRETE_POWDER_WALL, MinecraftItems.BROWN_CONCRETE_POWDER_WALL, MinecraftItems.GREEN_CONCRETE_POWDER_WALL, MinecraftItems.RED_CONCRETE_POWDER_WALL, MinecraftItems.BLACK_CONCRETE_POWDER_WALL);
        rainbowWall("Glazed Terracotta", MinecraftItems.WHITE_GLAZED_TERRACOTTA_WALL, MinecraftItems.ORANGE_GLAZED_TERRACOTTA_WALL, MinecraftItems.MAGENTA_GLAZED_TERRACOTTA_WALL, MinecraftItems.LIGHT_BLUE_GLAZED_TERRACOTTA_WALL, MinecraftItems.YELLOW_GLAZED_TERRACOTTA_WALL, MinecraftItems.LIME_GLAZED_TERRACOTTA_WALL, MinecraftItems.PINK_GLAZED_TERRACOTTA_WALL, MinecraftItems.GRAY_GLAZED_TERRACOTTA_WALL, MinecraftItems.LIGHT_GRAY_GLAZED_TERRACOTTA_WALL, MinecraftItems.CYAN_GLAZED_TERRACOTTA_WALL, MinecraftItems.PURPLE_GLAZED_TERRACOTTA_WALL, MinecraftItems.BLUE_GLAZED_TERRACOTTA_WALL, MinecraftItems.BROWN_GLAZED_TERRACOTTA_WALL, MinecraftItems.GREEN_GLAZED_TERRACOTTA_WALL, MinecraftItems.RED_GLAZED_TERRACOTTA_WALL, MinecraftItems.BLACK_GLAZED_TERRACOTTA_WALL);
        rainbowWall("Glass", MinecraftItems.WHITE_STAINED_GLASS_WALL, MinecraftItems.ORANGE_STAINED_GLASS_WALL, MinecraftItems.MAGENTA_STAINED_GLASS_WALL, MinecraftItems.LIGHT_BLUE_STAINED_GLASS_WALL, MinecraftItems.YELLOW_STAINED_GLASS_WALL, MinecraftItems.LIME_STAINED_GLASS_WALL, MinecraftItems.PINK_STAINED_GLASS_WALL, MinecraftItems.GRAY_STAINED_GLASS_WALL, MinecraftItems.LIGHT_GRAY_STAINED_GLASS_WALL, MinecraftItems.CYAN_STAINED_GLASS_WALL, MinecraftItems.PURPLE_STAINED_GLASS_WALL, MinecraftItems.BLUE_STAINED_GLASS_WALL, MinecraftItems.BROWN_STAINED_GLASS_WALL, MinecraftItems.GREEN_STAINED_GLASS_WALL, MinecraftItems.RED_STAINED_GLASS_WALL, MinecraftItems.BLACK_STAINED_GLASS_WALL);
        rainbowWall("Terracotta", MinecraftItems.WHITE_TERRACOTTA_WALL, MinecraftItems.ORANGE_TERRACOTTA_WALL, MinecraftItems.MAGENTA_TERRACOTTA_WALL, MinecraftItems.LIGHT_BLUE_TERRACOTTA_WALL, MinecraftItems.YELLOW_TERRACOTTA_WALL, MinecraftItems.LIME_TERRACOTTA_WALL, MinecraftItems.PINK_TERRACOTTA_WALL, MinecraftItems.GRAY_TERRACOTTA_WALL, MinecraftItems.LIGHT_GRAY_TERRACOTTA_WALL, MinecraftItems.CYAN_TERRACOTTA_WALL, MinecraftItems.PURPLE_TERRACOTTA_WALL, MinecraftItems.BLUE_TERRACOTTA_WALL, MinecraftItems.BROWN_TERRACOTTA_WALL, MinecraftItems.GREEN_TERRACOTTA_WALL, MinecraftItems.RED_TERRACOTTA_WALL, MinecraftItems.BLACK_TERRACOTTA_WALL);
        rainbowWall("Wool", MinecraftItems.WHITE_WOOL_WALL, MinecraftItems.ORANGE_WOOL_WALL, MinecraftItems.MAGENTA_WOOL_WALL, MinecraftItems.LIGHT_BLUE_WOOL_WALL, MinecraftItems.YELLOW_WOOL_WALL, MinecraftItems.LIME_WOOL_WALL, MinecraftItems.PINK_WOOL_WALL, MinecraftItems.GRAY_WOOL_WALL, MinecraftItems.LIGHT_GRAY_WOOL_WALL, MinecraftItems.CYAN_WOOL_WALL, MinecraftItems.PURPLE_WOOL_WALL, MinecraftItems.BLUE_WOOL_WALL, MinecraftItems.BROWN_WOOL_WALL, MinecraftItems.GREEN_WOOL_WALL, MinecraftItems.RED_WOOL_WALL, MinecraftItems.BLACK_WOOL_WALL);
        wall(MinecraftItems.DIRT_WALL, "Dirt");
        wall(MinecraftItems.COARSE_DIRT_WALL, "Coarse Dirt");
        wall(MinecraftItems.PODZOL_WALL, "Podzol");
        wall(MinecraftItems.BEDROCK_WALL, "Bedrock");
        wall(MinecraftItems.SAND_WALL, "Sand");
        wall(MinecraftItems.RED_SAND_WALL, "Red Sand");
        wall(MinecraftItems.GRAVEL_WALL, "Gravel");
        wall(MinecraftItems.GOLD_ORE_WALL, "Gold Ore");
        wall(MinecraftItems.IRON_ORE_WALL, "Iron Ore");
        wall(MinecraftItems.COAL_ORE_WALL, "Coal Ore");
        wall(MinecraftItems.SPONGE_WALL, "Sponge");
        wall(MinecraftItems.WET_SPONGE_WALL, "Wet Sponge");
        wall(MinecraftItems.GLASS_WALL, "Glass");
        wall(MinecraftItems.LAPIS_ORE_WALL, "Lapis Ore");
        wall(MinecraftItems.LAPIS_BLOCK_WALL, "Lapis Block");
        wall(MinecraftItems.CHISELED_SANDSTONE_WALL, "Chiseled Sandstone");
        wall(MinecraftItems.GOLD_BLOCK_WALL, "Gold Block");
        wall(MinecraftItems.IRON_BLOCK_WALL, "Iron Block");
        wall(MinecraftItems.BOOKSHELF_WALL, "Bookshelf");
        wall(MinecraftItems.OBSIDIAN_WALL, "Obsidian");
        wall(MinecraftItems.PURPUR_PILLAR_WALL, "Purpur Pillar");
        wall(MinecraftItems.DIAMOND_ORE_WALL, "Diamond Ore");
        wall(MinecraftItems.DIAMOND_BLOCK_WALL, "Diamond Block");
        wall(MinecraftItems.REDSTONE_ORE_WALL, "Redstone Ore");
        wall(MinecraftItems.ICE_WALL, "Ice");
        wall(MinecraftItems.SNOW_WALL, "Snow");
        wall(MinecraftItems.CLAY_WALL, "Clay");
        wall(MinecraftItems.PUMPKIN_WALL, "Pumpkin");
        wall(MinecraftItems.NETHERRACK_WALL, "Netherrack");
        wall(MinecraftItems.SOUL_SAND_WALL, "Soul Sand");
        wall(MinecraftItems.GLOWSTONE_WALL, "Glowstone");
        wall(MinecraftItems.CRACKED_STONE_BRICK_WALL, "Cracked Stone Brick");
        wall(MinecraftItems.CHISELED_STONE_BRICK_WALL, "Chiseled Stone Brick");
        wall(MinecraftItems.BROWN_MUSHROOM_WALL, "Brown Mushroom");
        wall(MinecraftItems.RED_MUSHROOM_WALL, "Red Mushroom");
        wall(MinecraftItems.MUSHROOM_STEM_WALL, "Mushroom Stem");
        wall(MinecraftItems.MELON_WALL, "Melon");
        wall(MinecraftItems.MYCELIUM_WALL, "Mycelium");
        wall(MinecraftItems.END_STONE_WALL, "End Stone");
        wall(MinecraftItems.EMERALD_ORE_WALL, "Emerald Ore");
        wall(MinecraftItems.EMERALD_BLOCK_WALL, "Emerald Block");
        wall(MinecraftItems.REDSTONE_BLOCK_WALL, "Redstone Block");
        wall(MinecraftItems.NETHER_QUARTZ_ORE_WALL, "Nether Quartz Ore");
        wall(MinecraftItems.CHISELED_QUARTZ_WALL, "Chiseled Quartz");
        wall(MinecraftItems.QUARTZ_PILLAR_WALL, "Quartz Pillar");
        wall(MinecraftItems.HAY_WALL, "Hay");
        wall(MinecraftItems.TERRACOTTA_WALL, "Terracotta");
        wall(MinecraftItems.COAL_WALL, "Coal");
        wall(MinecraftItems.PACKED_ICE_WALL, "Packed Ice");
        wall(MinecraftItems.SLIME_WALL, "Slime");
        wall(MinecraftItems.SEA_LANTERN_WALL, "Sea Lantern");
        wall(MinecraftItems.CHISELED_RED_SANDSTONE_WALL, "Chiseled Red Sandstone");
        wall(MinecraftItems.MAGMA_WALL, "Magma");
        wall(MinecraftItems.NETHER_WART_WALL, "Nether Wart");
        wall(MinecraftItems.BONE_WALL, "Bone");
        wall(MinecraftItems.DEAD_TUBE_CORAL_WALL, "Dead Tube Coral");
        wall(MinecraftItems.DEAD_BRAIN_CORAL_WALL, "Dead Brain Coral");
        wall(MinecraftItems.DEAD_BUBBLE_CORAL_WALL, "Dead Bubble Coral");
        wall(MinecraftItems.DEAD_FIRE_CORAL_WALL, "Dead Fire Coral");
        wall(MinecraftItems.DEAD_HORN_CORAL_WALL, "Dead Horn Coral");
        wall(MinecraftItems.TUBE_CORAL_WALL, "Tube Coral");
        wall(MinecraftItems.BRAIN_CORAL_WALL, "Brain Coral");
        wall(MinecraftItems.BUBBLE_CORAL_WALL, "Bubble Coral");
        wall(MinecraftItems.FIRE_CORAL_WALL, "Fire Coral");
        wall(MinecraftItems.HORN_CORAL_WALL, "Horn Coral");
        wall(MinecraftItems.DRIED_KELP_WALL, "Dried Kelp");
        wall(MinecraftItems.HONEY_WALL, "Honey");
        wall(MinecraftItems.HONEYCOMB_WALL, "Honeycomb");
        vertSlab(MinecraftItems.OAK_PLANK_VERTICAL_SLAB, "Oak Plank");
        vertSlab(MinecraftItems.SPRUCE_PLANK_VERTICAL_SLAB, "Spruce Plank");
        vertSlab(MinecraftItems.BIRCH_PLANK_VERTICAL_SLAB, "Birch Plank");
        vertSlab(MinecraftItems.JUNGLE_PLANK_VERTICAL_SLAB, "Jungle Plank");
        vertSlab(MinecraftItems.ACACIA_PLANK_VERTICAL_SLAB, "Acacia Plank");
        vertSlab(MinecraftItems.DARK_OAK_PLANK_VERTICAL_SLAB, "Dark Oak Plank");
        vertSlab(MinecraftItems.OAK_VERTICAL_SLAB, "Oak");
        vertSlab(MinecraftItems.SPRUCE_VERTICAL_SLAB, "Spruce");
        vertSlab(MinecraftItems.BIRCH_VERTICAL_SLAB, "Birch");
        vertSlab(MinecraftItems.JUNGLE_VERTICAL_SLAB, "Jungle");
        vertSlab(MinecraftItems.ACACIA_VERTICAL_SLAB, "Acacia");
        vertSlab(MinecraftItems.DARK_OAK_VERTICAL_SLAB, "Dark Oak");
        vertSlab(MinecraftItems.STRIPPED_OAK_VERTICAL_SLAB, "Stripped Oak");
        vertSlab(MinecraftItems.STRIPPED_SPRUCE_VERTICAL_SLAB, "Stripped Spruce");
        vertSlab(MinecraftItems.STRIPPED_BIRCH_VERTICAL_SLAB, "Stripped Birch");
        vertSlab(MinecraftItems.STRIPPED_JUNGLE_VERTICAL_SLAB, "Stripped Jungle");
        vertSlab(MinecraftItems.STRIPPED_ACACIA_VERTICAL_SLAB, "Stripped Acacia");
        vertSlab(MinecraftItems.STRIPPED_DARK_OAK_VERTICAL_SLAB, "Stripped Dark Oak");
        rainbowVertSlab("Concrete", MinecraftItems.WHITE_CONCRETE_VERTICAL_SLAB, MinecraftItems.ORANGE_CONCRETE_VERTICAL_SLAB, MinecraftItems.MAGENTA_CONCRETE_VERTICAL_SLAB, MinecraftItems.LIGHT_BLUE_CONCRETE_VERTICAL_SLAB, MinecraftItems.YELLOW_CONCRETE_VERTICAL_SLAB, MinecraftItems.LIME_CONCRETE_VERTICAL_SLAB, MinecraftItems.PINK_CONCRETE_VERTICAL_SLAB, MinecraftItems.GRAY_CONCRETE_VERTICAL_SLAB, MinecraftItems.LIGHT_GRAY_CONCRETE_VERTICAL_SLAB, MinecraftItems.CYAN_CONCRETE_VERTICAL_SLAB, MinecraftItems.PURPLE_CONCRETE_VERTICAL_SLAB, MinecraftItems.BLUE_CONCRETE_VERTICAL_SLAB, MinecraftItems.BROWN_CONCRETE_VERTICAL_SLAB, MinecraftItems.GREEN_CONCRETE_VERTICAL_SLAB, MinecraftItems.RED_CONCRETE_VERTICAL_SLAB, MinecraftItems.BLACK_CONCRETE_VERTICAL_SLAB);
        rainbowVertSlab("Concrete Powder", MinecraftItems.WHITE_CONCRETE_POWDER_VERTICAL_SLAB, MinecraftItems.ORANGE_CONCRETE_POWDER_VERTICAL_SLAB, MinecraftItems.MAGENTA_CONCRETE_POWDER_VERTICAL_SLAB, MinecraftItems.LIGHT_BLUE_CONCRETE_POWDER_VERTICAL_SLAB, MinecraftItems.YELLOW_CONCRETE_POWDER_VERTICAL_SLAB, MinecraftItems.LIME_CONCRETE_POWDER_VERTICAL_SLAB, MinecraftItems.PINK_CONCRETE_POWDER_VERTICAL_SLAB, MinecraftItems.GRAY_CONCRETE_POWDER_VERTICAL_SLAB, MinecraftItems.LIGHT_GRAY_CONCRETE_POWDER_VERTICAL_SLAB, MinecraftItems.CYAN_CONCRETE_POWDER_VERTICAL_SLAB, MinecraftItems.PURPLE_CONCRETE_POWDER_VERTICAL_SLAB, MinecraftItems.BLUE_CONCRETE_POWDER_VERTICAL_SLAB, MinecraftItems.BROWN_CONCRETE_POWDER_VERTICAL_SLAB, MinecraftItems.GREEN_CONCRETE_POWDER_VERTICAL_SLAB, MinecraftItems.RED_CONCRETE_POWDER_VERTICAL_SLAB, MinecraftItems.BLACK_CONCRETE_POWDER_VERTICAL_SLAB);
        rainbowVertSlab("Glazed Terracotta", MinecraftItems.WHITE_GLAZED_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.ORANGE_GLAZED_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.MAGENTA_GLAZED_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.LIGHT_BLUE_GLAZED_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.YELLOW_GLAZED_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.LIME_GLAZED_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.PINK_GLAZED_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.GRAY_GLAZED_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.LIGHT_GRAY_GLAZED_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.CYAN_GLAZED_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.PURPLE_GLAZED_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.BLUE_GLAZED_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.BROWN_GLAZED_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.GREEN_GLAZED_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.RED_GLAZED_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.BLACK_GLAZED_TERRACOTTA_VERTICAL_SLAB);
        rainbowVertSlab("Glass", MinecraftItems.WHITE_STAINED_GLASS_VERTICAL_SLAB, MinecraftItems.ORANGE_STAINED_GLASS_VERTICAL_SLAB, MinecraftItems.MAGENTA_STAINED_GLASS_VERTICAL_SLAB, MinecraftItems.LIGHT_BLUE_STAINED_GLASS_VERTICAL_SLAB, MinecraftItems.YELLOW_STAINED_GLASS_VERTICAL_SLAB, MinecraftItems.LIME_STAINED_GLASS_VERTICAL_SLAB, MinecraftItems.PINK_STAINED_GLASS_VERTICAL_SLAB, MinecraftItems.GRAY_STAINED_GLASS_VERTICAL_SLAB, MinecraftItems.LIGHT_GRAY_STAINED_GLASS_VERTICAL_SLAB, MinecraftItems.CYAN_STAINED_GLASS_VERTICAL_SLAB, MinecraftItems.PURPLE_STAINED_GLASS_VERTICAL_SLAB, MinecraftItems.BLUE_STAINED_GLASS_VERTICAL_SLAB, MinecraftItems.BROWN_STAINED_GLASS_VERTICAL_SLAB, MinecraftItems.GREEN_STAINED_GLASS_VERTICAL_SLAB, MinecraftItems.RED_STAINED_GLASS_VERTICAL_SLAB, MinecraftItems.BLACK_STAINED_GLASS_VERTICAL_SLAB);
        rainbowVertSlab("Terracotta", MinecraftItems.WHITE_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.ORANGE_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.MAGENTA_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.LIGHT_BLUE_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.YELLOW_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.LIME_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.PINK_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.GRAY_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.LIGHT_GRAY_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.CYAN_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.PURPLE_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.BLUE_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.BROWN_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.GREEN_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.RED_TERRACOTTA_VERTICAL_SLAB, MinecraftItems.BLACK_TERRACOTTA_VERTICAL_SLAB);
        rainbowVertSlab("Wool", MinecraftItems.WHITE_WOOL_VERTICAL_SLAB, MinecraftItems.ORANGE_WOOL_VERTICAL_SLAB, MinecraftItems.MAGENTA_WOOL_VERTICAL_SLAB, MinecraftItems.LIGHT_BLUE_WOOL_VERTICAL_SLAB, MinecraftItems.YELLOW_WOOL_VERTICAL_SLAB, MinecraftItems.LIME_WOOL_VERTICAL_SLAB, MinecraftItems.PINK_WOOL_VERTICAL_SLAB, MinecraftItems.GRAY_WOOL_VERTICAL_SLAB, MinecraftItems.LIGHT_GRAY_WOOL_VERTICAL_SLAB, MinecraftItems.CYAN_WOOL_VERTICAL_SLAB, MinecraftItems.PURPLE_WOOL_VERTICAL_SLAB, MinecraftItems.BLUE_WOOL_VERTICAL_SLAB, MinecraftItems.BROWN_WOOL_VERTICAL_SLAB, MinecraftItems.GREEN_WOOL_VERTICAL_SLAB, MinecraftItems.RED_WOOL_VERTICAL_SLAB, MinecraftItems.BLACK_WOOL_VERTICAL_SLAB);
        vertSlab(MinecraftItems.STONE_VERTICAL_SLAB, "Stone");
        vertSlab(MinecraftItems.GRANITE_VERTICAL_SLAB, "Granite");
        vertSlab(MinecraftItems.POLISHED_GRANITE_VERTICAL_SLAB, "Polished Granite");
        vertSlab(MinecraftItems.DIORITE_VERTICAL_SLAB, "Diorite");
        vertSlab(MinecraftItems.POLISHED_DIORITE_VERTICAL_SLAB, "Polished Diorite");
        vertSlab(MinecraftItems.ANDESITE_VERTICAL_SLAB, "Andesite");
        vertSlab(MinecraftItems.POLISHED_ANDESITE_VERTICAL_SLAB, "Polished Andesite");
        vertSlab(MinecraftItems.DIRT_VERTICAL_SLAB, "Dirt");
        vertSlab(MinecraftItems.COARSE_DIRT_VERTICAL_SLAB, "Coarse Dirt");
        vertSlab(MinecraftItems.PODZOL_VERTICAL_SLAB, "Podzol");
        vertSlab(MinecraftItems.COBBLESTONE_VERTICAL_SLAB, "Cobblestone");
        vertSlab(MinecraftItems.BEDROCK_VERTICAL_SLAB, "Bedrock");
        vertSlab(MinecraftItems.SAND_VERTICAL_SLAB, "Sand");
        vertSlab(MinecraftItems.RED_SAND_VERTICAL_SLAB, "Red Sand");
        vertSlab(MinecraftItems.GRAVEL_VERTICAL_SLAB, "Gravel");
        vertSlab(MinecraftItems.GOLD_ORE_VERTICAL_SLAB, "Gold Ore");
        vertSlab(MinecraftItems.IRON_ORE_VERTICAL_SLAB, "Iron Ore");
        vertSlab(MinecraftItems.COAL_ORE_VERTICAL_SLAB, "Coal Ore");
        vertSlab(MinecraftItems.SPONGE_VERTICAL_SLAB, "Sponge");
        vertSlab(MinecraftItems.WET_SPONGE_VERTICAL_SLAB, "Wet Sponge");
        vertSlab(MinecraftItems.GLASS_VERTICAL_SLAB, "Glass");
        vertSlab(MinecraftItems.LAPIS_ORE_VERTICAL_SLAB, "Lapis Ore");
        vertSlab(MinecraftItems.LAPIS_BLOCK_VERTICAL_SLAB, "Lapis Block");
        vertSlab(MinecraftItems.SANDSTONE_VERTICAL_SLAB, "Sandstone");
        vertSlab(MinecraftItems.CHISELED_SANDSTONE_VERTICAL_SLAB, "Chiseled Sandstone");
        vertSlab(MinecraftItems.CUT_SANDSTONE_VERTICAL_SLAB, "Cut Sandstone");
        vertSlab(MinecraftItems.GOLD_BLOCK_VERTICAL_SLAB, "Gold Block");
        vertSlab(MinecraftItems.IRON_BLOCK_VERTICAL_SLAB, "Iron Block");
        vertSlab(MinecraftItems.SMOOTH_QUARTZ_VERTICAL_SLAB, "Smooth Quartz");
        vertSlab(MinecraftItems.SMOOTH_RED_SANDSTONE_VERTICAL_SLAB, "Smooth Red Sandstone");
        vertSlab(MinecraftItems.SMOOTH_SANDSTONE_VERTICAL_SLAB, "Smooth Sandstone");
        vertSlab(MinecraftItems.SMOOTH_STONE_VERTICAL_SLAB, "Smooth Stone");
        vertSlab(MinecraftItems.BRICK_VERTICAL_SLAB, "Brick");
        vertSlab(MinecraftItems.BOOKSHELF_VERTICAL_SLAB, "Bookshelf");
        vertSlab(MinecraftItems.MOSSY_COBBLESTONE_VERTICAL_SLAB, "Mossy Cobblestone");
        vertSlab(MinecraftItems.OBSIDIAN_VERTICAL_SLAB, "Obsidian");
        vertSlab(MinecraftItems.PURPUR_VERTICAL_SLAB, "Purpur");
        vertSlab(MinecraftItems.PURPUR_PILLAR_VERTICAL_SLAB, "Purpur Pillar");
        vertSlab(MinecraftItems.DIAMOND_ORE_VERTICAL_SLAB, "Diamond Ore");
        vertSlab(MinecraftItems.DIAMOND_BLOCK_VERTICAL_SLAB, "Diamond Block");
        vertSlab(MinecraftItems.REDSTONE_ORE_VERTICAL_SLAB, "Redstone Ore");
        vertSlab(MinecraftItems.ICE_VERTICAL_SLAB, "Ice");
        vertSlab(MinecraftItems.SNOW_VERTICAL_SLAB, "Snow");
        vertSlab(MinecraftItems.CLAY_VERTICAL_SLAB, "Clay");
        vertSlab(MinecraftItems.PUMPKIN_VERTICAL_SLAB, "Pumpkin");
        vertSlab(MinecraftItems.NETHERRACK_VERTICAL_SLAB, "Netherrack");
        vertSlab(MinecraftItems.SOUL_SAND_VERTICAL_SLAB, "Soul Sand");
        vertSlab(MinecraftItems.GLOWSTONE_VERTICAL_SLAB, "Glowstone");
        vertSlab(MinecraftItems.STONE_BRICK_VERTICAL_SLAB, "Stone Brick");
        vertSlab(MinecraftItems.MOSSY_STONE_BRICK_VERTICAL_SLAB, "Mossy Stone Brick");
        vertSlab(MinecraftItems.CRACKED_STONE_BRICK_VERTICAL_SLAB, "Cracked Stone Brick");
        vertSlab(MinecraftItems.CHISELED_STONE_BRICK_VERTICAL_SLAB, "Chiseled Stone Brick");
        vertSlab(MinecraftItems.BROWN_MUSHROOM_VERTICAL_SLAB, "Brown Mushroom");
        vertSlab(MinecraftItems.RED_MUSHROOM_VERTICAL_SLAB, "Red Mushroom");
        vertSlab(MinecraftItems.MUSHROOM_STEM_VERTICAL_SLAB, "Mushroom Stem");
        vertSlab(MinecraftItems.MELON_VERTICAL_SLAB, "Melon");
        vertSlab(MinecraftItems.MYCELIUM_VERTICAL_SLAB, "Mycelium");
        vertSlab(MinecraftItems.NETHER_BRICK_VERTICAL_SLAB, "Nether Brick");
        vertSlab(MinecraftItems.END_STONE_VERTICAL_SLAB, "End Stone");
        vertSlab(MinecraftItems.END_STONE_BRICK_VERTICAL_SLAB, "End Stone Brick");
        vertSlab(MinecraftItems.EMERALD_ORE_VERTICAL_SLAB, "Emerald Ore");
        vertSlab(MinecraftItems.EMERALD_BLOCK_VERTICAL_SLAB, "Emerald Block");
        vertSlab(MinecraftItems.REDSTONE_BLOCK_VERTICAL_SLAB, "Redstone Block");
        vertSlab(MinecraftItems.QUARTZ_VERTICAL_SLAB, "Quartz");
        vertSlab(MinecraftItems.NETHER_QUARTZ_ORE_VERTICAL_SLAB, "Nether Quartz Ore");
        vertSlab(MinecraftItems.CHISELED_QUARTZ_VERTICAL_SLAB, "Chiseled Quartz");
        vertSlab(MinecraftItems.QUARTZ_PILLAR_VERTICAL_SLAB, "Quartz Pillar");
        vertSlab(MinecraftItems.HAY_VERTICAL_SLAB, "Hay");
        vertSlab(MinecraftItems.TERRACOTTA_VERTICAL_SLAB, "Terracotta");
        vertSlab(MinecraftItems.COAL_VERTICAL_SLAB, "Coal");
        vertSlab(MinecraftItems.PACKED_ICE_VERTICAL_SLAB, "Packed Ice");
        vertSlab(MinecraftItems.SLIME_VERTICAL_SLAB, "Slime");
        vertSlab(MinecraftItems.PRISMARINE_VERTICAL_SLAB, "Prismarine");
        vertSlab(MinecraftItems.PRISMARINE_BRICK_VERTICAL_SLAB, "Prismarine Brick");
        vertSlab(MinecraftItems.DARK_PRISMARINE_VERTICAL_SLAB, "Dark Prismarine");
        vertSlab(MinecraftItems.SEA_LANTERN_VERTICAL_SLAB, "Sea Lantern");
        vertSlab(MinecraftItems.RED_SANDSTONE_VERTICAL_SLAB, "Red Sandstone");
        vertSlab(MinecraftItems.CHISELED_RED_SANDSTONE_VERTICAL_SLAB, "Chiseled Red Sandstone");
        vertSlab(MinecraftItems.CUT_RED_SANDSTONE_VERTICAL_SLAB, "Cut Red Sandstone");
        vertSlab(MinecraftItems.MAGMA_VERTICAL_SLAB, "Magma");
        vertSlab(MinecraftItems.NETHER_WART_VERTICAL_SLAB, "Nether Wart");
        vertSlab(MinecraftItems.RED_NETHER_BRICK_VERTICAL_SLAB, "Red Nether Brick");
        vertSlab(MinecraftItems.BONE_VERTICAL_SLAB, "Bone");
        vertSlab(MinecraftItems.DEAD_TUBE_CORAL_VERTICAL_SLAB, "Dead Tube Coral");
        vertSlab(MinecraftItems.DEAD_BRAIN_CORAL_VERTICAL_SLAB, "Dead Brain Coral");
        vertSlab(MinecraftItems.DEAD_BUBBLE_CORAL_VERTICAL_SLAB, "Dead Bubble Coral");
        vertSlab(MinecraftItems.DEAD_FIRE_CORAL_VERTICAL_SLAB, "Dead Fire Coral");
        vertSlab(MinecraftItems.DEAD_HORN_CORAL_VERTICAL_SLAB, "Dead Horn Coral");
        vertSlab(MinecraftItems.TUBE_CORAL_VERTICAL_SLAB, "Tube Coral");
        vertSlab(MinecraftItems.BRAIN_CORAL_VERTICAL_SLAB, "Brain Coral");
        vertSlab(MinecraftItems.BUBBLE_CORAL_VERTICAL_SLAB, "Bubble Coral");
        vertSlab(MinecraftItems.FIRE_CORAL_VERTICAL_SLAB, "Fire Coral");
        vertSlab(MinecraftItems.HORN_CORAL_VERTICAL_SLAB, "Horn Coral");
        vertSlab(MinecraftItems.DRIED_KELP_VERTICAL_SLAB, "Dried Kelp");
        vertSlab(MinecraftItems.HONEY_VERTICAL_SLAB, "Honey");
        vertSlab(MinecraftItems.HONEYCOMB_VERTICAL_SLAB, "Honeycomb");
        vertStairs(MinecraftItems.OAK_PLANK_VERTICAL_STAIRS, "Oak Plank");
        vertStairs(MinecraftItems.SPRUCE_PLANK_VERTICAL_STAIRS, "Spruce Plank");
        vertStairs(MinecraftItems.BIRCH_PLANK_VERTICAL_STAIRS, "Birch Plank");
        vertStairs(MinecraftItems.JUNGLE_PLANK_VERTICAL_STAIRS, "Jungle Plank");
        vertStairs(MinecraftItems.ACACIA_PLANK_VERTICAL_STAIRS, "Acacia Plank");
        vertStairs(MinecraftItems.DARK_OAK_PLANK_VERTICAL_STAIRS, "Dark Oak Plank");
        vertStairs(MinecraftItems.OAK_VERTICAL_STAIRS, "Oak");
        vertStairs(MinecraftItems.SPRUCE_VERTICAL_STAIRS, "Spruce");
        vertStairs(MinecraftItems.BIRCH_VERTICAL_STAIRS, "Birch");
        vertStairs(MinecraftItems.JUNGLE_VERTICAL_STAIRS, "Jungle");
        vertStairs(MinecraftItems.ACACIA_VERTICAL_STAIRS, "Acacia");
        vertStairs(MinecraftItems.DARK_OAK_VERTICAL_STAIRS, "Dark Oak");
        vertStairs(MinecraftItems.STRIPPED_OAK_VERTICAL_STAIRS, "Stripped Oak");
        vertStairs(MinecraftItems.STRIPPED_SPRUCE_VERTICAL_STAIRS, "Stripped Spruce");
        vertStairs(MinecraftItems.STRIPPED_BIRCH_VERTICAL_STAIRS, "Stripped Birch");
        vertStairs(MinecraftItems.STRIPPED_JUNGLE_VERTICAL_STAIRS, "Stripped Jungle");
        vertStairs(MinecraftItems.STRIPPED_ACACIA_VERTICAL_STAIRS, "Stripped Acacia");
        vertStairs(MinecraftItems.STRIPPED_DARK_OAK_VERTICAL_STAIRS, "Stripped Dark Oak");
        rainbowVertStairs("Concrete", MinecraftItems.WHITE_CONCRETE_VERTICAL_STAIRS, MinecraftItems.ORANGE_CONCRETE_VERTICAL_STAIRS, MinecraftItems.MAGENTA_CONCRETE_VERTICAL_STAIRS, MinecraftItems.LIGHT_BLUE_CONCRETE_VERTICAL_STAIRS, MinecraftItems.YELLOW_CONCRETE_VERTICAL_STAIRS, MinecraftItems.LIME_CONCRETE_VERTICAL_STAIRS, MinecraftItems.PINK_CONCRETE_VERTICAL_STAIRS, MinecraftItems.GRAY_CONCRETE_VERTICAL_STAIRS, MinecraftItems.LIGHT_GRAY_CONCRETE_VERTICAL_STAIRS, MinecraftItems.CYAN_CONCRETE_VERTICAL_STAIRS, MinecraftItems.PURPLE_CONCRETE_VERTICAL_STAIRS, MinecraftItems.BLUE_CONCRETE_VERTICAL_STAIRS, MinecraftItems.BROWN_CONCRETE_VERTICAL_STAIRS, MinecraftItems.GREEN_CONCRETE_VERTICAL_STAIRS, MinecraftItems.RED_CONCRETE_VERTICAL_STAIRS, MinecraftItems.BLACK_CONCRETE_VERTICAL_STAIRS);
        rainbowVertStairs("Concrete Powder", MinecraftItems.WHITE_CONCRETE_POWDER_VERTICAL_STAIRS, MinecraftItems.ORANGE_CONCRETE_POWDER_VERTICAL_STAIRS, MinecraftItems.MAGENTA_CONCRETE_POWDER_VERTICAL_STAIRS, MinecraftItems.LIGHT_BLUE_CONCRETE_POWDER_VERTICAL_STAIRS, MinecraftItems.YELLOW_CONCRETE_POWDER_VERTICAL_STAIRS, MinecraftItems.LIME_CONCRETE_POWDER_VERTICAL_STAIRS, MinecraftItems.PINK_CONCRETE_POWDER_VERTICAL_STAIRS, MinecraftItems.GRAY_CONCRETE_POWDER_VERTICAL_STAIRS, MinecraftItems.LIGHT_GRAY_CONCRETE_POWDER_VERTICAL_STAIRS, MinecraftItems.CYAN_CONCRETE_POWDER_VERTICAL_STAIRS, MinecraftItems.PURPLE_CONCRETE_POWDER_VERTICAL_STAIRS, MinecraftItems.BLUE_CONCRETE_POWDER_VERTICAL_STAIRS, MinecraftItems.BROWN_CONCRETE_POWDER_VERTICAL_STAIRS, MinecraftItems.GREEN_CONCRETE_POWDER_VERTICAL_STAIRS, MinecraftItems.RED_CONCRETE_POWDER_VERTICAL_STAIRS, MinecraftItems.BLACK_CONCRETE_POWDER_VERTICAL_STAIRS);
        rainbowVertStairs("Glazed Terracotta", MinecraftItems.WHITE_GLAZED_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.ORANGE_GLAZED_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.MAGENTA_GLAZED_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.LIGHT_BLUE_GLAZED_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.YELLOW_GLAZED_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.LIME_GLAZED_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.PINK_GLAZED_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.GRAY_GLAZED_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.LIGHT_GRAY_GLAZED_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.CYAN_GLAZED_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.PURPLE_GLAZED_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.BLUE_GLAZED_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.BROWN_GLAZED_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.GREEN_GLAZED_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.RED_GLAZED_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.BLACK_GLAZED_TERRACOTTA_VERTICAL_STAIRS);
        rainbowVertStairs("Glass", MinecraftItems.WHITE_STAINED_GLASS_VERTICAL_STAIRS, MinecraftItems.ORANGE_STAINED_GLASS_VERTICAL_STAIRS, MinecraftItems.MAGENTA_STAINED_GLASS_VERTICAL_STAIRS, MinecraftItems.LIGHT_BLUE_STAINED_GLASS_VERTICAL_STAIRS, MinecraftItems.YELLOW_STAINED_GLASS_VERTICAL_STAIRS, MinecraftItems.LIME_STAINED_GLASS_VERTICAL_STAIRS, MinecraftItems.PINK_STAINED_GLASS_VERTICAL_STAIRS, MinecraftItems.GRAY_STAINED_GLASS_VERTICAL_STAIRS, MinecraftItems.LIGHT_GRAY_STAINED_GLASS_VERTICAL_STAIRS, MinecraftItems.CYAN_STAINED_GLASS_VERTICAL_STAIRS, MinecraftItems.PURPLE_STAINED_GLASS_VERTICAL_STAIRS, MinecraftItems.BLUE_STAINED_GLASS_VERTICAL_STAIRS, MinecraftItems.BROWN_STAINED_GLASS_VERTICAL_STAIRS, MinecraftItems.GREEN_STAINED_GLASS_VERTICAL_STAIRS, MinecraftItems.RED_STAINED_GLASS_VERTICAL_STAIRS, MinecraftItems.BLACK_STAINED_GLASS_VERTICAL_STAIRS);
        rainbowVertStairs("Terracotta", MinecraftItems.WHITE_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.ORANGE_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.MAGENTA_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.LIGHT_BLUE_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.YELLOW_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.LIME_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.PINK_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.GRAY_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.LIGHT_GRAY_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.CYAN_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.PURPLE_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.BLUE_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.BROWN_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.GREEN_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.RED_TERRACOTTA_VERTICAL_STAIRS, MinecraftItems.BLACK_TERRACOTTA_VERTICAL_STAIRS);
        rainbowVertStairs("Wool", MinecraftItems.WHITE_WOOL_VERTICAL_STAIRS, MinecraftItems.ORANGE_WOOL_VERTICAL_STAIRS, MinecraftItems.MAGENTA_WOOL_VERTICAL_STAIRS, MinecraftItems.LIGHT_BLUE_WOOL_VERTICAL_STAIRS, MinecraftItems.YELLOW_WOOL_VERTICAL_STAIRS, MinecraftItems.LIME_WOOL_VERTICAL_STAIRS, MinecraftItems.PINK_WOOL_VERTICAL_STAIRS, MinecraftItems.GRAY_WOOL_VERTICAL_STAIRS, MinecraftItems.LIGHT_GRAY_WOOL_VERTICAL_STAIRS, MinecraftItems.CYAN_WOOL_VERTICAL_STAIRS, MinecraftItems.PURPLE_WOOL_VERTICAL_STAIRS, MinecraftItems.BLUE_WOOL_VERTICAL_STAIRS, MinecraftItems.BROWN_WOOL_VERTICAL_STAIRS, MinecraftItems.GREEN_WOOL_VERTICAL_STAIRS, MinecraftItems.RED_WOOL_VERTICAL_STAIRS, MinecraftItems.BLACK_WOOL_VERTICAL_STAIRS);
        vertStairs(MinecraftItems.STONE_VERTICAL_STAIRS, "Stone");
        vertStairs(MinecraftItems.GRANITE_VERTICAL_STAIRS, "Granite");
        vertStairs(MinecraftItems.POLISHED_GRANITE_VERTICAL_STAIRS, "Polished Granite");
        vertStairs(MinecraftItems.DIORITE_VERTICAL_STAIRS, "Diorite");
        vertStairs(MinecraftItems.POLISHED_DIORITE_VERTICAL_STAIRS, "Polished Diorite");
        vertStairs(MinecraftItems.ANDESITE_VERTICAL_STAIRS, "Andesite");
        vertStairs(MinecraftItems.POLISHED_ANDESITE_VERTICAL_STAIRS, "Polished Andesite");
        vertStairs(MinecraftItems.DIRT_VERTICAL_STAIRS, "Dirt");
        vertStairs(MinecraftItems.COARSE_DIRT_VERTICAL_STAIRS, "Coarse Dirt");
        vertStairs(MinecraftItems.PODZOL_VERTICAL_STAIRS, "Podzol");
        vertStairs(MinecraftItems.COBBLESTONE_VERTICAL_STAIRS, "Cobblestone");
        vertStairs(MinecraftItems.BEDROCK_VERTICAL_STAIRS, "Bedrock");
        vertStairs(MinecraftItems.SAND_VERTICAL_STAIRS, "Sand");
        vertStairs(MinecraftItems.RED_SAND_VERTICAL_STAIRS, "Red Sand");
        vertStairs(MinecraftItems.GRAVEL_VERTICAL_STAIRS, "Gravel");
        vertStairs(MinecraftItems.GOLD_ORE_VERTICAL_STAIRS, "Gold Ore");
        vertStairs(MinecraftItems.IRON_ORE_VERTICAL_STAIRS, "Iron Ore");
        vertStairs(MinecraftItems.COAL_ORE_VERTICAL_STAIRS, "Coal Ore");
        vertStairs(MinecraftItems.SPONGE_VERTICAL_STAIRS, "Sponge");
        vertStairs(MinecraftItems.WET_SPONGE_VERTICAL_STAIRS, "Wet Sponge");
        vertStairs(MinecraftItems.GLASS_VERTICAL_STAIRS, "Glass");
        vertStairs(MinecraftItems.LAPIS_ORE_VERTICAL_STAIRS, "Lapis Ore");
        vertStairs(MinecraftItems.LAPIS_BLOCK_VERTICAL_STAIRS, "Lapis Block");
        vertStairs(MinecraftItems.SANDSTONE_VERTICAL_STAIRS, "Sandstone");
        vertStairs(MinecraftItems.CHISELED_SANDSTONE_VERTICAL_STAIRS, "Chiseled Sandstone");
        vertStairs(MinecraftItems.CUT_SANDSTONE_VERTICAL_STAIRS, "Cut Sandstone");
        vertStairs(MinecraftItems.GOLD_BLOCK_VERTICAL_STAIRS, "Gold Block");
        vertStairs(MinecraftItems.IRON_BLOCK_VERTICAL_STAIRS, "Iron Block");
        vertStairs(MinecraftItems.SMOOTH_QUARTZ_VERTICAL_STAIRS, "Smooth Quartz");
        vertStairs(MinecraftItems.SMOOTH_RED_SANDSTONE_VERTICAL_STAIRS, "Smooth Red Sandstone");
        vertStairs(MinecraftItems.SMOOTH_SANDSTONE_VERTICAL_STAIRS, "Smooth Sandstone");
        vertStairs(MinecraftItems.SMOOTH_STONE_VERTICAL_STAIRS, "Smooth Stone");
        vertStairs(MinecraftItems.BRICK_VERTICAL_STAIRS, "Brick");
        vertStairs(MinecraftItems.BOOKSHELF_VERTICAL_STAIRS, "Bookshelf");
        vertStairs(MinecraftItems.MOSSY_COBBLESTONE_VERTICAL_STAIRS, "Mossy Cobblestone");
        vertStairs(MinecraftItems.OBSIDIAN_VERTICAL_STAIRS, "Obsidian");
        vertStairs(MinecraftItems.PURPUR_VERTICAL_STAIRS, "Purpur");
        vertStairs(MinecraftItems.PURPUR_PILLAR_VERTICAL_STAIRS, "Purpur Pillar");
        vertStairs(MinecraftItems.DIAMOND_ORE_VERTICAL_STAIRS, "Diamond Ore");
        vertStairs(MinecraftItems.DIAMOND_BLOCK_VERTICAL_STAIRS, "Diamond Block");
        vertStairs(MinecraftItems.REDSTONE_ORE_VERTICAL_STAIRS, "Redstone Ore");
        vertStairs(MinecraftItems.ICE_VERTICAL_STAIRS, "Ice");
        vertStairs(MinecraftItems.SNOW_VERTICAL_STAIRS, "Snow");
        vertStairs(MinecraftItems.CLAY_VERTICAL_STAIRS, "Clay");
        vertStairs(MinecraftItems.PUMPKIN_VERTICAL_STAIRS, "Pumpkin");
        vertStairs(MinecraftItems.NETHERRACK_VERTICAL_STAIRS, "Netherrack");
        vertStairs(MinecraftItems.SOUL_SAND_VERTICAL_STAIRS, "Soul Sand");
        vertStairs(MinecraftItems.GLOWSTONE_VERTICAL_STAIRS, "Glowstone");
        vertStairs(MinecraftItems.STONE_BRICK_VERTICAL_STAIRS, "Stone Brick");
        vertStairs(MinecraftItems.MOSSY_STONE_BRICK_VERTICAL_STAIRS, "Mossy Stone Brick");
        vertStairs(MinecraftItems.CRACKED_STONE_BRICK_VERTICAL_STAIRS, "Cracked Stone Brick");
        vertStairs(MinecraftItems.CHISELED_STONE_BRICK_VERTICAL_STAIRS, "Chiseled Stone Brick");
        vertStairs(MinecraftItems.BROWN_MUSHROOM_VERTICAL_STAIRS, "Brown Mushroom");
        vertStairs(MinecraftItems.RED_MUSHROOM_VERTICAL_STAIRS, "Red Mushroom");
        vertStairs(MinecraftItems.MUSHROOM_STEM_VERTICAL_STAIRS, "Mushroom Stem");
        vertStairs(MinecraftItems.MELON_VERTICAL_STAIRS, "Melon");
        vertStairs(MinecraftItems.MYCELIUM_VERTICAL_STAIRS, "Mycelium");
        vertStairs(MinecraftItems.NETHER_BRICK_VERTICAL_STAIRS, "Nether Brick");
        vertStairs(MinecraftItems.END_STONE_VERTICAL_STAIRS, "End Stone");
        vertStairs(MinecraftItems.END_STONE_BRICK_VERTICAL_STAIRS, "End Stone Brick");
        vertStairs(MinecraftItems.EMERALD_ORE_VERTICAL_STAIRS, "Emerald Ore");
        vertStairs(MinecraftItems.EMERALD_BLOCK_VERTICAL_STAIRS, "Emerald Block");
        vertStairs(MinecraftItems.REDSTONE_BLOCK_VERTICAL_STAIRS, "Redstone Block");
        vertStairs(MinecraftItems.QUARTZ_VERTICAL_STAIRS, "Quartz");
        vertStairs(MinecraftItems.NETHER_QUARTZ_ORE_VERTICAL_STAIRS, "Nether Quartz Ore");
        vertStairs(MinecraftItems.CHISELED_QUARTZ_VERTICAL_STAIRS, "Chiseled Quartz");
        vertStairs(MinecraftItems.QUARTZ_PILLAR_VERTICAL_STAIRS, "Quartz Pillar");
        vertStairs(MinecraftItems.HAY_VERTICAL_STAIRS, "Hay");
        vertStairs(MinecraftItems.TERRACOTTA_VERTICAL_STAIRS, "Terracotta");
        vertStairs(MinecraftItems.COAL_VERTICAL_STAIRS, "Coal");
        vertStairs(MinecraftItems.PACKED_ICE_VERTICAL_STAIRS, "Packed Ice");
        vertStairs(MinecraftItems.SLIME_VERTICAL_STAIRS, "Slime");
        vertStairs(MinecraftItems.PRISMARINE_VERTICAL_STAIRS, "Prismarine");
        vertStairs(MinecraftItems.PRISMARINE_BRICK_VERTICAL_STAIRS, "Prismarine Brick");
        vertStairs(MinecraftItems.DARK_PRISMARINE_VERTICAL_STAIRS, "Dark Prismarine");
        vertStairs(MinecraftItems.SEA_LANTERN_VERTICAL_STAIRS, "Sea Lantern");
        vertStairs(MinecraftItems.RED_SANDSTONE_VERTICAL_STAIRS, "Red Sandstone");
        vertStairs(MinecraftItems.CHISELED_RED_SANDSTONE_VERTICAL_STAIRS, "Chiseled Red Sandstone");
        vertStairs(MinecraftItems.CUT_RED_SANDSTONE_VERTICAL_STAIRS, "Cut Red Sandstone");
        vertStairs(MinecraftItems.MAGMA_VERTICAL_STAIRS, "Magma");
        vertStairs(MinecraftItems.NETHER_WART_VERTICAL_STAIRS, "Nether Wart");
        vertStairs(MinecraftItems.RED_NETHER_BRICK_VERTICAL_STAIRS, "Red Nether Brick");
        vertStairs(MinecraftItems.BONE_VERTICAL_STAIRS, "Bone");
        vertStairs(MinecraftItems.DEAD_TUBE_CORAL_VERTICAL_STAIRS, "Dead Tube Coral");
        vertStairs(MinecraftItems.DEAD_BRAIN_CORAL_VERTICAL_STAIRS, "Dead Brain Coral");
        vertStairs(MinecraftItems.DEAD_BUBBLE_CORAL_VERTICAL_STAIRS, "Dead Bubble Coral");
        vertStairs(MinecraftItems.DEAD_FIRE_CORAL_VERTICAL_STAIRS, "Dead Fire Coral");
        vertStairs(MinecraftItems.DEAD_HORN_CORAL_VERTICAL_STAIRS, "Dead Horn Coral");
        vertStairs(MinecraftItems.TUBE_CORAL_VERTICAL_STAIRS, "Tube Coral");
        vertStairs(MinecraftItems.BRAIN_CORAL_VERTICAL_STAIRS, "Brain Coral");
        vertStairs(MinecraftItems.BUBBLE_CORAL_VERTICAL_STAIRS, "Bubble Coral");
        vertStairs(MinecraftItems.FIRE_CORAL_VERTICAL_STAIRS, "Fire Coral");
        vertStairs(MinecraftItems.HORN_CORAL_VERTICAL_STAIRS, "Horn Coral");
        vertStairs(MinecraftItems.DRIED_KELP_VERTICAL_STAIRS, "Dried Kelp");
        vertStairs(MinecraftItems.HONEY_VERTICAL_STAIRS, "Honey");
        vertStairs(MinecraftItems.HONEYCOMB_VERTICAL_STAIRS, "Honeycomb");
    }
}
