package ihh.slabsstairswalls.minecraft;

import ihh.slabsstairswalls.RecipeGen;
import java.util.function.Consumer;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.IFinishedRecipe;
import net.minecraft.item.Items;
import net.minecraftforge.common.Tags;

public final class MinecraftRecipes extends RecipeGen {
    public MinecraftRecipes(DataGenerator g) {
        super(g);
    }

    @Override
    protected void registerRecipes(Consumer<IFinishedRecipe> c) {
        fenceGateRecipe(MinecraftItems.NETHER_BRICK_FENCE_GATE, () -> Items.NETHER_BRICKS, Tags.Items.INGOTS_NETHER_BRICK, c);
        stairsRecipe(MinecraftItems.CUT_RED_SANDSTONE_STAIRS, () -> Items.CUT_RED_SANDSTONE, true, c);
        stairsRecipe(MinecraftItems.CUT_SANDSTONE_STAIRS, () -> Items.CUT_SANDSTONE, true, c);
        stairsRecipe(MinecraftItems.SMOOTH_STONE_STAIRS, () -> Items.SMOOTH_STONE, true, c);
        wallRecipe(MinecraftItems.CUT_RED_SANDSTONE_WALL, () -> Items.CUT_RED_SANDSTONE, true, c);
        wallRecipe(MinecraftItems.CUT_SANDSTONE_WALL, () -> Items.CUT_SANDSTONE, true, c);
        wallRecipe(MinecraftItems.DARK_PRISMARINE_WALL, () -> Items.DARK_PRISMARINE, true, c);
        wallRecipe(MinecraftItems.PRISMARINE_BRICK_WALL, () -> Items.PRISMARINE_BRICKS, true, c);
        wallRecipe(MinecraftItems.POLISHED_ANDESITE_WALL, () -> Items.POLISHED_ANDESITE, true, c);
        wallRecipe(MinecraftItems.POLISHED_DIORITE_WALL, () -> Items.POLISHED_DIORITE, true, c);
        wallRecipe(MinecraftItems.POLISHED_GRANITE_WALL, () -> Items.POLISHED_GRANITE, true, c);
        wallRecipe(MinecraftItems.PURPUR_WALL, () -> Items.PURPUR_BLOCK, true, c);
        wallRecipe(MinecraftItems.QUARTZ_WALL, () -> Items.QUARTZ_BLOCK, true, c);
        wallRecipe(MinecraftItems.SMOOTH_QUARTZ_WALL, () -> Items.SMOOTH_QUARTZ, true, c);
        wallRecipe(MinecraftItems.SMOOTH_RED_SANDSTONE_WALL, () -> Items.SMOOTH_RED_SANDSTONE, true, c);
        wallRecipe(MinecraftItems.SMOOTH_SANDSTONE_WALL, () -> Items.SMOOTH_SANDSTONE, true, c);
        wallRecipe(MinecraftItems.SMOOTH_STONE_WALL, () -> Items.SMOOTH_STONE, true, c);
        wallRecipe(MinecraftItems.STONE_WALL, () -> Items.STONE, true, c);
        slabStairsWallRecipe(MinecraftItems.OAK_SLAB, MinecraftItems.OAK_STAIRS, MinecraftItems.OAK_WALL, () -> Items.OAK_WOOD, false, c);
        slabStairsWallRecipe(MinecraftItems.SPRUCE_SLAB, MinecraftItems.SPRUCE_STAIRS, MinecraftItems.SPRUCE_WALL, () -> Items.SPRUCE_WOOD, false, c);
        slabStairsWallRecipe(MinecraftItems.BIRCH_SLAB, MinecraftItems.BIRCH_STAIRS, MinecraftItems.BIRCH_WALL, () -> Items.BIRCH_WOOD, false, c);
        slabStairsWallRecipe(MinecraftItems.JUNGLE_SLAB, MinecraftItems.JUNGLE_STAIRS, MinecraftItems.JUNGLE_WALL, () -> Items.JUNGLE_WOOD, false, c);
        slabStairsWallRecipe(MinecraftItems.ACACIA_SLAB, MinecraftItems.ACACIA_STAIRS, MinecraftItems.ACACIA_WALL, () -> Items.ACACIA_WOOD, false, c);
        slabStairsWallRecipe(MinecraftItems.DARK_OAK_SLAB, MinecraftItems.DARK_OAK_STAIRS, MinecraftItems.DARK_OAK_WALL, () -> Items.DARK_OAK_WOOD, false, c);
        slabStairsWallRecipe(MinecraftItems.STRIPPED_OAK_SLAB, MinecraftItems.STRIPPED_OAK_STAIRS, MinecraftItems.STRIPPED_OAK_WALL, () -> Items.STRIPPED_OAK_WOOD, false, c);
        slabStairsWallRecipe(MinecraftItems.STRIPPED_SPRUCE_SLAB, MinecraftItems.STRIPPED_SPRUCE_STAIRS, MinecraftItems.STRIPPED_SPRUCE_WALL, () -> Items.STRIPPED_SPRUCE_WOOD, false, c);
        slabStairsWallRecipe(MinecraftItems.STRIPPED_BIRCH_SLAB, MinecraftItems.STRIPPED_BIRCH_STAIRS, MinecraftItems.STRIPPED_BIRCH_WALL, () -> Items.STRIPPED_BIRCH_WOOD, false, c);
        slabStairsWallRecipe(MinecraftItems.STRIPPED_JUNGLE_SLAB, MinecraftItems.STRIPPED_JUNGLE_STAIRS, MinecraftItems.STRIPPED_JUNGLE_WALL, () -> Items.STRIPPED_JUNGLE_WOOD, false, c);
        slabStairsWallRecipe(MinecraftItems.STRIPPED_ACACIA_SLAB, MinecraftItems.STRIPPED_ACACIA_STAIRS, MinecraftItems.STRIPPED_ACACIA_WALL, () -> Items.STRIPPED_ACACIA_WOOD, false, c);
        slabStairsWallRecipe(MinecraftItems.STRIPPED_DARK_OAK_SLAB, MinecraftItems.STRIPPED_DARK_OAK_STAIRS, MinecraftItems.STRIPPED_DARK_OAK_WALL, () -> Items.STRIPPED_DARK_OAK_WOOD, false, c);
        slabStairsWallRecipe(MinecraftItems.WHITE_CONCRETE_SLAB, MinecraftItems.WHITE_CONCRETE_STAIRS, MinecraftItems.WHITE_CONCRETE_WALL, () -> Items.WHITE_CONCRETE, true, c);
        slabStairsWallRecipe(MinecraftItems.ORANGE_CONCRETE_SLAB, MinecraftItems.ORANGE_CONCRETE_STAIRS, MinecraftItems.ORANGE_CONCRETE_WALL, () -> Items.ORANGE_CONCRETE, true, c);
        slabStairsWallRecipe(MinecraftItems.MAGENTA_CONCRETE_SLAB, MinecraftItems.MAGENTA_CONCRETE_STAIRS, MinecraftItems.MAGENTA_CONCRETE_WALL, () -> Items.MAGENTA_CONCRETE, true, c);
        slabStairsWallRecipe(MinecraftItems.LIGHT_BLUE_CONCRETE_SLAB, MinecraftItems.LIGHT_BLUE_CONCRETE_STAIRS, MinecraftItems.LIGHT_BLUE_CONCRETE_WALL, () -> Items.LIGHT_BLUE_CONCRETE, true, c);
        slabStairsWallRecipe(MinecraftItems.YELLOW_CONCRETE_SLAB, MinecraftItems.YELLOW_CONCRETE_STAIRS, MinecraftItems.YELLOW_CONCRETE_WALL, () -> Items.YELLOW_CONCRETE, true, c);
        slabStairsWallRecipe(MinecraftItems.LIME_CONCRETE_SLAB, MinecraftItems.LIME_CONCRETE_STAIRS, MinecraftItems.LIME_CONCRETE_WALL, () -> Items.LIME_CONCRETE, true, c);
        slabStairsWallRecipe(MinecraftItems.PINK_CONCRETE_SLAB, MinecraftItems.PINK_CONCRETE_STAIRS, MinecraftItems.PINK_CONCRETE_WALL, () -> Items.PINK_CONCRETE, true, c);
        slabStairsWallRecipe(MinecraftItems.GRAY_CONCRETE_SLAB, MinecraftItems.GRAY_CONCRETE_STAIRS, MinecraftItems.GRAY_CONCRETE_WALL, () -> Items.GRAY_CONCRETE, true, c);
        slabStairsWallRecipe(MinecraftItems.LIGHT_GRAY_CONCRETE_SLAB, MinecraftItems.LIGHT_GRAY_CONCRETE_STAIRS, MinecraftItems.LIGHT_GRAY_CONCRETE_WALL, () -> Items.LIGHT_GRAY_CONCRETE, true, c);
        slabStairsWallRecipe(MinecraftItems.CYAN_CONCRETE_SLAB, MinecraftItems.CYAN_CONCRETE_STAIRS, MinecraftItems.CYAN_CONCRETE_WALL, () -> Items.CYAN_CONCRETE, true, c);
        slabStairsWallRecipe(MinecraftItems.PURPLE_CONCRETE_SLAB, MinecraftItems.PURPLE_CONCRETE_STAIRS, MinecraftItems.PURPLE_CONCRETE_WALL, () -> Items.PURPLE_CONCRETE, true, c);
        slabStairsWallRecipe(MinecraftItems.BLUE_CONCRETE_SLAB, MinecraftItems.BLUE_CONCRETE_STAIRS, MinecraftItems.BLUE_CONCRETE_WALL, () -> Items.BLUE_CONCRETE, true, c);
        slabStairsWallRecipe(MinecraftItems.BROWN_CONCRETE_SLAB, MinecraftItems.BROWN_CONCRETE_STAIRS, MinecraftItems.BROWN_CONCRETE_WALL, () -> Items.BROWN_CONCRETE, true, c);
        slabStairsWallRecipe(MinecraftItems.GREEN_CONCRETE_SLAB, MinecraftItems.GREEN_CONCRETE_STAIRS, MinecraftItems.GREEN_CONCRETE_WALL, () -> Items.GREEN_CONCRETE, true, c);
        slabStairsWallRecipe(MinecraftItems.RED_CONCRETE_SLAB, MinecraftItems.RED_CONCRETE_STAIRS, MinecraftItems.RED_CONCRETE_WALL, () -> Items.RED_CONCRETE, true, c);
        slabStairsWallRecipe(MinecraftItems.BLACK_CONCRETE_SLAB, MinecraftItems.BLACK_CONCRETE_STAIRS, MinecraftItems.BLACK_CONCRETE_WALL, () -> Items.BLACK_CONCRETE, true, c);
        slabStairsWallRecipe(MinecraftItems.WHITE_CONCRETE_POWDER_SLAB, MinecraftItems.WHITE_CONCRETE_POWDER_STAIRS, MinecraftItems.WHITE_CONCRETE_POWDER_WALL, () -> Items.WHITE_CONCRETE_POWDER, false, c);
        slabStairsWallRecipe(MinecraftItems.ORANGE_CONCRETE_POWDER_SLAB, MinecraftItems.ORANGE_CONCRETE_POWDER_STAIRS, MinecraftItems.ORANGE_CONCRETE_POWDER_WALL, () -> Items.ORANGE_CONCRETE_POWDER, false, c);
        slabStairsWallRecipe(MinecraftItems.MAGENTA_CONCRETE_POWDER_SLAB, MinecraftItems.MAGENTA_CONCRETE_POWDER_STAIRS, MinecraftItems.MAGENTA_CONCRETE_POWDER_WALL, () -> Items.MAGENTA_CONCRETE_POWDER, false, c);
        slabStairsWallRecipe(MinecraftItems.LIGHT_BLUE_CONCRETE_POWDER_SLAB, MinecraftItems.LIGHT_BLUE_CONCRETE_POWDER_STAIRS, MinecraftItems.LIGHT_BLUE_CONCRETE_POWDER_WALL, () -> Items.LIGHT_BLUE_CONCRETE_POWDER, false, c);
        slabStairsWallRecipe(MinecraftItems.YELLOW_CONCRETE_POWDER_SLAB, MinecraftItems.YELLOW_CONCRETE_POWDER_STAIRS, MinecraftItems.YELLOW_CONCRETE_POWDER_WALL, () -> Items.YELLOW_CONCRETE_POWDER, false, c);
        slabStairsWallRecipe(MinecraftItems.LIME_CONCRETE_POWDER_SLAB, MinecraftItems.LIME_CONCRETE_POWDER_STAIRS, MinecraftItems.LIME_CONCRETE_POWDER_WALL, () -> Items.LIME_CONCRETE_POWDER, false, c);
        slabStairsWallRecipe(MinecraftItems.PINK_CONCRETE_POWDER_SLAB, MinecraftItems.PINK_CONCRETE_POWDER_STAIRS, MinecraftItems.PINK_CONCRETE_POWDER_WALL, () -> Items.PINK_CONCRETE_POWDER, false, c);
        slabStairsWallRecipe(MinecraftItems.GRAY_CONCRETE_POWDER_SLAB, MinecraftItems.GRAY_CONCRETE_POWDER_STAIRS, MinecraftItems.GRAY_CONCRETE_POWDER_WALL, () -> Items.GRAY_CONCRETE_POWDER, false, c);
        slabStairsWallRecipe(MinecraftItems.LIGHT_GRAY_CONCRETE_POWDER_SLAB, MinecraftItems.LIGHT_GRAY_CONCRETE_POWDER_STAIRS, MinecraftItems.LIGHT_GRAY_CONCRETE_POWDER_WALL, () -> Items.LIGHT_GRAY_CONCRETE_POWDER, false, c);
        slabStairsWallRecipe(MinecraftItems.CYAN_CONCRETE_POWDER_SLAB, MinecraftItems.CYAN_CONCRETE_POWDER_STAIRS, MinecraftItems.CYAN_CONCRETE_POWDER_WALL, () -> Items.CYAN_CONCRETE_POWDER, false, c);
        slabStairsWallRecipe(MinecraftItems.PURPLE_CONCRETE_POWDER_SLAB, MinecraftItems.PURPLE_CONCRETE_POWDER_STAIRS, MinecraftItems.PURPLE_CONCRETE_POWDER_WALL, () -> Items.PURPLE_CONCRETE_POWDER, false, c);
        slabStairsWallRecipe(MinecraftItems.BLUE_CONCRETE_POWDER_SLAB, MinecraftItems.BLUE_CONCRETE_POWDER_STAIRS, MinecraftItems.BLUE_CONCRETE_POWDER_WALL, () -> Items.BLUE_CONCRETE_POWDER, false, c);
        slabStairsWallRecipe(MinecraftItems.BROWN_CONCRETE_POWDER_SLAB, MinecraftItems.BROWN_CONCRETE_POWDER_STAIRS, MinecraftItems.BROWN_CONCRETE_POWDER_WALL, () -> Items.BROWN_CONCRETE_POWDER, false, c);
        slabStairsWallRecipe(MinecraftItems.GREEN_CONCRETE_POWDER_SLAB, MinecraftItems.GREEN_CONCRETE_POWDER_STAIRS, MinecraftItems.GREEN_CONCRETE_POWDER_WALL, () -> Items.GREEN_CONCRETE_POWDER, false, c);
        slabStairsWallRecipe(MinecraftItems.RED_CONCRETE_POWDER_SLAB, MinecraftItems.RED_CONCRETE_POWDER_STAIRS, MinecraftItems.RED_CONCRETE_POWDER_WALL, () -> Items.RED_CONCRETE_POWDER, false, c);
        slabStairsWallRecipe(MinecraftItems.BLACK_CONCRETE_POWDER_SLAB, MinecraftItems.BLACK_CONCRETE_POWDER_STAIRS, MinecraftItems.BLACK_CONCRETE_POWDER_WALL, () -> Items.BLACK_CONCRETE_POWDER, false, c);
        slabStairsWallRecipe(MinecraftItems.WHITE_GLAZED_TERRACOTTA_SLAB, MinecraftItems.WHITE_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.WHITE_GLAZED_TERRACOTTA_WALL, () -> Items.WHITE_GLAZED_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.ORANGE_GLAZED_TERRACOTTA_SLAB, MinecraftItems.ORANGE_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.ORANGE_GLAZED_TERRACOTTA_WALL, () -> Items.ORANGE_GLAZED_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.MAGENTA_GLAZED_TERRACOTTA_SLAB, MinecraftItems.MAGENTA_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.MAGENTA_GLAZED_TERRACOTTA_WALL, () -> Items.MAGENTA_GLAZED_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.LIGHT_BLUE_GLAZED_TERRACOTTA_SLAB, MinecraftItems.LIGHT_BLUE_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.LIGHT_BLUE_GLAZED_TERRACOTTA_WALL, () -> Items.LIGHT_BLUE_GLAZED_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.YELLOW_GLAZED_TERRACOTTA_SLAB, MinecraftItems.YELLOW_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.YELLOW_GLAZED_TERRACOTTA_WALL, () -> Items.YELLOW_GLAZED_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.LIME_GLAZED_TERRACOTTA_SLAB, MinecraftItems.LIME_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.LIME_GLAZED_TERRACOTTA_WALL, () -> Items.LIME_GLAZED_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.PINK_GLAZED_TERRACOTTA_SLAB, MinecraftItems.PINK_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.PINK_GLAZED_TERRACOTTA_WALL, () -> Items.PINK_GLAZED_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.GRAY_GLAZED_TERRACOTTA_SLAB, MinecraftItems.GRAY_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.GRAY_GLAZED_TERRACOTTA_WALL, () -> Items.GRAY_GLAZED_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.LIGHT_GRAY_GLAZED_TERRACOTTA_SLAB, MinecraftItems.LIGHT_GRAY_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.LIGHT_GRAY_GLAZED_TERRACOTTA_WALL, () -> Items.LIGHT_GRAY_GLAZED_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.CYAN_GLAZED_TERRACOTTA_SLAB, MinecraftItems.CYAN_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.CYAN_GLAZED_TERRACOTTA_WALL, () -> Items.CYAN_GLAZED_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.PURPLE_GLAZED_TERRACOTTA_SLAB, MinecraftItems.PURPLE_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.PURPLE_GLAZED_TERRACOTTA_WALL, () -> Items.PURPLE_GLAZED_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.BLUE_GLAZED_TERRACOTTA_SLAB, MinecraftItems.BLUE_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.BLUE_GLAZED_TERRACOTTA_WALL, () -> Items.BLUE_GLAZED_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.BROWN_GLAZED_TERRACOTTA_SLAB, MinecraftItems.BROWN_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.BROWN_GLAZED_TERRACOTTA_WALL, () -> Items.BROWN_GLAZED_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.GREEN_GLAZED_TERRACOTTA_SLAB, MinecraftItems.GREEN_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.GREEN_GLAZED_TERRACOTTA_WALL, () -> Items.GREEN_GLAZED_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.RED_GLAZED_TERRACOTTA_SLAB, MinecraftItems.RED_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.RED_GLAZED_TERRACOTTA_WALL, () -> Items.RED_GLAZED_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.BLACK_GLAZED_TERRACOTTA_SLAB, MinecraftItems.BLACK_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.BLACK_GLAZED_TERRACOTTA_WALL, () -> Items.BLACK_GLAZED_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.WHITE_STAINED_GLASS_SLAB, MinecraftItems.WHITE_STAINED_GLASS_STAIRS, MinecraftItems.WHITE_STAINED_GLASS_WALL, () -> Items.WHITE_STAINED_GLASS, false, c);
        slabStairsWallRecipe(MinecraftItems.ORANGE_STAINED_GLASS_SLAB, MinecraftItems.ORANGE_STAINED_GLASS_STAIRS, MinecraftItems.ORANGE_STAINED_GLASS_WALL, () -> Items.ORANGE_STAINED_GLASS, false, c);
        slabStairsWallRecipe(MinecraftItems.MAGENTA_STAINED_GLASS_SLAB, MinecraftItems.MAGENTA_STAINED_GLASS_STAIRS, MinecraftItems.MAGENTA_STAINED_GLASS_WALL, () -> Items.MAGENTA_STAINED_GLASS, false, c);
        slabStairsWallRecipe(MinecraftItems.LIGHT_BLUE_STAINED_GLASS_SLAB, MinecraftItems.LIGHT_BLUE_STAINED_GLASS_STAIRS, MinecraftItems.LIGHT_BLUE_STAINED_GLASS_WALL, () -> Items.LIGHT_BLUE_STAINED_GLASS, false, c);
        slabStairsWallRecipe(MinecraftItems.YELLOW_STAINED_GLASS_SLAB, MinecraftItems.YELLOW_STAINED_GLASS_STAIRS, MinecraftItems.YELLOW_STAINED_GLASS_WALL, () -> Items.YELLOW_STAINED_GLASS, false, c);
        slabStairsWallRecipe(MinecraftItems.LIME_STAINED_GLASS_SLAB, MinecraftItems.LIME_STAINED_GLASS_STAIRS, MinecraftItems.LIME_STAINED_GLASS_WALL, () -> Items.LIME_STAINED_GLASS, false, c);
        slabStairsWallRecipe(MinecraftItems.PINK_STAINED_GLASS_SLAB, MinecraftItems.PINK_STAINED_GLASS_STAIRS, MinecraftItems.PINK_STAINED_GLASS_WALL, () -> Items.PINK_STAINED_GLASS, false, c);
        slabStairsWallRecipe(MinecraftItems.GRAY_STAINED_GLASS_SLAB, MinecraftItems.GRAY_STAINED_GLASS_STAIRS, MinecraftItems.GRAY_STAINED_GLASS_WALL, () -> Items.GRAY_STAINED_GLASS, false, c);
        slabStairsWallRecipe(MinecraftItems.LIGHT_GRAY_STAINED_GLASS_SLAB, MinecraftItems.LIGHT_GRAY_STAINED_GLASS_STAIRS, MinecraftItems.LIGHT_GRAY_STAINED_GLASS_WALL, () -> Items.LIGHT_GRAY_STAINED_GLASS, false, c);
        slabStairsWallRecipe(MinecraftItems.CYAN_STAINED_GLASS_SLAB, MinecraftItems.CYAN_STAINED_GLASS_STAIRS, MinecraftItems.CYAN_STAINED_GLASS_WALL, () -> Items.CYAN_STAINED_GLASS, false, c);
        slabStairsWallRecipe(MinecraftItems.PURPLE_STAINED_GLASS_SLAB, MinecraftItems.PURPLE_STAINED_GLASS_STAIRS, MinecraftItems.PURPLE_STAINED_GLASS_WALL, () -> Items.PURPLE_STAINED_GLASS, false, c);
        slabStairsWallRecipe(MinecraftItems.BLUE_STAINED_GLASS_SLAB, MinecraftItems.BLUE_STAINED_GLASS_STAIRS, MinecraftItems.BLUE_STAINED_GLASS_WALL, () -> Items.BLUE_STAINED_GLASS, false, c);
        slabStairsWallRecipe(MinecraftItems.BROWN_STAINED_GLASS_SLAB, MinecraftItems.BROWN_STAINED_GLASS_STAIRS, MinecraftItems.BROWN_STAINED_GLASS_WALL, () -> Items.BROWN_STAINED_GLASS, false, c);
        slabStairsWallRecipe(MinecraftItems.GREEN_STAINED_GLASS_SLAB, MinecraftItems.GREEN_STAINED_GLASS_STAIRS, MinecraftItems.GREEN_STAINED_GLASS_WALL, () -> Items.GREEN_STAINED_GLASS, false, c);
        slabStairsWallRecipe(MinecraftItems.RED_STAINED_GLASS_SLAB, MinecraftItems.RED_STAINED_GLASS_STAIRS, MinecraftItems.RED_STAINED_GLASS_WALL, () -> Items.RED_STAINED_GLASS, false, c);
        slabStairsWallRecipe(MinecraftItems.BLACK_STAINED_GLASS_SLAB, MinecraftItems.BLACK_STAINED_GLASS_STAIRS, MinecraftItems.BLACK_STAINED_GLASS_WALL, () -> Items.BLACK_STAINED_GLASS, false, c);
        slabStairsWallRecipe(MinecraftItems.WHITE_TERRACOTTA_SLAB, MinecraftItems.WHITE_TERRACOTTA_STAIRS, MinecraftItems.WHITE_TERRACOTTA_WALL, () -> Items.WHITE_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.ORANGE_TERRACOTTA_SLAB, MinecraftItems.ORANGE_TERRACOTTA_STAIRS, MinecraftItems.ORANGE_TERRACOTTA_WALL, () -> Items.ORANGE_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.MAGENTA_TERRACOTTA_SLAB, MinecraftItems.MAGENTA_TERRACOTTA_STAIRS, MinecraftItems.MAGENTA_TERRACOTTA_WALL, () -> Items.MAGENTA_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.LIGHT_BLUE_TERRACOTTA_SLAB, MinecraftItems.LIGHT_BLUE_TERRACOTTA_STAIRS, MinecraftItems.LIGHT_BLUE_TERRACOTTA_WALL, () -> Items.LIGHT_BLUE_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.YELLOW_TERRACOTTA_SLAB, MinecraftItems.YELLOW_TERRACOTTA_STAIRS, MinecraftItems.YELLOW_TERRACOTTA_WALL, () -> Items.YELLOW_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.LIME_TERRACOTTA_SLAB, MinecraftItems.LIME_TERRACOTTA_STAIRS, MinecraftItems.LIME_TERRACOTTA_WALL, () -> Items.LIME_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.PINK_TERRACOTTA_SLAB, MinecraftItems.PINK_TERRACOTTA_STAIRS, MinecraftItems.PINK_TERRACOTTA_WALL, () -> Items.PINK_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.GRAY_TERRACOTTA_SLAB, MinecraftItems.GRAY_TERRACOTTA_STAIRS, MinecraftItems.GRAY_TERRACOTTA_WALL, () -> Items.GRAY_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.LIGHT_GRAY_TERRACOTTA_SLAB, MinecraftItems.LIGHT_GRAY_TERRACOTTA_STAIRS, MinecraftItems.LIGHT_GRAY_TERRACOTTA_WALL, () -> Items.LIGHT_GRAY_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.CYAN_TERRACOTTA_SLAB, MinecraftItems.CYAN_TERRACOTTA_STAIRS, MinecraftItems.CYAN_TERRACOTTA_WALL, () -> Items.CYAN_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.PURPLE_TERRACOTTA_SLAB, MinecraftItems.PURPLE_TERRACOTTA_STAIRS, MinecraftItems.PURPLE_TERRACOTTA_WALL, () -> Items.PURPLE_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.BLUE_TERRACOTTA_SLAB, MinecraftItems.BLUE_TERRACOTTA_STAIRS, MinecraftItems.BLUE_TERRACOTTA_WALL, () -> Items.BLUE_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.BROWN_TERRACOTTA_SLAB, MinecraftItems.BROWN_TERRACOTTA_STAIRS, MinecraftItems.BROWN_TERRACOTTA_WALL, () -> Items.BROWN_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.GREEN_TERRACOTTA_SLAB, MinecraftItems.GREEN_TERRACOTTA_STAIRS, MinecraftItems.GREEN_TERRACOTTA_WALL, () -> Items.GREEN_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.RED_TERRACOTTA_SLAB, MinecraftItems.RED_TERRACOTTA_STAIRS, MinecraftItems.RED_TERRACOTTA_WALL, () -> Items.RED_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.BLACK_TERRACOTTA_SLAB, MinecraftItems.BLACK_TERRACOTTA_STAIRS, MinecraftItems.BLACK_TERRACOTTA_WALL, () -> Items.BLACK_TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.WHITE_WOOL_SLAB, MinecraftItems.WHITE_WOOL_STAIRS, MinecraftItems.WHITE_WOOL_WALL, () -> Items.WHITE_WOOL, false, c);
        slabStairsWallRecipe(MinecraftItems.ORANGE_WOOL_SLAB, MinecraftItems.ORANGE_WOOL_STAIRS, MinecraftItems.ORANGE_WOOL_WALL, () -> Items.ORANGE_WOOL, false, c);
        slabStairsWallRecipe(MinecraftItems.MAGENTA_WOOL_SLAB, MinecraftItems.MAGENTA_WOOL_STAIRS, MinecraftItems.MAGENTA_WOOL_WALL, () -> Items.MAGENTA_WOOL, false, c);
        slabStairsWallRecipe(MinecraftItems.LIGHT_BLUE_WOOL_SLAB, MinecraftItems.LIGHT_BLUE_WOOL_STAIRS, MinecraftItems.LIGHT_BLUE_WOOL_WALL, () -> Items.LIGHT_BLUE_WOOL, false, c);
        slabStairsWallRecipe(MinecraftItems.YELLOW_WOOL_SLAB, MinecraftItems.YELLOW_WOOL_STAIRS, MinecraftItems.YELLOW_WOOL_WALL, () -> Items.YELLOW_WOOL, false, c);
        slabStairsWallRecipe(MinecraftItems.LIME_WOOL_SLAB, MinecraftItems.LIME_WOOL_STAIRS, MinecraftItems.LIME_WOOL_WALL, () -> Items.LIME_WOOL, false, c);
        slabStairsWallRecipe(MinecraftItems.PINK_WOOL_SLAB, MinecraftItems.PINK_WOOL_STAIRS, MinecraftItems.PINK_WOOL_WALL, () -> Items.PINK_WOOL, false, c);
        slabStairsWallRecipe(MinecraftItems.GRAY_WOOL_SLAB, MinecraftItems.GRAY_WOOL_STAIRS, MinecraftItems.GRAY_WOOL_WALL, () -> Items.GRAY_WOOL, false, c);
        slabStairsWallRecipe(MinecraftItems.LIGHT_GRAY_WOOL_SLAB, MinecraftItems.LIGHT_GRAY_WOOL_STAIRS, MinecraftItems.LIGHT_GRAY_WOOL_WALL, () -> Items.LIGHT_GRAY_WOOL, false, c);
        slabStairsWallRecipe(MinecraftItems.CYAN_WOOL_SLAB, MinecraftItems.CYAN_WOOL_STAIRS, MinecraftItems.CYAN_WOOL_WALL, () -> Items.CYAN_WOOL, false, c);
        slabStairsWallRecipe(MinecraftItems.PURPLE_WOOL_SLAB, MinecraftItems.PURPLE_WOOL_STAIRS, MinecraftItems.PURPLE_WOOL_WALL, () -> Items.PURPLE_WOOL, false, c);
        slabStairsWallRecipe(MinecraftItems.BLUE_WOOL_SLAB, MinecraftItems.BLUE_WOOL_STAIRS, MinecraftItems.BLUE_WOOL_WALL, () -> Items.BLUE_WOOL, false, c);
        slabStairsWallRecipe(MinecraftItems.BROWN_WOOL_SLAB, MinecraftItems.BROWN_WOOL_STAIRS, MinecraftItems.BROWN_WOOL_WALL, () -> Items.BROWN_WOOL, false, c);
        slabStairsWallRecipe(MinecraftItems.GREEN_WOOL_SLAB, MinecraftItems.GREEN_WOOL_STAIRS, MinecraftItems.GREEN_WOOL_WALL, () -> Items.GREEN_WOOL, false, c);
        slabStairsWallRecipe(MinecraftItems.RED_WOOL_SLAB, MinecraftItems.RED_WOOL_STAIRS, MinecraftItems.RED_WOOL_WALL, () -> Items.RED_WOOL, false, c);
        slabStairsWallRecipe(MinecraftItems.BLACK_WOOL_SLAB, MinecraftItems.BLACK_WOOL_STAIRS, MinecraftItems.BLACK_WOOL_WALL, () -> Items.BLACK_WOOL, false, c);
        slabStairsWallRecipe(MinecraftItems.DIRT_SLAB, MinecraftItems.DIRT_STAIRS, MinecraftItems.DIRT_WALL, () -> Items.DIRT, false, c);
        slabStairsWallRecipe(MinecraftItems.COARSE_DIRT_SLAB, MinecraftItems.COARSE_DIRT_STAIRS, MinecraftItems.COARSE_DIRT_WALL, () -> Items.COARSE_DIRT, false, c);
        slabStairsWallRecipe(MinecraftItems.PODZOL_SLAB, MinecraftItems.PODZOL_STAIRS, MinecraftItems.PODZOL_WALL, () -> Items.PODZOL, false, c);
        slabStairsWallRecipe(MinecraftItems.BEDROCK_SLAB, MinecraftItems.BEDROCK_STAIRS, MinecraftItems.BEDROCK_WALL, () -> Items.BEDROCK, true, c);
        slabStairsWallRecipe(MinecraftItems.SAND_SLAB, MinecraftItems.SAND_STAIRS, MinecraftItems.SAND_WALL, () -> Items.SAND, false, c);
        slabStairsWallRecipe(MinecraftItems.RED_SAND_SLAB, MinecraftItems.RED_SAND_STAIRS, MinecraftItems.RED_SAND_WALL, () -> Items.RED_SAND, false, c);
        slabStairsWallRecipe(MinecraftItems.GRAVEL_SLAB, MinecraftItems.GRAVEL_STAIRS, MinecraftItems.GRAVEL_WALL, () -> Items.GRAVEL, false, c);
        slabStairsWallRecipe(MinecraftItems.GOLD_ORE_SLAB, MinecraftItems.GOLD_ORE_STAIRS, MinecraftItems.GOLD_ORE_WALL, () -> Items.GOLD_ORE, true, c);
        slabStairsWallRecipe(MinecraftItems.IRON_ORE_SLAB, MinecraftItems.IRON_ORE_STAIRS, MinecraftItems.IRON_ORE_WALL, () -> Items.IRON_ORE, true, c);
        slabStairsWallRecipe(MinecraftItems.COAL_ORE_SLAB, MinecraftItems.COAL_ORE_STAIRS, MinecraftItems.COAL_ORE_WALL, () -> Items.COAL_ORE, true, c);
        slabStairsWallRecipe(MinecraftItems.SPONGE_SLAB, MinecraftItems.SPONGE_STAIRS, MinecraftItems.SPONGE_WALL, () -> Items.SPONGE, false, c);
        slabStairsWallRecipe(MinecraftItems.WET_SPONGE_SLAB, MinecraftItems.WET_SPONGE_STAIRS, MinecraftItems.WET_SPONGE_WALL, () -> Items.WET_SPONGE, false, c);
        slabStairsWallRecipe(MinecraftItems.GLASS_SLAB, MinecraftItems.GLASS_STAIRS, MinecraftItems.GLASS_WALL, () -> Items.GLASS, false, c);
        slabStairsWallRecipe(MinecraftItems.LAPIS_ORE_SLAB, MinecraftItems.LAPIS_ORE_STAIRS, MinecraftItems.LAPIS_ORE_WALL, () -> Items.LAPIS_ORE, true, c);
        slabStairsWallRecipe(MinecraftItems.LAPIS_BLOCK_SLAB, MinecraftItems.LAPIS_BLOCK_STAIRS, MinecraftItems.LAPIS_BLOCK_WALL, () -> Items.LAPIS_BLOCK, true, c);
        slabStairsWallRecipe(MinecraftItems.CHISELED_SANDSTONE_SLAB, MinecraftItems.CHISELED_SANDSTONE_STAIRS, MinecraftItems.CHISELED_SANDSTONE_WALL, () -> Items.CHISELED_SANDSTONE, true, c);
        slabStairsWallRecipe(MinecraftItems.GOLD_BLOCK_SLAB, MinecraftItems.GOLD_BLOCK_STAIRS, MinecraftItems.GOLD_BLOCK_WALL, () -> Items.GOLD_BLOCK, true, c);
        slabStairsWallRecipe(MinecraftItems.IRON_BLOCK_SLAB, MinecraftItems.IRON_BLOCK_STAIRS, MinecraftItems.IRON_BLOCK_WALL, () -> Items.IRON_BLOCK, true, c);
        slabStairsWallRecipe(MinecraftItems.BOOKSHELF_SLAB, MinecraftItems.BOOKSHELF_STAIRS, MinecraftItems.BOOKSHELF_WALL, () -> Items.BOOKSHELF, false, c);
        slabStairsWallRecipe(MinecraftItems.OBSIDIAN_SLAB, MinecraftItems.OBSIDIAN_STAIRS, MinecraftItems.OBSIDIAN_WALL, () -> Items.OBSIDIAN, false, c);
        slabStairsWallRecipe(MinecraftItems.PURPUR_PILLAR_SLAB, MinecraftItems.PURPUR_PILLAR_STAIRS, MinecraftItems.PURPUR_PILLAR_WALL, () -> Items.PURPUR_PILLAR, true, c);
        slabStairsWallRecipe(MinecraftItems.DIAMOND_ORE_SLAB, MinecraftItems.DIAMOND_ORE_STAIRS, MinecraftItems.DIAMOND_ORE_WALL, () -> Items.DIAMOND_ORE, true, c);
        slabStairsWallRecipe(MinecraftItems.DIAMOND_BLOCK_SLAB, MinecraftItems.DIAMOND_BLOCK_STAIRS, MinecraftItems.DIAMOND_BLOCK_WALL, () -> Items.DIAMOND_BLOCK, true, c);
        slabStairsWallRecipe(MinecraftItems.REDSTONE_ORE_SLAB, MinecraftItems.REDSTONE_ORE_STAIRS, MinecraftItems.REDSTONE_ORE_WALL, () -> Items.REDSTONE_ORE, true, c);
        slabStairsWallRecipe(MinecraftItems.ICE_SLAB, MinecraftItems.ICE_STAIRS, MinecraftItems.ICE_WALL, () -> Items.ICE, false, c);
        slabStairsWallRecipe(MinecraftItems.SNOW_SLAB, MinecraftItems.SNOW_STAIRS, MinecraftItems.SNOW_WALL, () -> Items.SNOW_BLOCK, false, c);
        slabStairsWallRecipe(MinecraftItems.CLAY_SLAB, MinecraftItems.CLAY_STAIRS, MinecraftItems.CLAY_WALL, () -> Items.CLAY, false, c);
        slabStairsWallRecipe(MinecraftItems.PUMPKIN_SLAB, MinecraftItems.PUMPKIN_STAIRS, MinecraftItems.PUMPKIN_WALL, () -> Items.PUMPKIN, false, c);
        slabStairsWallRecipe(MinecraftItems.NETHERRACK_SLAB, MinecraftItems.NETHERRACK_STAIRS, MinecraftItems.NETHERRACK_WALL, () -> Items.NETHERRACK, true, c);
        slabStairsWallRecipe(MinecraftItems.SOUL_SAND_SLAB, MinecraftItems.SOUL_SAND_STAIRS, MinecraftItems.SOUL_SAND_WALL, () -> Items.SOUL_SAND, false, c);
        slabStairsWallRecipe(MinecraftItems.GLOWSTONE_SLAB, MinecraftItems.GLOWSTONE_STAIRS, MinecraftItems.GLOWSTONE_WALL, () -> Items.GLOWSTONE, true, c);
        slabStairsWallRecipe(MinecraftItems.CRACKED_STONE_BRICK_SLAB, MinecraftItems.CRACKED_STONE_BRICK_STAIRS, MinecraftItems.CRACKED_STONE_BRICK_WALL, () -> Items.CRACKED_STONE_BRICKS, true, c);
        slabStairsWallRecipe(MinecraftItems.CHISELED_STONE_BRICK_SLAB, MinecraftItems.CHISELED_STONE_BRICK_STAIRS, MinecraftItems.CHISELED_STONE_BRICK_WALL, () -> Items.CHISELED_STONE_BRICKS, true, c);
        slabStairsWallRecipe(MinecraftItems.BROWN_MUSHROOM_SLAB, MinecraftItems.BROWN_MUSHROOM_STAIRS, MinecraftItems.BROWN_MUSHROOM_WALL, () -> Items.BROWN_MUSHROOM_BLOCK, false, c);
        slabStairsWallRecipe(MinecraftItems.RED_MUSHROOM_SLAB, MinecraftItems.RED_MUSHROOM_STAIRS, MinecraftItems.RED_MUSHROOM_WALL, () -> Items.RED_MUSHROOM_BLOCK, false, c);
        slabStairsWallRecipe(MinecraftItems.MUSHROOM_STEM_SLAB, MinecraftItems.MUSHROOM_STEM_STAIRS, MinecraftItems.MUSHROOM_STEM_WALL, () -> Items.MUSHROOM_STEM, false, c);
        slabStairsWallRecipe(MinecraftItems.MELON_SLAB, MinecraftItems.MELON_STAIRS, MinecraftItems.MELON_WALL, () -> Items.MELON, false, c);
        slabStairsWallRecipe(MinecraftItems.MYCELIUM_SLAB, MinecraftItems.MYCELIUM_STAIRS, MinecraftItems.MYCELIUM_WALL, () -> Items.MYCELIUM, false, c);
        slabStairsWallRecipe(MinecraftItems.END_STONE_SLAB, MinecraftItems.END_STONE_STAIRS, MinecraftItems.END_STONE_WALL, () -> Items.END_STONE, true, c);
        slabStairsWallRecipe(MinecraftItems.EMERALD_ORE_SLAB, MinecraftItems.EMERALD_ORE_STAIRS, MinecraftItems.EMERALD_ORE_WALL, () -> Items.EMERALD_ORE, true, c);
        slabStairsWallRecipe(MinecraftItems.EMERALD_BLOCK_SLAB, MinecraftItems.EMERALD_BLOCK_STAIRS, MinecraftItems.EMERALD_BLOCK_WALL, () -> Items.EMERALD_BLOCK, true, c);
        slabStairsWallRecipe(MinecraftItems.REDSTONE_BLOCK_SLAB, MinecraftItems.REDSTONE_BLOCK_STAIRS, MinecraftItems.REDSTONE_BLOCK_WALL, () -> Items.REDSTONE_BLOCK, true, c);
        slabStairsWallRecipe(MinecraftItems.NETHER_QUARTZ_ORE_SLAB, MinecraftItems.NETHER_QUARTZ_ORE_STAIRS, MinecraftItems.NETHER_QUARTZ_ORE_WALL, () -> Items.NETHER_QUARTZ_ORE, true, c);
        slabStairsWallRecipe(MinecraftItems.CHISELED_QUARTZ_SLAB, MinecraftItems.CHISELED_QUARTZ_STAIRS, MinecraftItems.CHISELED_QUARTZ_WALL, () -> Items.CHISELED_QUARTZ_BLOCK, true, c);
        slabStairsWallRecipe(MinecraftItems.QUARTZ_PILLAR_SLAB, MinecraftItems.QUARTZ_PILLAR_STAIRS, MinecraftItems.QUARTZ_PILLAR_WALL, () -> Items.QUARTZ_PILLAR, true, c);
        slabStairsWallRecipe(MinecraftItems.HAY_SLAB, MinecraftItems.HAY_STAIRS, MinecraftItems.HAY_WALL, () -> Items.HAY_BLOCK, true, c);
        slabStairsWallRecipe(MinecraftItems.TERRACOTTA_SLAB, MinecraftItems.TERRACOTTA_STAIRS, MinecraftItems.TERRACOTTA_WALL, () -> Items.TERRACOTTA, true, c);
        slabStairsWallRecipe(MinecraftItems.COAL_SLAB, MinecraftItems.COAL_STAIRS, MinecraftItems.COAL_WALL, () -> Items.COAL_BLOCK, true, c);
        slabStairsWallRecipe(MinecraftItems.PACKED_ICE_SLAB, MinecraftItems.PACKED_ICE_STAIRS, MinecraftItems.PACKED_ICE_WALL, () -> Items.PACKED_ICE, false, c);
        slabStairsWallRecipe(MinecraftItems.SLIME_SLAB, MinecraftItems.SLIME_STAIRS, MinecraftItems.SLIME_WALL, () -> Items.SLIME_BLOCK, true, c);
        slabStairsWallRecipe(MinecraftItems.SEA_LANTERN_SLAB, MinecraftItems.SEA_LANTERN_STAIRS, MinecraftItems.SEA_LANTERN_WALL, () -> Items.SEA_LANTERN, true, c);
        slabStairsWallRecipe(MinecraftItems.CHISELED_RED_SANDSTONE_SLAB, MinecraftItems.CHISELED_RED_SANDSTONE_STAIRS, MinecraftItems.CHISELED_RED_SANDSTONE_WALL, () -> Items.CHISELED_RED_SANDSTONE, true, c);
        slabStairsWallRecipe(MinecraftItems.MAGMA_SLAB, MinecraftItems.MAGMA_STAIRS, MinecraftItems.MAGMA_WALL, () -> Items.MAGMA_BLOCK, false, c);
        slabStairsWallRecipe(MinecraftItems.NETHER_WART_SLAB, MinecraftItems.NETHER_WART_STAIRS, MinecraftItems.NETHER_WART_WALL, () -> Items.NETHER_WART_BLOCK, false, c);
        slabStairsWallRecipe(MinecraftItems.BONE_SLAB, MinecraftItems.BONE_STAIRS, MinecraftItems.BONE_WALL, () -> Items.BONE_BLOCK, false, c);
        slabStairsWallRecipe(MinecraftItems.DEAD_TUBE_CORAL_SLAB, MinecraftItems.DEAD_TUBE_CORAL_STAIRS, MinecraftItems.DEAD_TUBE_CORAL_WALL, () -> Items.DEAD_TUBE_CORAL_BLOCK, false, c);
        slabStairsWallRecipe(MinecraftItems.DEAD_BRAIN_CORAL_SLAB, MinecraftItems.DEAD_BRAIN_CORAL_STAIRS, MinecraftItems.DEAD_BRAIN_CORAL_WALL, () -> Items.DEAD_BRAIN_CORAL_BLOCK, false, c);
        slabStairsWallRecipe(MinecraftItems.DEAD_BUBBLE_CORAL_SLAB, MinecraftItems.DEAD_BUBBLE_CORAL_STAIRS, MinecraftItems.DEAD_BUBBLE_CORAL_WALL, () -> Items.DEAD_BUBBLE_CORAL_BLOCK, false, c);
        slabStairsWallRecipe(MinecraftItems.DEAD_FIRE_CORAL_SLAB, MinecraftItems.DEAD_FIRE_CORAL_STAIRS, MinecraftItems.DEAD_FIRE_CORAL_WALL, () -> Items.DEAD_FIRE_CORAL_BLOCK, false, c);
        slabStairsWallRecipe(MinecraftItems.DEAD_HORN_CORAL_SLAB, MinecraftItems.DEAD_HORN_CORAL_STAIRS, MinecraftItems.DEAD_HORN_CORAL_WALL, () -> Items.DEAD_HORN_CORAL_BLOCK, false, c);
        slabStairsWallRecipe(MinecraftItems.TUBE_CORAL_SLAB, MinecraftItems.TUBE_CORAL_STAIRS, MinecraftItems.TUBE_CORAL_WALL, () -> Items.TUBE_CORAL_BLOCK, false, c);
        slabStairsWallRecipe(MinecraftItems.BRAIN_CORAL_SLAB, MinecraftItems.BRAIN_CORAL_STAIRS, MinecraftItems.BRAIN_CORAL_WALL, () -> Items.BRAIN_CORAL_BLOCK, false, c);
        slabStairsWallRecipe(MinecraftItems.BUBBLE_CORAL_SLAB, MinecraftItems.BUBBLE_CORAL_STAIRS, MinecraftItems.BUBBLE_CORAL_WALL, () -> Items.BUBBLE_CORAL_BLOCK, false, c);
        slabStairsWallRecipe(MinecraftItems.FIRE_CORAL_SLAB, MinecraftItems.FIRE_CORAL_STAIRS, MinecraftItems.FIRE_CORAL_WALL, () -> Items.FIRE_CORAL_BLOCK, false, c);
        slabStairsWallRecipe(MinecraftItems.HORN_CORAL_SLAB, MinecraftItems.HORN_CORAL_STAIRS, MinecraftItems.HORN_CORAL_WALL, () -> Items.HORN_CORAL_BLOCK, false, c);
        slabStairsWallRecipe(MinecraftItems.DRIED_KELP_SLAB, MinecraftItems.DRIED_KELP_STAIRS, MinecraftItems.DRIED_KELP_WALL, () -> Items.DRIED_KELP_BLOCK, false, c);
        slabStairsWallRecipe(MinecraftItems.HONEY_SLAB, MinecraftItems.HONEY_STAIRS, MinecraftItems.HONEY_WALL, () -> Items.HONEY_BLOCK, false, c);
        slabStairsWallRecipe(MinecraftItems.HONEYCOMB_SLAB, MinecraftItems.HONEYCOMB_STAIRS, MinecraftItems.HONEYCOMB_WALL, () -> Items.HONEYCOMB_BLOCK, false, c);
    }
}
