package ihh.slabsstairswalls.minecraft;

import ihh.slabsstairswalls.LangGenDEDE;
import ihh.slabsstairswalls.SlabsStairsWalls;
import net.minecraft.data.DataGenerator;

import static ihh.slabsstairswalls.IInit.registerWall;

public final class MinecraftLangGenDEDE extends LangGenDEDE {
    public MinecraftLangGenDEDE(DataGenerator g) {
        super(g);
    }

    @Override
    protected void addTranslations() {
        add("itemGroup." + SlabsStairsWalls.MODID, SlabsStairsWalls.MODNAME);
        fenceGate(MinecraftItems.NETHER_BRICK_FENCE_GATE, "Netherziegel");
        stairs(MinecraftItems.CUT_RED_SANDSTONE_STAIRS, "Geschnittene rote Sandstein");
        stairs(MinecraftItems.CUT_SANDSTONE_STAIRS, "Geschnittene Sandstein");
        stairs(MinecraftItems.SMOOTH_STONE_STAIRS, "Glatte Stein");
        wall(MinecraftItems.CUT_RED_SANDSTONE_WALL, "Geschnittene rote Sandstein");
        wall(MinecraftItems.CUT_SANDSTONE_WALL, "Geschnittene Sandstein");
        wall(MinecraftItems.DARK_PRISMARINE_WALL, "Dunkle Prismarin");
        wall(MinecraftItems.PRISMARINE_BRICK_WALL, "Prismarinziegel");
        wall(MinecraftItems.POLISHED_ANDESITE_WALL, "Polierte Andesit");
        wall(MinecraftItems.POLISHED_DIORITE_WALL, "Polierte Diorit");
        wall(MinecraftItems.POLISHED_GRANITE_WALL, "Polierte Granit");
        wall(MinecraftItems.PURPUR_WALL, "Purpur");
        wall(MinecraftItems.QUARTZ_WALL, "Quarz");
        wall(MinecraftItems.SMOOTH_QUARTZ_WALL, "Glatte Quarz");
        wall(MinecraftItems.SMOOTH_RED_SANDSTONE_WALL, "Glatte rote Sandstein");
        wall(MinecraftItems.SMOOTH_SANDSTONE_WALL, "Glatte Sandstein");
        wall(MinecraftItems.SMOOTH_STONE_WALL, "Glatte Stein");
        wall(MinecraftItems.STONE_WALL, "Stein");
        slab(MinecraftItems.OAK_SLAB, "Eichen");
        slab(MinecraftItems.SPRUCE_SLAB, "Fichten");
        slab(MinecraftItems.BIRCH_SLAB, "Birken");
        slab(MinecraftItems.JUNGLE_SLAB, "Dschungel");
        slab(MinecraftItems.ACACIA_SLAB, "Akazien");
        slab(MinecraftItems.DARK_OAK_SLAB, "Schwarzeichen");
        slab(MinecraftItems.STRIPPED_OAK_SLAB, "Entrindete Eichen");
        slab(MinecraftItems.STRIPPED_SPRUCE_SLAB, "Entrindete Fichten");
        slab(MinecraftItems.STRIPPED_BIRCH_SLAB, "Entrindete Birken");
        slab(MinecraftItems.STRIPPED_JUNGLE_SLAB, "Entrindete Dschungel");
        slab(MinecraftItems.STRIPPED_ACACIA_SLAB, "Entrindete Akazien");
        slab(MinecraftItems.STRIPPED_DARK_OAK_SLAB, "Entrindete Schwarzeichen");
        rainbowSlab("Beton", MinecraftItems.WHITE_CONCRETE_SLAB, MinecraftItems.ORANGE_CONCRETE_SLAB, MinecraftItems.MAGENTA_CONCRETE_SLAB, MinecraftItems.LIGHT_BLUE_CONCRETE_SLAB, MinecraftItems.YELLOW_CONCRETE_SLAB, MinecraftItems.LIME_CONCRETE_SLAB, MinecraftItems.PINK_CONCRETE_SLAB, MinecraftItems.GRAY_CONCRETE_SLAB, MinecraftItems.LIGHT_GRAY_CONCRETE_SLAB, MinecraftItems.CYAN_CONCRETE_SLAB, MinecraftItems.PURPLE_CONCRETE_SLAB, MinecraftItems.BLUE_CONCRETE_SLAB, MinecraftItems.BROWN_CONCRETE_SLAB, MinecraftItems.GREEN_CONCRETE_SLAB, MinecraftItems.RED_CONCRETE_SLAB, MinecraftItems.BLACK_CONCRETE_SLAB);
        rainbowSlab("Betonpulver", MinecraftItems.WHITE_CONCRETE_POWDER_SLAB, MinecraftItems.ORANGE_CONCRETE_POWDER_SLAB, MinecraftItems.MAGENTA_CONCRETE_POWDER_SLAB, MinecraftItems.LIGHT_BLUE_CONCRETE_POWDER_SLAB, MinecraftItems.YELLOW_CONCRETE_POWDER_SLAB, MinecraftItems.LIME_CONCRETE_POWDER_SLAB, MinecraftItems.PINK_CONCRETE_POWDER_SLAB, MinecraftItems.GRAY_CONCRETE_POWDER_SLAB, MinecraftItems.LIGHT_GRAY_CONCRETE_POWDER_SLAB, MinecraftItems.CYAN_CONCRETE_POWDER_SLAB, MinecraftItems.PURPLE_CONCRETE_POWDER_SLAB, MinecraftItems.BLUE_CONCRETE_POWDER_SLAB, MinecraftItems.BROWN_CONCRETE_POWDER_SLAB, MinecraftItems.GREEN_CONCRETE_POWDER_SLAB, MinecraftItems.RED_CONCRETE_POWDER_SLAB, MinecraftItems.BLACK_CONCRETE_POWDER_SLAB);
        rainbowSlab("glasierte Keramik", MinecraftItems.WHITE_GLAZED_TERRACOTTA_SLAB, MinecraftItems.ORANGE_GLAZED_TERRACOTTA_SLAB, MinecraftItems.MAGENTA_GLAZED_TERRACOTTA_SLAB, MinecraftItems.LIGHT_BLUE_GLAZED_TERRACOTTA_SLAB, MinecraftItems.YELLOW_GLAZED_TERRACOTTA_SLAB, MinecraftItems.LIME_GLAZED_TERRACOTTA_SLAB, MinecraftItems.PINK_GLAZED_TERRACOTTA_SLAB, MinecraftItems.GRAY_GLAZED_TERRACOTTA_SLAB, MinecraftItems.LIGHT_GRAY_GLAZED_TERRACOTTA_SLAB, MinecraftItems.CYAN_GLAZED_TERRACOTTA_SLAB, MinecraftItems.PURPLE_GLAZED_TERRACOTTA_SLAB, MinecraftItems.BLUE_GLAZED_TERRACOTTA_SLAB, MinecraftItems.BROWN_GLAZED_TERRACOTTA_SLAB, MinecraftItems.GREEN_GLAZED_TERRACOTTA_SLAB, MinecraftItems.RED_GLAZED_TERRACOTTA_SLAB, MinecraftItems.BLACK_GLAZED_TERRACOTTA_SLAB);
        rainbowSlab("Glas", MinecraftItems.WHITE_STAINED_GLASS_SLAB, MinecraftItems.ORANGE_STAINED_GLASS_SLAB, MinecraftItems.MAGENTA_STAINED_GLASS_SLAB, MinecraftItems.LIGHT_BLUE_STAINED_GLASS_SLAB, MinecraftItems.YELLOW_STAINED_GLASS_SLAB, MinecraftItems.LIME_STAINED_GLASS_SLAB, MinecraftItems.PINK_STAINED_GLASS_SLAB, MinecraftItems.GRAY_STAINED_GLASS_SLAB, MinecraftItems.LIGHT_GRAY_STAINED_GLASS_SLAB, MinecraftItems.CYAN_STAINED_GLASS_SLAB, MinecraftItems.PURPLE_STAINED_GLASS_SLAB, MinecraftItems.BLUE_STAINED_GLASS_SLAB, MinecraftItems.BROWN_STAINED_GLASS_SLAB, MinecraftItems.GREEN_STAINED_GLASS_SLAB, MinecraftItems.RED_STAINED_GLASS_SLAB, MinecraftItems.BLACK_STAINED_GLASS_SLAB);
        rainbowSlab("Keramik", MinecraftItems.WHITE_TERRACOTTA_SLAB, MinecraftItems.ORANGE_TERRACOTTA_SLAB, MinecraftItems.MAGENTA_TERRACOTTA_SLAB, MinecraftItems.LIGHT_BLUE_TERRACOTTA_SLAB, MinecraftItems.YELLOW_TERRACOTTA_SLAB, MinecraftItems.LIME_TERRACOTTA_SLAB, MinecraftItems.PINK_TERRACOTTA_SLAB, MinecraftItems.GRAY_TERRACOTTA_SLAB, MinecraftItems.LIGHT_GRAY_TERRACOTTA_SLAB, MinecraftItems.CYAN_TERRACOTTA_SLAB, MinecraftItems.PURPLE_TERRACOTTA_SLAB, MinecraftItems.BLUE_TERRACOTTA_SLAB, MinecraftItems.BROWN_TERRACOTTA_SLAB, MinecraftItems.GREEN_TERRACOTTA_SLAB, MinecraftItems.RED_TERRACOTTA_SLAB, MinecraftItems.BLACK_TERRACOTTA_SLAB);
        rainbowSlab("Wolle", MinecraftItems.WHITE_WOOL_SLAB, MinecraftItems.ORANGE_WOOL_SLAB, MinecraftItems.MAGENTA_WOOL_SLAB, MinecraftItems.LIGHT_BLUE_WOOL_SLAB, MinecraftItems.YELLOW_WOOL_SLAB, MinecraftItems.LIME_WOOL_SLAB, MinecraftItems.PINK_WOOL_SLAB, MinecraftItems.GRAY_WOOL_SLAB, MinecraftItems.LIGHT_GRAY_WOOL_SLAB, MinecraftItems.CYAN_WOOL_SLAB, MinecraftItems.PURPLE_WOOL_SLAB, MinecraftItems.BLUE_WOOL_SLAB, MinecraftItems.BROWN_WOOL_SLAB, MinecraftItems.GREEN_WOOL_SLAB, MinecraftItems.RED_WOOL_SLAB, MinecraftItems.BLACK_WOOL_SLAB);
        slab(MinecraftItems.DIRT_SLAB, "Erd");
        slab(MinecraftItems.COARSE_DIRT_SLAB, "Grobe Erd");
        slab(MinecraftItems.PODZOL_SLAB, "Podsol");
        slab(MinecraftItems.BEDROCK_SLAB, "Grundgestein");
        slab(MinecraftItems.SAND_SLAB, "Sand");
        slab(MinecraftItems.RED_SAND_SLAB, "Rote Sand");
        slab(MinecraftItems.GRAVEL_SLAB, "Kies");
        slab(MinecraftItems.GOLD_ORE_SLAB, "Golderz");
        slab(MinecraftItems.IRON_ORE_SLAB, "Eisenerz");
        slab(MinecraftItems.COAL_ORE_SLAB, "Kohleerz");
        slab(MinecraftItems.SPONGE_SLAB, "Schwamm");
        slab(MinecraftItems.WET_SPONGE_SLAB, "Nasse Schwamm");
        slab(MinecraftItems.GLASS_SLAB, "Glass");
        slab(MinecraftItems.LAPIS_ORE_SLAB, "Lapislazulierz");
        slab(MinecraftItems.LAPIS_BLOCK_SLAB, "Lapislazuliblock");
        slab(MinecraftItems.CHISELED_SANDSTONE_SLAB, "Gemeißelte Sandstein");
        slab(MinecraftItems.GOLD_BLOCK_SLAB, "Goldblock");
        slab(MinecraftItems.IRON_BLOCK_SLAB, "Eisenblock");
        slab(MinecraftItems.BOOKSHELF_SLAB, "Bücherregal");
        slab(MinecraftItems.OBSIDIAN_SLAB, "Obsidian");
        slab(MinecraftItems.PURPUR_PILLAR_SLAB, "Purpursäulen");
        slab(MinecraftItems.DIAMOND_ORE_SLAB, "Diamanterz");
        slab(MinecraftItems.DIAMOND_BLOCK_SLAB, "Diamantblock");
        slab(MinecraftItems.REDSTONE_ORE_SLAB, "Redstoneerz");
        slab(MinecraftItems.ICE_SLAB, "Eis");
        slab(MinecraftItems.SNOW_SLAB, "Schnee");
        slab(MinecraftItems.CLAY_SLAB, "Lehm");
        slab(MinecraftItems.PUMPKIN_SLAB, "Kürbis");
        slab(MinecraftItems.NETHERRACK_SLAB, "Netherrack");
        slab(MinecraftItems.SOUL_SAND_SLAB, "Seelensand");
        slab(MinecraftItems.GLOWSTONE_SLAB, "Glowstone");
        slab(MinecraftItems.CRACKED_STONE_BRICK_SLAB, "Rissige Steinziegel");
        slab(MinecraftItems.CHISELED_STONE_BRICK_SLAB, "Gemeißelte Steinziegel");
        slab(MinecraftItems.BROWN_MUSHROOM_SLAB, "Braune Pilz");
        slab(MinecraftItems.RED_MUSHROOM_SLAB, "Rote Pilz");
        slab(MinecraftItems.MUSHROOM_STEM_SLAB, "Pilzstamm");
        slab(MinecraftItems.MELON_SLAB, "Melone");
        slab(MinecraftItems.MYCELIUM_SLAB, "Myzelium");
        slab(MinecraftItems.END_STONE_SLAB, "Endstein");
        slab(MinecraftItems.EMERALD_ORE_SLAB, "Smaragderz");
        slab(MinecraftItems.EMERALD_BLOCK_SLAB, "Smaragdblock");
        slab(MinecraftItems.REDSTONE_BLOCK_SLAB, "Redstoneblock");
        slab(MinecraftItems.NETHER_QUARTZ_ORE_SLAB, "Netherquarzerz");
        slab(MinecraftItems.CHISELED_QUARTZ_SLAB, "Gemeißelte Quarz");
        slab(MinecraftItems.QUARTZ_PILLAR_SLAB, "Quarzsäulen");
        slab(MinecraftItems.HAY_SLAB, "Heu");
        slab(MinecraftItems.TERRACOTTA_SLAB, "Terrakotta");
        slab(MinecraftItems.COAL_SLAB, "Kohle");
        slab(MinecraftItems.PACKED_ICE_SLAB, "Packeis");
        slab(MinecraftItems.SLIME_SLAB, "Schleim");
        slab(MinecraftItems.SEA_LANTERN_SLAB, "Seelaternen");
        slab(MinecraftItems.CHISELED_RED_SANDSTONE_SLAB, "Gemeißelte rote Sandstein");
        slab(MinecraftItems.MAGMA_SLAB, "Magma");
        slab(MinecraftItems.NETHER_WART_SLAB, "Netherwarzen");
        slab(MinecraftItems.BONE_SLAB, "Knochen");
        slab(MinecraftItems.DEAD_TUBE_CORAL_SLAB, "Tote Orgelkorallen");
        slab(MinecraftItems.DEAD_BRAIN_CORAL_SLAB, "Tote Gehirnkorallen");
        slab(MinecraftItems.DEAD_BUBBLE_CORAL_SLAB, "Tote Blasenkorallen");
        slab(MinecraftItems.DEAD_FIRE_CORAL_SLAB, "Tote Feuerkorallen");
        slab(MinecraftItems.DEAD_HORN_CORAL_SLAB, "Tote Geweihkorallen");
        slab(MinecraftItems.TUBE_CORAL_SLAB, "Orgelkorallen");
        slab(MinecraftItems.BRAIN_CORAL_SLAB, "Geweihkorallen");
        slab(MinecraftItems.BUBBLE_CORAL_SLAB, "Blasenkorallen");
        slab(MinecraftItems.FIRE_CORAL_SLAB, "Feuerkorallen");
        slab(MinecraftItems.HORN_CORAL_SLAB, "Gehirnkorallen");
        slab(MinecraftItems.DRIED_KELP_SLAB, "Getrocknete Seetang");
        slab(MinecraftItems.HONEY_SLAB, "Honig");
        slab(MinecraftItems.HONEYCOMB_SLAB, "Honigwaben");
        stairs(MinecraftItems.OAK_STAIRS, "Eichen");
        stairs(MinecraftItems.SPRUCE_STAIRS, "Fichten");
        stairs(MinecraftItems.BIRCH_STAIRS, "Birken");
        stairs(MinecraftItems.JUNGLE_STAIRS, "Dschungel");
        stairs(MinecraftItems.ACACIA_STAIRS, "Akazien");
        stairs(MinecraftItems.DARK_OAK_STAIRS, "Schwarzeichen");
        stairs(MinecraftItems.STRIPPED_OAK_STAIRS, "Entrindete Eichen");
        stairs(MinecraftItems.STRIPPED_SPRUCE_STAIRS, "Entrindete Fichten");
        stairs(MinecraftItems.STRIPPED_BIRCH_STAIRS, "Entrindete Birken");
        stairs(MinecraftItems.STRIPPED_JUNGLE_STAIRS, "Entrindete Dschungel");
        stairs(MinecraftItems.STRIPPED_ACACIA_STAIRS, "Entrindete Akazien");
        stairs(MinecraftItems.STRIPPED_DARK_OAK_STAIRS, "Entrindete Schwarzeichen");
        rainbowStairs("Beton", MinecraftItems.WHITE_CONCRETE_STAIRS, MinecraftItems.ORANGE_CONCRETE_STAIRS, MinecraftItems.MAGENTA_CONCRETE_STAIRS, MinecraftItems.LIGHT_BLUE_CONCRETE_STAIRS, MinecraftItems.YELLOW_CONCRETE_STAIRS, MinecraftItems.LIME_CONCRETE_STAIRS, MinecraftItems.PINK_CONCRETE_STAIRS, MinecraftItems.GRAY_CONCRETE_STAIRS, MinecraftItems.LIGHT_GRAY_CONCRETE_STAIRS, MinecraftItems.CYAN_CONCRETE_STAIRS, MinecraftItems.PURPLE_CONCRETE_STAIRS, MinecraftItems.BLUE_CONCRETE_STAIRS, MinecraftItems.BROWN_CONCRETE_STAIRS, MinecraftItems.GREEN_CONCRETE_STAIRS, MinecraftItems.RED_CONCRETE_STAIRS, MinecraftItems.BLACK_CONCRETE_STAIRS);
        rainbowStairs("Betonpulver", MinecraftItems.WHITE_CONCRETE_POWDER_STAIRS, MinecraftItems.ORANGE_CONCRETE_POWDER_STAIRS, MinecraftItems.MAGENTA_CONCRETE_POWDER_STAIRS, MinecraftItems.LIGHT_BLUE_CONCRETE_POWDER_STAIRS, MinecraftItems.YELLOW_CONCRETE_POWDER_STAIRS, MinecraftItems.LIME_CONCRETE_POWDER_STAIRS, MinecraftItems.PINK_CONCRETE_POWDER_STAIRS, MinecraftItems.GRAY_CONCRETE_POWDER_STAIRS, MinecraftItems.LIGHT_GRAY_CONCRETE_POWDER_STAIRS, MinecraftItems.CYAN_CONCRETE_POWDER_STAIRS, MinecraftItems.PURPLE_CONCRETE_POWDER_STAIRS, MinecraftItems.BLUE_CONCRETE_POWDER_STAIRS, MinecraftItems.BROWN_CONCRETE_POWDER_STAIRS, MinecraftItems.GREEN_CONCRETE_POWDER_STAIRS, MinecraftItems.RED_CONCRETE_POWDER_STAIRS, MinecraftItems.BLACK_CONCRETE_POWDER_STAIRS);
        rainbowStairs("glasierte Keramik", MinecraftItems.WHITE_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.ORANGE_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.MAGENTA_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.LIGHT_BLUE_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.YELLOW_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.LIME_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.PINK_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.GRAY_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.LIGHT_GRAY_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.CYAN_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.PURPLE_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.BLUE_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.BROWN_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.GREEN_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.RED_GLAZED_TERRACOTTA_STAIRS, MinecraftItems.BLACK_GLAZED_TERRACOTTA_STAIRS);
        rainbowStairs("Glas", MinecraftItems.WHITE_STAINED_GLASS_STAIRS, MinecraftItems.ORANGE_STAINED_GLASS_STAIRS, MinecraftItems.MAGENTA_STAINED_GLASS_STAIRS, MinecraftItems.LIGHT_BLUE_STAINED_GLASS_STAIRS, MinecraftItems.YELLOW_STAINED_GLASS_STAIRS, MinecraftItems.LIME_STAINED_GLASS_STAIRS, MinecraftItems.PINK_STAINED_GLASS_STAIRS, MinecraftItems.GRAY_STAINED_GLASS_STAIRS, MinecraftItems.LIGHT_GRAY_STAINED_GLASS_STAIRS, MinecraftItems.CYAN_STAINED_GLASS_STAIRS, MinecraftItems.PURPLE_STAINED_GLASS_STAIRS, MinecraftItems.BLUE_STAINED_GLASS_STAIRS, MinecraftItems.BROWN_STAINED_GLASS_STAIRS, MinecraftItems.GREEN_STAINED_GLASS_STAIRS, MinecraftItems.RED_STAINED_GLASS_STAIRS, MinecraftItems.BLACK_STAINED_GLASS_STAIRS);
        rainbowStairs("Keramik", MinecraftItems.WHITE_TERRACOTTA_STAIRS, MinecraftItems.ORANGE_TERRACOTTA_STAIRS, MinecraftItems.MAGENTA_TERRACOTTA_STAIRS, MinecraftItems.LIGHT_BLUE_TERRACOTTA_STAIRS, MinecraftItems.YELLOW_TERRACOTTA_STAIRS, MinecraftItems.LIME_TERRACOTTA_STAIRS, MinecraftItems.PINK_TERRACOTTA_STAIRS, MinecraftItems.GRAY_TERRACOTTA_STAIRS, MinecraftItems.LIGHT_GRAY_TERRACOTTA_STAIRS, MinecraftItems.CYAN_TERRACOTTA_STAIRS, MinecraftItems.PURPLE_TERRACOTTA_STAIRS, MinecraftItems.BLUE_TERRACOTTA_STAIRS, MinecraftItems.BROWN_TERRACOTTA_STAIRS, MinecraftItems.GREEN_TERRACOTTA_STAIRS, MinecraftItems.RED_TERRACOTTA_STAIRS, MinecraftItems.BLACK_TERRACOTTA_STAIRS);
        rainbowStairs("Wolle", MinecraftItems.WHITE_WOOL_STAIRS, MinecraftItems.ORANGE_WOOL_STAIRS, MinecraftItems.MAGENTA_WOOL_STAIRS, MinecraftItems.LIGHT_BLUE_WOOL_STAIRS, MinecraftItems.YELLOW_WOOL_STAIRS, MinecraftItems.LIME_WOOL_STAIRS, MinecraftItems.PINK_WOOL_STAIRS, MinecraftItems.GRAY_WOOL_STAIRS, MinecraftItems.LIGHT_GRAY_WOOL_STAIRS, MinecraftItems.CYAN_WOOL_STAIRS, MinecraftItems.PURPLE_WOOL_STAIRS, MinecraftItems.BLUE_WOOL_STAIRS, MinecraftItems.BROWN_WOOL_STAIRS, MinecraftItems.GREEN_WOOL_STAIRS, MinecraftItems.RED_WOOL_STAIRS, MinecraftItems.BLACK_WOOL_STAIRS);
        stairs(MinecraftItems.DIRT_STAIRS, "Erd");
        stairs(MinecraftItems.COARSE_DIRT_STAIRS, "Grobe Erd");
        stairs(MinecraftItems.PODZOL_STAIRS, "Podsol");
        stairs(MinecraftItems.BEDROCK_STAIRS, "Grundgestein");
        stairs(MinecraftItems.SAND_STAIRS, "Sand");
        stairs(MinecraftItems.RED_SAND_STAIRS, "Rote Sand");
        stairs(MinecraftItems.GRAVEL_STAIRS, "Kies");
        stairs(MinecraftItems.GOLD_ORE_STAIRS, "Golderz");
        stairs(MinecraftItems.IRON_ORE_STAIRS, "Eisenerz");
        stairs(MinecraftItems.COAL_ORE_STAIRS, "Kohleerz");
        stairs(MinecraftItems.SPONGE_STAIRS, "Schwamm");
        stairs(MinecraftItems.WET_SPONGE_STAIRS, "Nasse Schwamm");
        stairs(MinecraftItems.GLASS_STAIRS, "Glass");
        stairs(MinecraftItems.LAPIS_ORE_STAIRS, "Lapislazulierz");
        stairs(MinecraftItems.LAPIS_BLOCK_STAIRS, "Lapislazuliblock");
        stairs(MinecraftItems.CHISELED_SANDSTONE_STAIRS, "Gemeißelte Sandstein");
        stairs(MinecraftItems.GOLD_BLOCK_STAIRS, "Goldblock");
        stairs(MinecraftItems.IRON_BLOCK_STAIRS, "Eisenblock");
        stairs(MinecraftItems.BOOKSHELF_STAIRS, "Bücherregal");
        stairs(MinecraftItems.OBSIDIAN_STAIRS, "Obsidian");
        stairs(MinecraftItems.PURPUR_PILLAR_STAIRS, "Purpursäulen");
        stairs(MinecraftItems.DIAMOND_ORE_STAIRS, "Diamanterz");
        stairs(MinecraftItems.DIAMOND_BLOCK_STAIRS, "Diamantblock");
        stairs(MinecraftItems.REDSTONE_ORE_STAIRS, "Redstoneerz");
        stairs(MinecraftItems.ICE_STAIRS, "Eis");
        stairs(MinecraftItems.SNOW_STAIRS, "Schnee");
        stairs(MinecraftItems.CLAY_STAIRS, "Lehm");
        stairs(MinecraftItems.PUMPKIN_STAIRS, "Kürbis");
        stairs(MinecraftItems.NETHERRACK_STAIRS, "Netherrack");
        stairs(MinecraftItems.SOUL_SAND_STAIRS, "Seelensand");
        stairs(MinecraftItems.GLOWSTONE_STAIRS, "Glowstone");
        stairs(MinecraftItems.CRACKED_STONE_BRICK_STAIRS, "Rissige Steinziegel");
        stairs(MinecraftItems.CHISELED_STONE_BRICK_STAIRS, "Gemeißelte Steinziegel");
        stairs(MinecraftItems.BROWN_MUSHROOM_STAIRS, "Braune Pilz");
        stairs(MinecraftItems.RED_MUSHROOM_STAIRS, "Rote Pilz");
        stairs(MinecraftItems.MUSHROOM_STEM_STAIRS, "Pilzstamm");
        stairs(MinecraftItems.MELON_STAIRS, "Melone");
        stairs(MinecraftItems.MYCELIUM_STAIRS, "Myzelium");
        stairs(MinecraftItems.END_STONE_STAIRS, "Endstein");
        stairs(MinecraftItems.EMERALD_ORE_STAIRS, "Smaragderz");
        stairs(MinecraftItems.EMERALD_BLOCK_STAIRS, "Smaragdblock");
        stairs(MinecraftItems.REDSTONE_BLOCK_STAIRS, "Redstoneblock");
        stairs(MinecraftItems.NETHER_QUARTZ_ORE_STAIRS, "Netherquarzerz");
        stairs(MinecraftItems.CHISELED_QUARTZ_STAIRS, "Gemeißelte Quarz");
        stairs(MinecraftItems.QUARTZ_PILLAR_STAIRS, "Quarzsäulen");
        stairs(MinecraftItems.HAY_STAIRS, "Heu");
        stairs(MinecraftItems.TERRACOTTA_STAIRS, "Terrakotta");
        stairs(MinecraftItems.COAL_STAIRS, "Kohle");
        stairs(MinecraftItems.PACKED_ICE_STAIRS, "Packeis");
        stairs(MinecraftItems.SLIME_STAIRS, "Schleim");
        stairs(MinecraftItems.SEA_LANTERN_STAIRS, "Seelaternen");
        stairs(MinecraftItems.CHISELED_RED_SANDSTONE_STAIRS, "Gemeißelte rote Sandstein");
        stairs(MinecraftItems.MAGMA_STAIRS, "Magma");
        stairs(MinecraftItems.NETHER_WART_STAIRS, "Netherwarzen");
        stairs(MinecraftItems.BONE_STAIRS, "Knochen");
        stairs(MinecraftItems.DEAD_TUBE_CORAL_STAIRS, "Tote Orgelkorallen");
        stairs(MinecraftItems.DEAD_BRAIN_CORAL_STAIRS, "Tote Gehirnkorallen");
        stairs(MinecraftItems.DEAD_BUBBLE_CORAL_STAIRS, "Tote Blasenkorallen");
        stairs(MinecraftItems.DEAD_FIRE_CORAL_STAIRS, "Tote Feuerkorallen");
        stairs(MinecraftItems.DEAD_HORN_CORAL_STAIRS, "Tote Geweihkorallen");
        stairs(MinecraftItems.TUBE_CORAL_STAIRS, "Orgelkorallen");
        stairs(MinecraftItems.BRAIN_CORAL_STAIRS, "Geweihkorallen");
        stairs(MinecraftItems.BUBBLE_CORAL_STAIRS, "Blasenkorallen");
        stairs(MinecraftItems.FIRE_CORAL_STAIRS, "Feuerkorallen");
        stairs(MinecraftItems.HORN_CORAL_STAIRS, "Gehirnkorallen");
        stairs(MinecraftItems.DRIED_KELP_STAIRS, "Getrocknete Seetang");
        stairs(MinecraftItems.HONEY_STAIRS, "Honig");
        stairs(MinecraftItems.HONEYCOMB_STAIRS, "Honigwaben");
        wall(MinecraftItems.OAK_WALL, "Eichen");
        wall(MinecraftItems.SPRUCE_WALL, "Fichten");
        wall(MinecraftItems.BIRCH_WALL, "Birken");
        wall(MinecraftItems.JUNGLE_WALL, "Dschungel");
        wall(MinecraftItems.ACACIA_WALL, "Akazien");
        wall(MinecraftItems.DARK_OAK_WALL, "Schwarzeichen");
        wall(MinecraftItems.STRIPPED_OAK_WALL, "Entrindete Eichen");
        wall(MinecraftItems.STRIPPED_SPRUCE_WALL, "Entrindete Fichten");
        wall(MinecraftItems.STRIPPED_BIRCH_WALL, "Entrindete Birken");
        wall(MinecraftItems.STRIPPED_JUNGLE_WALL, "Entrindete Dschungel");
        wall(MinecraftItems.STRIPPED_ACACIA_WALL, "Entrindete Akazien");
        wall(MinecraftItems.STRIPPED_DARK_OAK_WALL, "Entrindete Schwarzeichen");
        rainbowWall("Beton", MinecraftItems.WHITE_CONCRETE_WALL, MinecraftItems.ORANGE_CONCRETE_WALL, MinecraftItems.MAGENTA_CONCRETE_WALL, MinecraftItems.LIGHT_BLUE_CONCRETE_WALL, MinecraftItems.YELLOW_CONCRETE_WALL, MinecraftItems.LIME_CONCRETE_WALL, MinecraftItems.PINK_CONCRETE_WALL, MinecraftItems.GRAY_CONCRETE_WALL, MinecraftItems.LIGHT_GRAY_CONCRETE_WALL, MinecraftItems.CYAN_CONCRETE_WALL, MinecraftItems.PURPLE_CONCRETE_WALL, MinecraftItems.BLUE_CONCRETE_WALL, MinecraftItems.BROWN_CONCRETE_WALL, MinecraftItems.GREEN_CONCRETE_WALL, MinecraftItems.RED_CONCRETE_WALL, MinecraftItems.BLACK_CONCRETE_WALL);
        rainbowWall("Betonpulver", MinecraftItems.WHITE_CONCRETE_POWDER_WALL, MinecraftItems.ORANGE_CONCRETE_POWDER_WALL, MinecraftItems.MAGENTA_CONCRETE_POWDER_WALL, MinecraftItems.LIGHT_BLUE_CONCRETE_POWDER_WALL, MinecraftItems.YELLOW_CONCRETE_POWDER_WALL, MinecraftItems.LIME_CONCRETE_POWDER_WALL, MinecraftItems.PINK_CONCRETE_POWDER_WALL, MinecraftItems.GRAY_CONCRETE_POWDER_WALL, MinecraftItems.LIGHT_GRAY_CONCRETE_POWDER_WALL, MinecraftItems.CYAN_CONCRETE_POWDER_WALL, MinecraftItems.PURPLE_CONCRETE_POWDER_WALL, MinecraftItems.BLUE_CONCRETE_POWDER_WALL, MinecraftItems.BROWN_CONCRETE_POWDER_WALL, MinecraftItems.GREEN_CONCRETE_POWDER_WALL, MinecraftItems.RED_CONCRETE_POWDER_WALL, MinecraftItems.BLACK_CONCRETE_POWDER_WALL);
        rainbowWall("glasierte Keramik", MinecraftItems.WHITE_GLAZED_TERRACOTTA_WALL, MinecraftItems.ORANGE_GLAZED_TERRACOTTA_WALL, MinecraftItems.MAGENTA_GLAZED_TERRACOTTA_WALL, MinecraftItems.LIGHT_BLUE_GLAZED_TERRACOTTA_WALL, MinecraftItems.YELLOW_GLAZED_TERRACOTTA_WALL, MinecraftItems.LIME_GLAZED_TERRACOTTA_WALL, MinecraftItems.PINK_GLAZED_TERRACOTTA_WALL, MinecraftItems.GRAY_GLAZED_TERRACOTTA_WALL, MinecraftItems.LIGHT_GRAY_GLAZED_TERRACOTTA_WALL, MinecraftItems.CYAN_GLAZED_TERRACOTTA_WALL, MinecraftItems.PURPLE_GLAZED_TERRACOTTA_WALL, MinecraftItems.BLUE_GLAZED_TERRACOTTA_WALL, MinecraftItems.BROWN_GLAZED_TERRACOTTA_WALL, MinecraftItems.GREEN_GLAZED_TERRACOTTA_WALL, MinecraftItems.RED_GLAZED_TERRACOTTA_WALL, MinecraftItems.BLACK_GLAZED_TERRACOTTA_WALL);
        rainbowWall("Glas", MinecraftItems.WHITE_STAINED_GLASS_WALL, MinecraftItems.ORANGE_STAINED_GLASS_WALL, MinecraftItems.MAGENTA_STAINED_GLASS_WALL, MinecraftItems.LIGHT_BLUE_STAINED_GLASS_WALL, MinecraftItems.YELLOW_STAINED_GLASS_WALL, MinecraftItems.LIME_STAINED_GLASS_WALL, MinecraftItems.PINK_STAINED_GLASS_WALL, MinecraftItems.GRAY_STAINED_GLASS_WALL, MinecraftItems.LIGHT_GRAY_STAINED_GLASS_WALL, MinecraftItems.CYAN_STAINED_GLASS_WALL, MinecraftItems.PURPLE_STAINED_GLASS_WALL, MinecraftItems.BLUE_STAINED_GLASS_WALL, MinecraftItems.BROWN_STAINED_GLASS_WALL, MinecraftItems.GREEN_STAINED_GLASS_WALL, MinecraftItems.RED_STAINED_GLASS_WALL, MinecraftItems.BLACK_STAINED_GLASS_WALL);
        rainbowWall("Keramik", MinecraftItems.WHITE_TERRACOTTA_WALL, MinecraftItems.ORANGE_TERRACOTTA_WALL, MinecraftItems.MAGENTA_TERRACOTTA_WALL, MinecraftItems.LIGHT_BLUE_TERRACOTTA_WALL, MinecraftItems.YELLOW_TERRACOTTA_WALL, MinecraftItems.LIME_TERRACOTTA_WALL, MinecraftItems.PINK_TERRACOTTA_WALL, MinecraftItems.GRAY_TERRACOTTA_WALL, MinecraftItems.LIGHT_GRAY_TERRACOTTA_WALL, MinecraftItems.CYAN_TERRACOTTA_WALL, MinecraftItems.PURPLE_TERRACOTTA_WALL, MinecraftItems.BLUE_TERRACOTTA_WALL, MinecraftItems.BROWN_TERRACOTTA_WALL, MinecraftItems.GREEN_TERRACOTTA_WALL, MinecraftItems.RED_TERRACOTTA_WALL, MinecraftItems.BLACK_TERRACOTTA_WALL);
        rainbowWall("Wolle", MinecraftItems.WHITE_WOOL_WALL, MinecraftItems.ORANGE_WOOL_WALL, MinecraftItems.MAGENTA_WOOL_WALL, MinecraftItems.LIGHT_BLUE_WOOL_WALL, MinecraftItems.YELLOW_WOOL_WALL, MinecraftItems.LIME_WOOL_WALL, MinecraftItems.PINK_WOOL_WALL, MinecraftItems.GRAY_WOOL_WALL, MinecraftItems.LIGHT_GRAY_WOOL_WALL, MinecraftItems.CYAN_WOOL_WALL, MinecraftItems.PURPLE_WOOL_WALL, MinecraftItems.BLUE_WOOL_WALL, MinecraftItems.BROWN_WOOL_WALL, MinecraftItems.GREEN_WOOL_WALL, MinecraftItems.RED_WOOL_WALL, MinecraftItems.BLACK_WOOL_WALL);
        wall(MinecraftItems.DIRT_WALL, "Erd");
        wall(MinecraftItems.COARSE_DIRT_WALL, "Grobe Erd");
        wall(MinecraftItems.PODZOL_WALL, "Podsol");
        wall(MinecraftItems.BEDROCK_WALL, "Grundgestein");
        wall(MinecraftItems.SAND_WALL, "Sand");
        wall(MinecraftItems.RED_SAND_WALL, "Rote Sand");
        wall(MinecraftItems.GRAVEL_WALL, "Kies");
        wall(MinecraftItems.GOLD_ORE_WALL, "Golderz");
        wall(MinecraftItems.IRON_ORE_WALL, "Eisenerz");
        wall(MinecraftItems.COAL_ORE_WALL, "Kohleerz");
        wall(MinecraftItems.SPONGE_WALL, "Schwamm");
        wall(MinecraftItems.WET_SPONGE_WALL, "Nasse Schwamm");
        wall(MinecraftItems.GLASS_WALL, "Glass");
        wall(MinecraftItems.LAPIS_ORE_WALL, "Lapislazulierz");
        wall(MinecraftItems.LAPIS_BLOCK_WALL, "Lapislazuliblock");
        wall(MinecraftItems.CHISELED_SANDSTONE_WALL, "Gemeißelte Sandstein");
        wall(MinecraftItems.GOLD_BLOCK_WALL, "Goldblock");
        wall(MinecraftItems.IRON_BLOCK_WALL, "Eisenblock");
        wall(MinecraftItems.BOOKSHELF_WALL, "Bücherregal");
        wall(MinecraftItems.OBSIDIAN_WALL, "Obsidian");
        wall(MinecraftItems.PURPUR_PILLAR_WALL, "Purpursäulen");
        wall(MinecraftItems.DIAMOND_ORE_WALL, "Diamanterz");
        wall(MinecraftItems.DIAMOND_BLOCK_WALL, "Diamantblock");
        wall(MinecraftItems.REDSTONE_ORE_WALL, "Redstoneerz");
        wall(MinecraftItems.ICE_WALL, "Eis");
        wall(MinecraftItems.SNOW_WALL, "Schnee");
        wall(MinecraftItems.CLAY_WALL, "Lehm");
        wall(MinecraftItems.PUMPKIN_WALL, "Kürbis");
        wall(MinecraftItems.NETHERRACK_WALL, "Netherrack");
        wall(MinecraftItems.SOUL_SAND_WALL, "Seelensand");
        wall(MinecraftItems.GLOWSTONE_WALL, "Glowstone");
        wall(MinecraftItems.CRACKED_STONE_BRICK_WALL, "Rissige Steinziegel");
        wall(MinecraftItems.CHISELED_STONE_BRICK_WALL, "Gemeißelte Steinziegel");
        wall(MinecraftItems.BROWN_MUSHROOM_WALL, "Braune Pilz");
        wall(MinecraftItems.RED_MUSHROOM_WALL, "Rote Pilz");
        wall(MinecraftItems.MUSHROOM_STEM_WALL, "Pilzstamm");
        wall(MinecraftItems.MELON_WALL, "Melone");
        wall(MinecraftItems.MYCELIUM_WALL, "Myzelium");
        wall(MinecraftItems.END_STONE_WALL, "Endstein");
        wall(MinecraftItems.EMERALD_ORE_WALL, "Smaragderz");
        wall(MinecraftItems.EMERALD_BLOCK_WALL, "Smaragdblock");
        wall(MinecraftItems.REDSTONE_BLOCK_WALL, "Redstoneblock");
        wall(MinecraftItems.NETHER_QUARTZ_ORE_WALL, "Netherquarzerz");
        wall(MinecraftItems.CHISELED_QUARTZ_WALL, "Gemeißelte Quarz");
        wall(MinecraftItems.QUARTZ_PILLAR_WALL, "Quarzsäulen");
        wall(MinecraftItems.HAY_WALL, "Heu");
        wall(MinecraftItems.TERRACOTTA_WALL, "Terrakotta");
        wall(MinecraftItems.COAL_WALL, "Kohle");
        wall(MinecraftItems.PACKED_ICE_WALL, "Packeis");
        wall(MinecraftItems.SLIME_WALL, "Schleim");
        wall(MinecraftItems.SEA_LANTERN_WALL, "Seelaternen");
        wall(MinecraftItems.CHISELED_RED_SANDSTONE_WALL, "Gemeißelte rote Sandstein");
        wall(MinecraftItems.MAGMA_WALL, "Magma");
        wall(MinecraftItems.NETHER_WART_WALL, "Netherwarzen");
        wall(MinecraftItems.BONE_WALL, "Knochen");
        wall(MinecraftItems.DEAD_TUBE_CORAL_WALL, "Tote Orgelkorallen");
        wall(MinecraftItems.DEAD_BRAIN_CORAL_WALL, "Tote Gehirnkorallen");
        wall(MinecraftItems.DEAD_BUBBLE_CORAL_WALL, "Tote Blasenkorallen");
        wall(MinecraftItems.DEAD_FIRE_CORAL_WALL, "Tote Feuerkorallen");
        wall(MinecraftItems.DEAD_HORN_CORAL_WALL, "Tote Geweihkorallen");
        wall(MinecraftItems.TUBE_CORAL_WALL, "Orgelkorallen");
        wall(MinecraftItems.BRAIN_CORAL_WALL, "Geweihkorallen");
        wall(MinecraftItems.BUBBLE_CORAL_WALL, "Blasenkorallen");
        wall(MinecraftItems.FIRE_CORAL_WALL, "Feuerkorallen");
        wall(MinecraftItems.HORN_CORAL_WALL, "Gehirnkorallen");
        wall(MinecraftItems.DRIED_KELP_WALL, "Getrocknete Seetang");
        wall(MinecraftItems.HONEY_WALL, "Honig");
        wall(MinecraftItems.HONEYCOMB_WALL, "Honigwaben");
    }
}
