modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
modId="slabsstairswalls"
version="${file.jarVersion}"
displayName="SlabsStairsWalls"
#displayURL="http://example.com/"
authors="IchHabeHunger54"
description='''
Adds slabs, stairs and fences/walls for blocks where there are none yet.
'''
#[[dependencies.slabsstairswalls]] #optional
#    modId="forge" #mandatory
#    mandatory=true #mandatory
#    versionRange="[28,)" #mandatory
#    ordering="NONE"
#    side="BOTH"
#[[dependencies.slabsstairswalls]]
#    modId="minecraft"
#    mandatory=true
#    versionRange="[1.14.4]"
#    ordering="NONE"
#    side="BOTH"
