modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
modId="slabsstairswalls"
version="${file.jarVersion}"
displayName="SlabsStairsWalls"
displayURL="https://www.curseforge.com/minecraft/mc-mods/slabs-stairs-walls"
authors="IchHabeHunger54"
description='''
Adds slabs, stairs and fences/walls for blocks where there are none yet.
'''
#[[dependencies.slabsstairswalls]]
#    modId="forge"
#    mandatory=true
#    versionRange="[28,)"
#    ordering="NONE"
#    side="BOTH"
#[[dependencies.slabsstairswalls]]
#    modId="minecraft"
#    mandatory=true
#    versionRange="[1.14.4]"
#    ordering="NONE"
#    side="BOTH"
